apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy
  labels:
    app.kubernetes.io/name: ntfy
    app.kubernetes.io/instance: ntfy
    app.kubernetes.io/component: ntfy
data:
  NTFY_ATTACHMENT_CACHE_DIR: /var/cache/ntfy/attachments
  NTFY_ATTACHMENT_TOTAL_SIZE_LIMIT: 3G
  NTFY_AUTH_DEFAULT_ACCESS: deny-all
  NTFY_BASE_URL: https://notify.guedescloud.com.br
  NTFY_BEHIND_PROXY: "true"
  NTFY_ENABLE_METRICS: "true"
  NTFY_LISTEN_HTTP: :8093
  NTFY_PROXY_TRUSTED_HOSTS: 10.42.0.0/16,fd42::/56,10.43.0.0/16,fd43::/112
  NTFY_UPSTREAM_BASE_URL: https://ntfy.sh
  NTFY_VISITOR_MESSAGE_DAILY_LIMIT: "1000"
  TZ: America/Bahia
