apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ntfy
resources:
  - configmap.yaml
  - deployment.yaml
  - httproute.yaml
  - namespace.yaml
  - persistentvolumeclaim.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml
images:
  - digest: sha256:f2419f405127afa868f10985c1a41449e673477cee1eb19994339a5ae8b592e7
    name: docker.io/binwiederhier/ntfy
    newTag: v2.27.0
labels:
  - pairs:
      app.kubernetes.io/part-of: ntfy
      app.kubernetes.io/version: v2.27.0
