apiVersion: v1
kind: Secret
metadata:
  name: ntfy
  labels:
    app.kubernetes.io/name: ntfy
    app.kubernetes.io/instance: ntfy
    app.kubernetes.io/component: ntfy
type: Opaque
stringData:
  NTFY_AUTH_TOKENS: ENC[AES256_GCM,data:vDE/5UaISJin5vIlEYhSQ6hDBg9lq2dNMHZ54r4cyqHmV5UuZtVmJg==,iv:+Dme+qj3p0KSZvPWUKCUmXuc9/CwFKpvAMq5cNHYjyY=,tag:cNLb1hKvWTSw5P/F5IbpMw==,type:str]
  NTFY_AUTH_USERS: ENC[AES256_GCM,data:s7ttjRvgqedYj7Iz1gmLnt40PtZzBd4AikBlnLfeZs0CH/Zt2hocTIGZijog3tW4uNIJqmosZ/b+UgNEDJOEb0heJcwlLUjpjpM=,iv:CljlHIlu8vEHPk0Wj3rob8Xseam/N4HzG5YeiOoXRqo=,tag:EOmhBZ98mZ2gMAS7q83OVg==,type:str]
  NTFY_DATABASE_URL: ENC[AES256_GCM,data:K3zIRiQ93JL0gTKIwA1QrLyIC5Fb8vREMtDeT/NWGjCCs1MxVATx0J2gfHmCoYWhcFj08ekCZSdXaOIUo+OACBij1q46kxG0SDgJUW22XNiMow4CFXf0rkAJiJJ3G+F2EnfIiPnfaHlQNZdI8cRZ9kRYz/pz5utfhp2+zZVmrQ==,iv:DJLOyGB37895BqRAzTmp1F5IAAxK7ulNJSiH0G5X6bE=,tag:NY1ooZbfU5SuLexBy8EY0A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFIrSEhvcEJx
        YTEyNVVnZWFDcHlUUjFuYk9LRFBHTnF0VnFlTzFLSHljV2s3SEhQeTEvV0UyMFVX
        N3h3UzIxY3R0djc4eDJSL0UrekxrdEROQ2FPdUlIcWFJa1d2c3JFMVY3TzJVV1Ex
        QngvL1dCOHg5Qm5HZ2tSQWVtUnRDRmpWZ0NhRXVoTWVxSnozVnBFTENiTVBWMitr
        ZEpFdnZwMmdFbVJqczBLMTk1UFptWHhpVFpSdUVVZWExUnk0SVVQeVBYVmd3RzRl
        UU1iZ0dCcGRBOVFIWmkwc3V5V2cxQzNxOUpBd2dobXBKK1BFV3RPd3d2NG9TT0k3
        SW5NaUJSaVNHK01DRVczN0lSYkpVMmUvdlVoMVFSaUlGT1FVVXp6SGcvZjB0cmlo
        R1lLTWJEVnpFbVRmNDBsMkpob2NkTExqNDB1Z2JsWExqMzJEVEs3d1ArWDBHdWRY
        S2FDa2ppS3VSQ2FUdUNUM1lPYWpSdHBra3AvS2U1UElqcjhOVUU3aXVLWVduemV2
        QmJIVWxZQWl3ZFhqc2hUR0ljdmVEaU53L2h0WWxZOWJ6aSt6Z01MeDRCT1pBQTlH
        ZUJLMGlDdWhaU3d2ZWk3Z3JUMThLc0tEc2pHZ0RZQzl0VlcrKzR5eEc0ekJXSmdn
        VnhmQngwSy9xRVRhY1FtSkk3Y29aR2pCdmlSOC9rekhhclYzZVY0ajdKQ0dTOHI4
        VFcreUd1VVVVQUpMTUFSaFhYSFZyaWtxYjBSQjhheGk4YVJpbGhZbUt2WlRzaWxo
        UVNjdlFQendNblN5MXNCOHZXTWQ2SmduWGQ1NG1wVjJNZmxGQ0t3NDlpNTFnaTho
        WktaN2NLbjRjOEdWZkVUWEF5VjJBdjJRZFVrbVRseS83OGdyMTRBZFpuMG5HY1hw
        aVk2VlAwZDZUWFFOYmRHVFlKSXhwQTB2K3ZuQmsvekVxNy8wcmpaR2xFRVhpUWJE
        VXVwdmdmRFVhbkYyYVpnYmVpVEMzK3NtcTFFNUVnWjEwNlVBOHVFcHNBbVhJb2RP
        RHdZRnFtRUx5U3UvTzNkbytkUWtvVTYvWTdFVUEzYWpsQm54b1BOYUM2ZWpSc1Jn
        T2xZNlpBck4yeUZuWHFJN09ZUjkxUkZFUTFmUjJTZTYxc3FxY3pTRWZxT08vY1JV
        Yy9pUmVhZTg5Z25DYlhtOTNIQ3BFbXQ4emZycWJGVktJQllidXNxbFZZZy9sOFMr
        WE1tMFJoVTV5dk5hR25UTld1bURaR2hoT3d3U0ZOWEtXNklGNGJ6RWRMcXcvdjlX
        ZTlCTUVrMFYwb3NldWFSQzVoVmhic3l0UGc1M3g3andZb0hZMEt1SGVudVZ4R1RX
        NnAwSzBGTGF3UHU4MitpWXZZUnExOEYxU2R4T3dFNk9FV0g3RVNsbDlTdXE5M1N6
        R2J0OUpXNk1NWFM2aUQxeXRZWEtaZ29OSEltUUxpUHROK1ZaQk5WdVhNVlcxeHBY
        Y1kwc3dsa044SWsvaHV6R210TVkrdWRPM3ZQUExKRWM1ZHdSTjlmU0xaUktNN29R
        SGtadzVxUDdFOGNwK01JTHBndCtjZTQ4OSt0aWFQdnRtYm5aa0hoSFVTcTVudVBG
        YjNTNFUvc3lnbGV5ejFac1cwQUsxa0p0NDdJTm5BdS9GRDVyVnM5RG1hMkZNNzJI
        aXRJK0t1Z2hNNjA2bVFhSFRzWVBtbzJhMkZJeUh3UzVJUHluK0hXUWRuZTFKVkY0
        MVlYZE1LdEF4cHFYVUcySUtLVWNlM2VRVUZSQjBTZENXSVYzZm16ckcyaUM1ZVlG
        U0JFT3FrU1VRT2lWbHVKT1RkOXh0NEkvMjE3dlJaTFhVM2g4enRCd0V2OUF1Zllu
        WUFLV2ZtWlkrd05QN3JpeHJrVER4NDBwVnFMaS85aE9JRC9kZGdFdGJkVk8vSVFU
        MXpucjVEU05tNmtFOVJIREVUYUQvaGExZVhnZHYxM3NVdWtpMkdFLzViYnBkUQo4
        R3pVMWcxSWxibkVBeXNic2VGd0hvUjFEQk1HU2YxdThGNFcxeDk0bzRVCi0tLSBL
        T01oaUZSS0tXYnBtMnQ4SkhKbUx2ajlVOEVxYnN1R21BVmFjblFlWWtrCsCPGTPx
        +7x1BZ+VMDjJ39+eie1K9XQMdWsiFCRs849474UsoxoSVXv7qAMdGi2zi1u4LbPk
        vSreZrH0X5gh6IQ=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1pcc952wp5r5svd72s6anpqzpth2m3lzzp7t5p072dxss4jeymjwrrq8gw5c7szx0lwtazuyvnlupq5n8zv2nxhq7yzwp34pkxdvnaj2u3evlddrkyqxrje255vefhhru9jzqe9z7yja78wgw5ffvlzlqcgrrsu5n0dpaxf9ra8gzdryyht90z4w45wa03keqrgfxyfmrsz30wz7dkgrhr6us499q2pnuj6pthq48qksqmqy8tlpnfv7qr2kswqycnsdal5srludhclg80enjvth6ngmfwmp82u3thdsjghge5zs77qqzm5as39v4e6mxz8lf8g0wg3ds6gaguhj9f3hqs448c988x4hcqyfe97urr00qhverqec22flfkgkgngs8awpkwjeez93mp0zuk7agmygmdrcy8z9zsp6z27sl8f3x6tsgelg3gf8tj86pedvp0etllw3qqyw6wpdq0fggq7qcv6xw6eghzdhv0ljkwwg5v9ahdsy5ngs6673khfhqr8ae7yggk29mhqncgttx966fhfvq329edcza827tgmwvnj60x6hg4qnz4stsnfncmk6m0t00czqrpzuskvm368yth2s9gev0k7g762h6gx6709sred9qp6gr0qes9jadv3d94pynkpjhwmz449ypfy3pdqvhhn78zj92p9snqqqxavz8lzk88mcjdkeqhqvz4dgffja78pe44cukue7vxwdfstwgj24p4632fmzmnfrevst44ssr42kz064ez49mtyjvxmegrdsvadv8k635qffefl42w90f56mn5g0ww725tlay8hsuvevth0uh8vjjfaagkygr3cp3xpjuc9rwc2nyup6df4pk669f256m3ny3s53s6z6ra3sr773803z6z6f70zdqd2uxd36xtanrszj8scq882u8djntyreylvn9gppfyr4xgf67e7at542222cvyusm8jchcqzy7xpuh6v88qf59cw7j5vmmx53q2cpvdgsxeeptyp9tq4pvxshkz9c9muv6lz5ttupxss43z4er7tnsdg42kfzy2qvtfsypfk7wqupv63kg9kfp30nyqcf02v8pd5gl0dzj02eheq35u8fxy705wmu9gp9ytptetz9yrdszzxmszac90un82sgvf42g4v4jp9f4a70gkazhf5vng2pct7z99ggh46lccwgvfjxvmwfz5ff8j5jmzrhpu9nzmtvr8x8evn82gl9h6p5gkm28uhurlwtg32uh8yst3zlq9xygwu2hcm32lj0f3h0kecvvd4m59gteyjs9zpelyj90k4p0g9jrsz5y8edjrhdzanrm353xd6hymuh2qu890k97dgp3ppds56gsza50ddcxve36xr3f4ft08dxlax5589nscuagaa8v0zcntf4d5asrzu8jknr42rk2y34mu54r0cjc0quy278yf657ez2nt33cr9qy3xesvx9uc60juwteuqvttec8knag9mv3q0d3jq9dau8cp5295m4dzjzya384k36rpjgl85r5weaqk60vlymnuugzpj5tyur3sxjds7p55ndjeflhu237zuu84fdpze2csnqzf3ak8q6qz7cjxsaqjhnv5y5ysp99w35u6rxs4u0f03ks7tv9de90cv5cca6sq2pfr6mv4nw8eu52qtp93dn4hgnzfven2r3lrpwelkr3mrpwn4wcrwcqjzytcuzse54ug9hdfnxn8f6edpqy9ztjwnp9mfy2w32keapqjk8dcvjd6n6yzkk2hry55d8cww4p74sdgwrghh84hx4wg57udyul3tmzpmfue7te9wtrxpn6gu287eu42xz2h3f88genu26030ve4nwvs0xcghmflvcjpp0sk5h9476vezhvp2k3kqyjvvt57qel7y8n4f70kn5ffna4m20x3pn2uy3d5c2ywqt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-22T15:14:29Z"
  mac: ENC[AES256_GCM,data:tbd5FJGmeybYtAEgbSHJ85IQtWv4/olE16wktMnJhvPVYtK2h8ssxxbuPUkPQPdif01mJqZ1UhrntyBzxItfNPTOnesl1U6a1+ULQiZiE5iVoIJTvbGmlgBiU55NYDm5BJTmsSAOpTaFbzS7dzKRUdZG7RYtgvlXjTnYooxULl4=,iv:Iu4YWjXzn9Ja3MD9CMumcEEsPkyIA6zjDXD8lLlICF0=,tag:C6wkGi6qZVdc2pLCa6yvxA==,type:str]
  version: 3.13.3
