apiVersion: v1
kind: ConfigMap
metadata:
  name: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/instance: immich
data:
  DB_DATABASE_NAME: immich
  DB_HOSTNAME: postgresql-rw.cnpg.svc.cluster.local
  DB_PORT: "5432"
  DB_VECTOR_EXTENSION: vectorchord
  HF_XET_CACHE: /cache/huggingface-xet
  IMMICH_ALLOW_SETUP: "false"
  IMMICH_CONFIG_FILE: /config/immich-config.json
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning:3003
  IMMICH_TRUSTED_PROXIES: 10.42.0.0/16,10.43.0.0/16,fd42::/56,fd43::/112
  MACHINE_LEARNING_HTTP_KEEPALIVE_TIMEOUT_S: "10"
  MPLCONFIGDIR: /cache/matplotlib-config
  REDIS_HOSTNAME: immich-valkey
  TRANSFORMERS_CACHE: /cache
  TZ: America/Bahia
