apiVersion: v1
kind: Secret
metadata:
  name: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/instance: immich
type: Opaque
stringData:
  DB_PASSWORD: ENC[AES256_GCM,data:nonUudNrIwD2BBtVJaFfSKbcNDlC3yVjgcttA3FpZPXw4S2ra+hZuMCHAlRhyYGSLJCIGAJc4aw3RAMykdWWtg==,iv:puCZGFRAnv3WeCkV+7uHRAB6Ho3ALjqfGpEyMuPLH/c=,tag:n78YRS2FiufBSQccdb+AgA==,type:str]
  DB_USERNAME: ENC[AES256_GCM,data:FERpG9b9,iv:bO/1BO9nDB5JqNf+3MGkw1rXJRS7Gftv3/5ZBlszw5k=,tag:6vL5xfbjxmZVXkAxxUA8zw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDZ1ZmY5dDVr
        ZW5pYTI0bmd0dnBleVBEVVhrZ0NDc1g1bFd1K1hhQWhjTTcybVJUOE5LdHc5OU5L
        L3ZJMFY4QWpGNFpQd0VOWHNLYVA4bnVhNjA1N2R2U05ndGZxNkU0cEhtNzFsQ3ZG
        K0V0Z3h1ZWt4NG1ERHc1RDVkU09paTk2OW11SGtBamZlUlFWYk1Famhqd0djeGpR
        R2sxL3VCb1Y4TlE0TVFOMVRVVkxTV3F4K0h5V1ljV2s3OHk3ekJ3QklnWUpoRkMz
        Z0Vhc09Ha3JNTk9OVm0rbTVIbEdBL0R6V3BDTXJJb1c3Z3dVNHNMQWJqNTJkbldm
        SUZsZ3FxMjhwb3FBOTRRSXhKYzMxQklmUHFJakNKMlBZL3U0ZDVBT3hydlNreVZW
        ckhmd3RsL2l3cjducWgyRjUyTUxKVk1BQUwvS2pZSXFXT0Rra0ZXemE5SXlrQTUr
        SEJMWWRrS3p5RFZYYi92NDY3VkVuQ21VeHg4RzhtUDd5cnpqQ01jbCtSUUxoMFZB
        ekRCRVc0V3JGWDBNcHZxUHhYR2YvQ1E3a2pZSGllWkZHWmNtU0k4Y3ovRlVqM2Jk
        NlI2V1g3OGQ2aHlKSE9GVFpWQngyV2RXdGFpNmoydmlmcUZ3UE9JckJBbmVjdGxI
        SXdDKzJQNGE3eVNnRU1IZUwybHdpbU5lLzhzdysya3htZXdyLzN3QnV4OHdWZjNu
        OUdGWW5QSTV5RDNrY3gxYnh6enlFcTBsMUVrMWpBY0tQRENzM2hodTJyend3UktP
        SXp0djE1VXM2R1dyMFdMd1M2eVJXREhITXZrYUszS3VhMUEvRXVGTEFhM3dheUtn
        VkZXMmZjbURJaDYzSE9DZlpNWFY5YkY3cE53ekdBelhtRG04RkFiMUsyMlpPM3ZR
        MUtURi8rQVR0K1FlWlkzaEgwemZsREJIK0srMlNQeUdjdWNjdlhBbUNwOXFXZEhM
        UWZNeUIzU0paSk5XaUttcHpmUkFZWFgyNTMyTFNNMlRwdHpyb2lGYXUvRys3c1dQ
        NitScW91YnhxVElYU0UvVlBRcUVIMjJtQlc3MGwrK1orSElMMjdmNnVYK2dYZ3hT
        engwMFpldjVCWHFUcWFKQzNKSE5HbnpEYm5WcVNBSENDZm90KzcvNzRENDN5RTlj
        Lzl5RTRWTHJ0b1E0Y1VkMnVkaEFBR2d3bng2ZUNuTjNOcTBHZ1AxMEQzb1JTODRH
        R1ZIblhrbE5hYmZaY0ZvQzlicWM0SWdoYTZjeG9YdjI0ZUU4REdZb2tVem1zQlJ6
        a3Vtb1F2b1dNa3lZNHl0bzNxZmRmcGRlZjlML2hKT0FnVmJhc1hVWmdORkdyNW85
        QTZONzErb2dxWUJWQ1VZSEl3ME5UcWYvekpUbFU0NkRUeUpxUjhVb0pJWFBLd0h5
        cGRRNjU1WEtPZGxWWlBOSzRyR1pCREE2SkNDamZPeXNUNXZZRUtiWWRiYXcwWCsw
        c3RxQldlRWJBa2ZyaXlrSEdYS3FOQW5XWk9EZktoTG1OMEowUVBMTE50NXZ6L25t
        aHYyd3ovVlMzeUhsZTljVnc1bU5tVHIvL1ZPQ0FKUkVROTRwa0kzNXcxRnBUL3NY
        bEpDa00vWk1GQ1Rnd2pLUlBjaTVFNkR0dTJEWU1PdU9abnV3aGFIL1VBZjlMYk1X
        UTRlUkFkbUFNQ0RONC9oNzJ3ZFQyYmNXRGs5S2UrTGZlZlZDbE1wVW5SWnplRlhB
        R3hBZEI5VFdoam5vZzFKb3Z1SlhWWVhiaGRUQU03NlFVdCtIdlN0L1pEdW5UUmhh
        Nnd5d2dtZURES05XS1RwcnFmZFBUVlgxaFRyN2RuNnQyaEV3MTFQcVpLZzdGWVZV
        NHJ3Q2JhQWZ2WVVQRlA1WGppNTYwd3ArS21LZWRoOXhZenRjbGhSdHh4cUxBR1hZ
        OXowRHFkblc0NDkwZ3U2WHY5dFhuUS9pZU4zSUNKRzhRaUVwcHM1NWRTY3pDdwpx
        VXEzdWNwaVRtOXRQbGlvallHcXhYTk8zUGRUc21ZTU9YYlJjeU9LUU5vCi0tLSBt
        UFZZKzRBSHpvdmZDcmczN0c3MU5xNHBlaVppcEdpbXJuNkQxS1hCL2R3CsjpAeg7
        rwt7s290pKqGP21F0+yV8Et+WBmcKWfCtpNi8+uFa9d8eEoedgPQ/lzTECWpVJnN
        cs4JOiT16WvlPPE=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1pcc952wp5r5svd72s6anpqzpth2m3lzzp7t5p072dxss4jeymjwrrq8gw5c7szx0lwtazuyvnlupq5n8zv2nxhq7yzwp34pkxdvnaj2u3evlddrkyqxrje255vefhhru9jzqe9z7yja78wgw5ffvlzlqcgrrsu5n0dpaxf9ra8gzdryyht90z4w45wa03keqrgfxyfmrsz30wz7dkgrhr6us499q2pnuj6pthq48qksqmqy8tlpnfv7qr2kswqycnsdal5srludhclg80enjvth6ngmfwmp82u3thdsjghge5zs77qqzm5as39v4e6mxz8lf8g0wg3ds6gaguhj9f3hqs448c988x4hcqyfe97urr00qhverqec22flfkgkgngs8awpkwjeez93mp0zuk7agmygmdrcy8z9zsp6z27sl8f3x6tsgelg3gf8tj86pedvp0etllw3qqyw6wpdq0fggq7qcv6xw6eghzdhv0ljkwwg5v9ahdsy5ngs6673khfhqr8ae7yggk29mhqncgttx966fhfvq329edcza827tgmwvnj60x6hg4qnz4stsnfncmk6m0t00czqrpzuskvm368yth2s9gev0k7g762h6gx6709sred9qp6gr0qes9jadv3d94pynkpjhwmz449ypfy3pdqvhhn78zj92p9snqqqxavz8lzk88mcjdkeqhqvz4dgffja78pe44cukue7vxwdfstwgj24p4632fmzmnfrevst44ssr42kz064ez49mtyjvxmegrdsvadv8k635qffefl42w90f56mn5g0ww725tlay8hsuvevth0uh8vjjfaagkygr3cp3xpjuc9rwc2nyup6df4pk669f256m3ny3s53s6z6ra3sr773803z6z6f70zdqd2uxd36xtanrszj8scq882u8djntyreylvn9gppfyr4xgf67e7at542222cvyusm8jchcqzy7xpuh6v88qf59cw7j5vmmx53q2cpvdgsxeeptyp9tq4pvxshkz9c9muv6lz5ttupxss43z4er7tnsdg42kfzy2qvtfsypfk7wqupv63kg9kfp30nyqcf02v8pd5gl0dzj02eheq35u8fxy705wmu9gp9ytptetz9yrdszzxmszac90un82sgvf42g4v4jp9f4a70gkazhf5vng2pct7z99ggh46lccwgvfjxvmwfz5ff8j5jmzrhpu9nzmtvr8x8evn82gl9h6p5gkm28uhurlwtg32uh8yst3zlq9xygwu2hcm32lj0f3h0kecvvd4m59gteyjs9zpelyj90k4p0g9jrsz5y8edjrhdzanrm353xd6hymuh2qu890k97dgp3ppds56gsza50ddcxve36xr3f4ft08dxlax5589nscuagaa8v0zcntf4d5asrzu8jknr42rk2y34mu54r0cjc0quy278yf657ez2nt33cr9qy3xesvx9uc60juwteuqvttec8knag9mv3q0d3jq9dau8cp5295m4dzjzya384k36rpjgl85r5weaqk60vlymnuugzpj5tyur3sxjds7p55ndjeflhu237zuu84fdpze2csnqzf3ak8q6qz7cjxsaqjhnv5y5ysp99w35u6rxs4u0f03ks7tv9de90cv5cca6sq2pfr6mv4nw8eu52qtp93dn4hgnzfven2r3lrpwelkr3mrpwn4wcrwcqjzytcuzse54ug9hdfnxn8f6edpqy9ztjwnp9mfy2w32keapqjk8dcvjd6n6yzkk2hry55d8cww4p74sdgwrghh84hx4wg57udyul3tmzpmfue7te9wtrxpn6gu287eu42xz2h3f88genu26030ve4nwvs0xcghmflvcjpp0sk5h9476vezhvp2k3kqyjvvt57qel7y8n4f70kn5ffna4m20x3pn2uy3d5c2ywqt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-23T14:03:32Z"
  mac: ENC[AES256_GCM,data:kN3fn8gkmPXV6KCbfNX1Uw/YdW53BmP5Y5VeQJMWxbH1m7x0sA8Zpu+CpEAaO/YQXK94hOl57yExjD1vtDg4NxHXgouVCqgAymoFwTqPAZZSq8R+sRwi4TNCUOKQKqnBdnec5Msm2F1FQecN5XpRl5dNBR17ZSzfrdSHQNaJjmU=,iv:QK3ofZvjWy+DRubnrp8vZyVKupedH5YmIPw+vslT/mo=,tag:O7eB+gLIByS1aUiSjbDU7w==,type:str]
  version: 3.13.3
