apiVersion: v1
kind: Secret
metadata:
  name: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/instance: immich
type: Opaque
stringData:
  DB_PASSWORD: ENC[AES256_GCM,data:IaE9LlrTzM1bkzPb08ijX4hGWnVyoBJhWLefcn7ZNPp/WYwnlSZFMvn2PWdffpBE860K+zYAQ3hWVTbw1neZgw==,iv:jKFlDEGuBVCcuWHZOkRKol2Wl+yE6LUTupPPdcdTjQo=,tag:ek1e5RlgoEMo0H3qkOmfyA==,type:str]
  DB_USERNAME: ENC[AES256_GCM,data:uvFyr2u9,iv:ZY8uHhj0Gp1uwl1Tr6J1yZGmfZ5u8VWYFiooxFbhkbk=,tag:rR2ALHm0JU6+X+d+bMX/PQ==,type:str]
  IMMICH_CONFIG_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:cQH8ZX80P4jH0Bth4xatu/8Ryj9ppsMji1OliFEQodZ++QjYwyrenJTx1+heY338vlvsLDXNmqKalECpZX3eMGOWK4slkMKe,iv:H6fWVbWQG0vAx4ksER2YultN62Hj5m4XqMfOHpFUhgM=,tag:Z804ROKVnv98MQKNOw/LJA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGlXNzhQT1NC
        VTVBS3pxMUdaTlJuL1ovME5GM3N5YnpYaUlQNkcrS1dVVnQxTE9aME9Nc1Qwcm9N
        dXhFVmo0MFhiWDlvQWlHTFBOSHlKSTMrMTlLYzNjdnRpcDRlT3ZLV09WUGpvdVpK
        WStxSnlSdGRtT1ZPZnhlblptUUZwM1FlUGU2SjJlZU5EbU92NEVtQjJRSk9BUTFy
        VmdIM2NFWmhwUHMzVUtJWjVTbUVFM1puLzk4bEkxY3hxNFFSbGZHaWNTUmNqWmVm
        S1hhUy9mWTFVMU8xL1I2Wi9yNzdUVmt4ekhTaWJFbXhjeFJ0dU9jb2lmZm1kSFJO
        YWNMRDVHdWVMQjFpV3dSQlJnZmY2d3VZQ1BnelQyYkVzd09vb1JObWNrVmhnUkgr
        NWNFY255cUYrYm83dnd6bkZrMHlZUld1dzNzM3ozSEZqMFlQTFQ2M0s0UDJ0SEFt
        WUxTYmdCYXJaWkRPNUdvWlVFcWRwd1JvcE9aenVGejBvOTNmcmlnbnZ2RmdmUHRH
        Tk00YjBnSVlLb3E3RVg5d3ZpWVozTUhvMlk1WlBTa3R3OG1wK3A2VWRqK0tuaUxl
        aFZLR29GdEdiNE45clVYbHhjdkpZZDVuVFQ5d1ZrSkdEOXhDZTIzOVl5ZGpuUlFU
        LzlIektNME0zVkhuNkZDcjZtSTVadUN2K0JOYVVXNzF5YkNabitjWVlHemIyY3hy
        Z1MyNW5YT2pSSGh3eHJRa29Qa2I0UzZROTF4Yk01OHo0QVFCQ2RNdGlSdlMrVW11
        cU8xdzhaVmFqNGpxdFVLTmZNclNwdHg3K1BOS1JUek5aUXJhZzY3d1ZwLzFxV1pJ
        UVdjVlo1QksrZlZxQWdCUGoxTGszTXN0cmpGWjdlM0JBTnoxOERwbFRMV0FvdXlN
        RExNbUtBWGxaMithaHBySkIwV001VEYrZVVKQkFueThoTTVQWG91bE9KN1VBd0hi
        SXRHejhWclhjcTVPanl4a1RMZU9JUXlEb0dGRm1BSUtEc1RNL3YrcmRMMy82alVM
        TFp6N2lmbzdXcllOZldFRkNHamw2dVBPSHpQY200MFZubnMwUm1kb2FCREZvbHlG
        OTJhaXQxN044b29aZ0M2RzFaNlcyVk9pY1RkNDNneEhVNGdDcEh3WklRSE9WOC84
        dDZMMTVYY1ArVFFCNndhUjNFWW5jekN5S0pPMlVROU5acXliUmhSQitIZG9FN1ZV
        VWhnUGVYbjh0SklMT0x0THRobm5ZdzVhWExtemxmT3lWbnc5dU55UWtxZnkwa1lQ
        bmRtYXBmVmhtNy9GbkpiSGZRS1NDd29kNVdqV0VUV0daMlNjaHBndm9hL0xyL3dn
        Vitnc1FKbG1FcWdROGpYMFZucGJ3UVF0bXROWG9ValhPQ1J2UGlMNWpzMjdnK2sw
        ZjVNazhob0xXUEdGNWI2ak5GWlpOT0FMeTJEdVdCSkkyN0NSQU03K283TEdUMmFi
        STM1Q0FNd3BJeXNEQk00RjdXRXRPM2t5UVAzTmNZYmdPdFdUZzY1MVVJRGpueE8r
        WnBneWtrVkNDS0tqVGlkT0xTdGhOTzhrUGFoZ0tUSHp2Ym1RSzlhQUlpUjlzdTBK
        T29jaW1LMTBKejlnc2RleC94VEtsc25UR3prdFppeExsdi9FbnJkVFc1Q0RhWnB3
        L1czaUVWYk5IK0ZCYU9JZEtUcTJ1MTNRaXlVMjI4UERJaUh4QVRLLzc5ZjQxZENC
        L2c0L2lOQU5naHFUMGYwRFo2Q2ZoY1diNUJVK0thdkpiTEVzaE1UMHp6TU4yWmEz
        ZmtTVklHZjhEZ05ic0J0NERQYlJmWEk4WVl3QnVKc0xyNGYwb2lVQkpmU3ZPaWY5
        QUtuWEdqU1ZrVVk3OFgzSDgrSm44OEN3dGx6NWFQK29tR0JEbVlwL2EvSXhwYlhC
        OGYvNGY5bVZoL3d2MHA1MjlSYkZyeDBoOGFxMFV3ZkF5Q3BJYjVGTXdNSFBVdwpV
        TUk4OG54dy9rOWNNd29qT3JQODViRGdhL2kwYWRDdkFsZDRRRGFMTWVnCi0tLSBo
        TVZMSnBrUUVnTks5MlBWdnlma2hwUU1NSnR4RzdaUVUyR1pyTmU2TURzCnKUUQyR
        6X+RBsoElDEmYz+H6okpvC1+o6U7K63MMYgFLBTXmt0H188DDuC0cowU3a8BINWC
        h+nsR4nueL5ZLmA=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1pcc952wp5r5svd72s6anpqzpth2m3lzzp7t5p072dxss4jeymjwrrq8gw5c7szx0lwtazuyvnlupq5n8zv2nxhq7yzwp34pkxdvnaj2u3evlddrkyqxrje255vefhhru9jzqe9z7yja78wgw5ffvlzlqcgrrsu5n0dpaxf9ra8gzdryyht90z4w45wa03keqrgfxyfmrsz30wz7dkgrhr6us499q2pnuj6pthq48qksqmqy8tlpnfv7qr2kswqycnsdal5srludhclg80enjvth6ngmfwmp82u3thdsjghge5zs77qqzm5as39v4e6mxz8lf8g0wg3ds6gaguhj9f3hqs448c988x4hcqyfe97urr00qhverqec22flfkgkgngs8awpkwjeez93mp0zuk7agmygmdrcy8z9zsp6z27sl8f3x6tsgelg3gf8tj86pedvp0etllw3qqyw6wpdq0fggq7qcv6xw6eghzdhv0ljkwwg5v9ahdsy5ngs6673khfhqr8ae7yggk29mhqncgttx966fhfvq329edcza827tgmwvnj60x6hg4qnz4stsnfncmk6m0t00czqrpzuskvm368yth2s9gev0k7g762h6gx6709sred9qp6gr0qes9jadv3d94pynkpjhwmz449ypfy3pdqvhhn78zj92p9snqqqxavz8lzk88mcjdkeqhqvz4dgffja78pe44cukue7vxwdfstwgj24p4632fmzmnfrevst44ssr42kz064ez49mtyjvxmegrdsvadv8k635qffefl42w90f56mn5g0ww725tlay8hsuvevth0uh8vjjfaagkygr3cp3xpjuc9rwc2nyup6df4pk669f256m3ny3s53s6z6ra3sr773803z6z6f70zdqd2uxd36xtanrszj8scq882u8djntyreylvn9gppfyr4xgf67e7at542222cvyusm8jchcqzy7xpuh6v88qf59cw7j5vmmx53q2cpvdgsxeeptyp9tq4pvxshkz9c9muv6lz5ttupxss43z4er7tnsdg42kfzy2qvtfsypfk7wqupv63kg9kfp30nyqcf02v8pd5gl0dzj02eheq35u8fxy705wmu9gp9ytptetz9yrdszzxmszac90un82sgvf42g4v4jp9f4a70gkazhf5vng2pct7z99ggh46lccwgvfjxvmwfz5ff8j5jmzrhpu9nzmtvr8x8evn82gl9h6p5gkm28uhurlwtg32uh8yst3zlq9xygwu2hcm32lj0f3h0kecvvd4m59gteyjs9zpelyj90k4p0g9jrsz5y8edjrhdzanrm353xd6hymuh2qu890k97dgp3ppds56gsza50ddcxve36xr3f4ft08dxlax5589nscuagaa8v0zcntf4d5asrzu8jknr42rk2y34mu54r0cjc0quy278yf657ez2nt33cr9qy3xesvx9uc60juwteuqvttec8knag9mv3q0d3jq9dau8cp5295m4dzjzya384k36rpjgl85r5weaqk60vlymnuugzpj5tyur3sxjds7p55ndjeflhu237zuu84fdpze2csnqzf3ak8q6qz7cjxsaqjhnv5y5ysp99w35u6rxs4u0f03ks7tv9de90cv5cca6sq2pfr6mv4nw8eu52qtp93dn4hgnzfven2r3lrpwelkr3mrpwn4wcrwcqjzytcuzse54ug9hdfnxn8f6edpqy9ztjwnp9mfy2w32keapqjk8dcvjd6n6yzkk2hry55d8cww4p74sdgwrghh84hx4wg57udyul3tmzpmfue7te9wtrxpn6gu287eu42xz2h3f88genu26030ve4nwvs0xcghmflvcjpp0sk5h9476vezhvp2k3kqyjvvt57qel7y8n4f70kn5ffna4m20x3pn2uy3d5c2ywqt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-23T05:33:51Z"
  mac: ENC[AES256_GCM,data:Qn9+wM3V4+IA8CtFuomjoSxMlWYGTL/XPki5RJ9x9g0fvnPo5aMaYxW1Bdq3dc+62T+SJtCAFT6YCilOCJSQ1qYr6iDAOMdnJgQRphB/C/AB+SAlkfEJvuAQksdNPGi14CAuQz4AZDVjaFUq+kK7CR1GMMoIkfB4GCkccThKFc4=,iv:GaJw9/Indoiv7QgxLLskj+9pGKeD+upriIb1a/+4T/c=,tag:dWgYjoxBEaRPKme1pHWBwQ==,type:str]
  version: 3.13.3
