apiVersion: v1
kind: Secret
metadata:
  name: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/instance: immich
type: Opaque
stringData:
  DB_PASSWORD: ENC[AES256_GCM,data:R9gRRCMfETxHVA3roME+tPUQN4A8agmU5ZNh/9RHkSvQcQJlYE+Emt1j4BBvTrJFJvFJU4qPU/8pUmhemM09Fw==,iv:phcXI9LPgvZyi2XCenKv9A5AJfoHoSDao46jZVFLeEU=,tag:lzXLRnYrjVEtn/Xf6zjo2A==,type:str]
  DB_USERNAME: ENC[AES256_GCM,data:rNDYqTYG,iv:9wRalgkvPkMtgJAsK1Zv+pNjlf1/UflXr/gfqojRddQ=,tag:OS1DtPUz8lPxKlaZBAHxrA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEZ2SklPUWYx
        KzVQUk9JWC9OeDNHeXdMa2hCSE8zK043MHpaamw4NlJyZERIRVI0VTZoNDdYN2Zx
        dVpmQWdUVHZRR0MyRHRsUkcrZmlQMnFoWDUvY2NNbFJCbkRha0VjekR2bHlwaVRW
        VjFwemFWTzJRNHB0dmlsdmVHS0FvWHJUMDRWaTRkOUt1SFVUY0laaVA1QU02cGRa
        eC82M1JXR1Jaa1JpaGtiSmNWMEM2OUF0Q1RJMUEvR2hMSlhpUkdlWWsreVdUckRL
        U2o4Rm54Z2kraXVIbXZySEpsbHcvWWNjK1EyMURDdDFuMGN2U0M0UVNTUG03WFRJ
        bXM3SUdOWitoU053UXFrV1BNMTFOMFVmMHFubnEra1dEcHBPUHJyRXNuUGoyWndZ
        VFhqUEtDdkJ0U0NLQjlpVjdqYlc0ekdCc3Bwcy9nUXZ3dm1ON2lBajdlTC9QZmpn
        OTlBaDBuR2diNlJTZjAwNFZTbTlPN3dJcUpKbzN2Y2lsaWgzcy9jZGcrYnpVaGV3
        azZxM0ZMZkM0Q3FTdkVsdForRDRCSkVaVWhUR2xpT2l1MmhnSm04NjJJeFVsNnAy
        MXdXSGNsaTF0b3prUjVOQ2JoaHRZYmRKU2JFUFh0MFZoOFJQSkdmaEs0K2R1TWcr
        TmxUTkovNjJqSWI4N2U2UlFCVTBsUW1kNm9XMmZvYk1LdThrZ2UxcWRHZUpJekhU
        d0xUNWp2UExOM0RxSlBHU2g2YXUwMWJmTTZUV3FBVytEWldrdTlyb2JaejEyWWE2
        VWhyeCtNOHFJczEzY210azQ3MnR5SlJkeWcvSXZzSThJZnk3cGwvcWlrS3ZzR2w4
        QklMa2ZlYXN1UlVJRVR6d05wMVJBNUtBWXgwMzlWN3YvT0RXSlN1SDhDU3gyY2Zs
        QjdzTU9WbVVkKzBJZXplTlR3c3pydzUyb1l3RWJQazFQZVVjdGk2SVhFc2Z4OHJ5
        aitnMzVmNEhSNWZTZ1JZcDNhai8yT0VrdUMxOUhYSkMwUXhueW1Sbkg1amt1S2xz
        bDJVUnlNeGxzdVpMOFlRR0p5UHFHdEc2aWRqL0hsWG0rUzRNclpnNDlBa2NZbVQ1
        N3FRakJOQXc3bHBIZ3hpaFZQL09ETGFjdGNZZ2VrZ2JpU3VEYnBYUHdZcFFkMWJm
        RWsvV3AzeFRiOVMvZXVZc2hoUGUzUzVVSDM4akxhbllIeFBuUXVrQVN4UE5KTlo1
        cFRYU1BqLzNKMnd1NEcvM1BoNE9DaFNXSXZySlkwamRCOUw2R1JmM0NxOFJqd3Qr
        WE10dkoxclRFWnVkZG1IdE4yYTV4UmY4Mk5IdnAvNHFRYit6TlFyeTZqZDJ5d21x
        UWZtTzErYStzZ3pZcnhwWGd5VWpsOTJuQlJWSTFoQVppd3lqVkpLd3FIaG9OWCtp
        UmlaODJrTmUvTk1xU0RRSUFFM3o0UWZxRFpmUDhUQjRYNmx6Zks3M3I0VkNmT1Ex
        UGpoZjVpbFhONnN0VVF4Y24yN05zWHdhaW1PL1pXLzZWdlNFQVZiSnQ2T0Z6b2VG
        RzRDTldyQk0wdHozcjlMeDQwUWNnZy9vZWVhWWV6cG5qZWJta3BHb1p0S3hVK2dj
        b3Vqek14bkQyUXJRVjNBRTdyRE5WQlh4T3BBT3NxN3NRZGgvTHRIdVJjWHJWRy9k
        b1o3bW5TL1RnYkZCbzY0cThEUUw0WnFYcG96M3RrTExrNG0vaytWcHp2SW5WdmNO
        TzRJS1ExbHE2c0xNZmErRDRUMXhSQXNwL1JHVG84dTJFNDUwWm5DaUZvb2NxM2JT
        OVRxaEhrRmIyUlhqaUZEZFErQ1VzRi91M2NKZlNWOXJZa2tKSmFiaE8xeXA4b2Fz
        VFNjT3ZpQzBDTlRwZ1FIMk1SK2pBdkkxbjh5WVRaWmVFK3lJMU5RUDBZTm5teFoy
        SnU2Z0ZjQ3pQRW9GZ1BZYXJWWGhTWXh3WXZ1bEEvUzJ0SmxBSFU2Y1lwdkNidwpW
        bWExdm9SMlphbktOMmoyNU5CZTV3cDhWL1dYRElKQXVnUzh2RzZyVzdrCi0tLSBF
        eFBselJ6YmJITWhLRll6TE1RY0E0MmM3UytHR1FabHdQRXp0akhyR1lVCjM0XMxS
        wlHmORse92RY6NSxYRUfhHHFuoB+oUF3EDTUjrTp+dSeT++lR+XpvB9RWr+eV89e
        9JjBlEGVbbhkOqs=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1pcc952wp5r5svd72s6anpqzpth2m3lzzp7t5p072dxss4jeymjwrrq8gw5c7szx0lwtazuyvnlupq5n8zv2nxhq7yzwp34pkxdvnaj2u3evlddrkyqxrje255vefhhru9jzqe9z7yja78wgw5ffvlzlqcgrrsu5n0dpaxf9ra8gzdryyht90z4w45wa03keqrgfxyfmrsz30wz7dkgrhr6us499q2pnuj6pthq48qksqmqy8tlpnfv7qr2kswqycnsdal5srludhclg80enjvth6ngmfwmp82u3thdsjghge5zs77qqzm5as39v4e6mxz8lf8g0wg3ds6gaguhj9f3hqs448c988x4hcqyfe97urr00qhverqec22flfkgkgngs8awpkwjeez93mp0zuk7agmygmdrcy8z9zsp6z27sl8f3x6tsgelg3gf8tj86pedvp0etllw3qqyw6wpdq0fggq7qcv6xw6eghzdhv0ljkwwg5v9ahdsy5ngs6673khfhqr8ae7yggk29mhqncgttx966fhfvq329edcza827tgmwvnj60x6hg4qnz4stsnfncmk6m0t00czqrpzuskvm368yth2s9gev0k7g762h6gx6709sred9qp6gr0qes9jadv3d94pynkpjhwmz449ypfy3pdqvhhn78zj92p9snqqqxavz8lzk88mcjdkeqhqvz4dgffja78pe44cukue7vxwdfstwgj24p4632fmzmnfrevst44ssr42kz064ez49mtyjvxmegrdsvadv8k635qffefl42w90f56mn5g0ww725tlay8hsuvevth0uh8vjjfaagkygr3cp3xpjuc9rwc2nyup6df4pk669f256m3ny3s53s6z6ra3sr773803z6z6f70zdqd2uxd36xtanrszj8scq882u8djntyreylvn9gppfyr4xgf67e7at542222cvyusm8jchcqzy7xpuh6v88qf59cw7j5vmmx53q2cpvdgsxeeptyp9tq4pvxshkz9c9muv6lz5ttupxss43z4er7tnsdg42kfzy2qvtfsypfk7wqupv63kg9kfp30nyqcf02v8pd5gl0dzj02eheq35u8fxy705wmu9gp9ytptetz9yrdszzxmszac90un82sgvf42g4v4jp9f4a70gkazhf5vng2pct7z99ggh46lccwgvfjxvmwfz5ff8j5jmzrhpu9nzmtvr8x8evn82gl9h6p5gkm28uhurlwtg32uh8yst3zlq9xygwu2hcm32lj0f3h0kecvvd4m59gteyjs9zpelyj90k4p0g9jrsz5y8edjrhdzanrm353xd6hymuh2qu890k97dgp3ppds56gsza50ddcxve36xr3f4ft08dxlax5589nscuagaa8v0zcntf4d5asrzu8jknr42rk2y34mu54r0cjc0quy278yf657ez2nt33cr9qy3xesvx9uc60juwteuqvttec8knag9mv3q0d3jq9dau8cp5295m4dzjzya384k36rpjgl85r5weaqk60vlymnuugzpj5tyur3sxjds7p55ndjeflhu237zuu84fdpze2csnqzf3ak8q6qz7cjxsaqjhnv5y5ysp99w35u6rxs4u0f03ks7tv9de90cv5cca6sq2pfr6mv4nw8eu52qtp93dn4hgnzfven2r3lrpwelkr3mrpwn4wcrwcqjzytcuzse54ug9hdfnxn8f6edpqy9ztjwnp9mfy2w32keapqjk8dcvjd6n6yzkk2hry55d8cww4p74sdgwrghh84hx4wg57udyul3tmzpmfue7te9wtrxpn6gu287eu42xz2h3f88genu26030ve4nwvs0xcghmflvcjpp0sk5h9476vezhvp2k3kqyjvvt57qel7y8n4f70kn5ffna4m20x3pn2uy3d5c2ywqt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-22T15:14:29Z"
  mac: ENC[AES256_GCM,data:0b4zI1dYMS/VBEhdd9vJjmfTLiWE8zGvEUPiC7sC1l2svh7t/C+/CMXcYwi9is52f0M5Y+Ulkqllp5ksfWd4DNCNshQB8DEC9gYTWawXGPADSX1xx7JHdFNkSP+lAMuFb1rNmG7hQblB2cPIvmTWkUwIYRo+kDAAeE1HVG0IcTU=,iv:WYdCp4qXCoZ+Nk8z1hVAYd62S0zslFPf+PzZ7gxfXV8=,tag:Dtl5ZurCXlTPiL87KlrdKw==,type:str]
  version: 3.13.3
