apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresql
spec:
  inheritedMetadata:
    annotations:
      prometheus.io/path: /metrics
      prometheus.io/port: "9187"
      prometheus.io/scrape: "true"
  instances: 1
  storage:
    size: 10Gi
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-standard-trixie@sha256:f0cc49632b5cc1e51f65ba03658c89bd31d64ea2672b14843a808a8d281417e1
  postgresql:
    shared_preload_libraries:
      - vchord.so
    extensions:
      - name: vchord
        image:
          reference: ghcr.io/tensorchord/vchord-scratch:pg18-v1.1.1
        dynamic_library_path:
          - /usr/lib/postgresql/18/lib
        extension_control_path:
          - /usr/share/postgresql/18/
  resources:
    limits:
      cpu: 1500m
      memory: 3Gi
    requests:
      cpu: 100m
      memory: 1Gi
