apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgresql
resources:
  - cluster.yaml
images:
  - name: ghcr.io/cloudnative-pg/postgresql
    newTag: 18.4-standard-trixie
    digest: sha256:f0cc49632b5cc1e51f65ba03658c89bd31d64ea2672b14843a808a8d281417e1
  - name: ghcr.io/tensorchord/vchord-scratch
    newTag: pg18-v1.1.1
    digest: sha256:bdea43bed2a414e21bbf71767bf6f0739747ac480b267b51772dc214ac28dcb3
labels:
  - pairs:
      app.kubernetes.io/version: 18.4-standard-trixie
configurations:
  - images.yaml
