apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: garage
resources:
  - configmap.yaml
  - customresourcedefinition.yaml
  - role.yaml
  - rolebinding.yaml
  - secret.yaml
  - service-headless.yaml
  - service.yaml
  - serviceaccount.yaml
  - statefulset.yaml
images:
  - name: docker.io/dxflrs/garage
    newTag: v2.3.0
    digest: sha256:866bd13ed2038ba7e7190e840482bc27234c4afaf77be8cfa439ae088c1e4690
labels:
  - pairs:
      app.kubernetes.io/part-of: garage
      app.kubernetes.io/version: v2.3.0
