apiVersion: v1
kind: Service
metadata:
  name: garage
  labels:
    app.kubernetes.io/name: garage
    app.kubernetes.io/instance: garage
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app.kubernetes.io/name: garage
    app.kubernetes.io/instance: garage
  ports:
    - name: s3-api
      protocol: TCP
      port: 3900
      targetPort: s3-api
    - name: s3-web
      protocol: TCP
      port: 3902
      targetPort: s3-web
    - name: admin
      protocol: TCP
      port: 3903
      targetPort: admin
