apiVersion: v1
kind: Service
metadata:
  name: garage-headless
  labels:
    app.kubernetes.io/name: garage
    app.kubernetes.io/instance: garage
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: garage
    app.kubernetes.io/instance: garage
  ports:
    - name: s3-api
      protocol: TCP
      port: 3900
      targetPort: 3900
    - name: rpc
      protocol: TCP
      port: 3901
      targetPort: 3901
    - name: s3-web
      protocol: TCP
      port: 3902
      targetPort: 3902
