apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  labels:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/instance: valkey
    app.kubernetes.io/component: valkey
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: valkey
      app.kubernetes.io/instance: valkey
      app.kubernetes.io/component: valkey
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: valkey
        app.kubernetes.io/instance: valkey
        app.kubernetes.io/component: valkey
    spec:
      serviceAccountName: valkey
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 999
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: server
          image: docker.io/valkey/valkey
          args:
            - --maxmemory
            - 50mb
            - --maxmemory-policy
            - allkeys-lru
          env:
            - name: VALKEY_LOG_LEVEL
              value: notice
          ports:
            - name: valkey
              containerPort: 6379
              protocol: TCP
          volumeMounts:
            - name: persistent
              mountPath: /data
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          startupProbe:
            exec:
              command:
                - valkey-cli
                - ping
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 10
            failureThreshold: 15
          livenessProbe:
            exec:
              command:
                - valkey-cli
                - ping
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - valkey-cli
                - ping
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 3
      volumes:
        - name: persistent
          persistentVolumeClaim:
            claimName: valkey
