apiVersion: v1
kind: Secret
metadata:
  name: lldap
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/component: database
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  password: ENC[AES256_GCM,data:zEeBE/rfR13fIi2fEs/SmFDRlAEFp+7SNW0Vmm4ynxVbkKyqLpRSiUsWHSS3Bx0fX1MX4A37i+F1WmXOm7bJrg==,iv:NYXNN9dhCxUfTkhtrqBRlnIVfCmeGl9xs8mqQPV6mbw=,tag:cmhalLDMqouAUS4LZO3+Kw==,type:str]
  username: ENC[AES256_GCM,data:vCaOdak=,iv:WodjIl4Td3+BuaOJFcOWwGWjJfzj7VL+qJnI6CiXfMY=,tag:7AuD7vBgTXr2H7Q7+KTFaw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IG9KN2daWUF1
        L2thdXQzTEJpRVlmVUdhanh0cUkvQ2l0TVJMOEg3QllSeUNWakxqK2ZtQUJJM0FH
        OWFyS2ZPU2pjaDNXeW45VURqeE5xc0tpV2EvQWM2aTl2d1U2MW40WWovTGZWbUtL
        VVNlSXNheENRZXEvcThmNVFmeXBXeURXd0NLK1Vvc25yU3VlK0RpSUR3ejdMQUNn
        dE5FUk5GNCszZ2drcExVbk03WVlKYncrOGpmajBJcHF1NlBhM1NLOGVPUUpoeFRS
        QllaUTB3TGh0d2VyaSt6aGRHUmovaDY5aE5WQU5XM20yN1ZvSTIzUzVqbUJIeGRh
        TXoydFFNbFB6M05HVFZQNXNsSXVlNlVhRzkrKzdqUFNKWDF2eXJqMUJZQ3JxdEhG
        SGV3UHl5em5OWVo3UGNNZ1ZLRnc1R1VhREZNK2VkOWNBeUVkSlFtbjB1SFpKTTJi
        MzVEUVdUZE1VVWh5N0IxRTE0ZVBzc0dQVlVBTXgyNC9aS1VrZ0NhMmEwVGhXRTd4
        Z2VaaFM0Mm9WcmVYNUJ5cUl1Q1VOczZhSDFnNG01WHpXVjJxNVVZc09FNWtpTW1G
        UTAxVXp2MDVlN1NMRC8rRUFQUGNrbGJ2ekxSZXlkMVZxaEZSQ0lMbE9NNUFhekdX
        WGNyLytxeWR2Yzh1b2sxNUJJOU51QTB0MlFLck9PQTdleEdLNWYxRm9YNmZIb1A1
        ZjBpZWVDcms3R3c2aXcvQTR2STlaQ000SUROVUxJcWpTMDRvV1Q4bzYwYVluYTY2
        c2EwRGJVS3cyTTFHOEgvVmIrYW1RaWJtVjRCUVA4b2RHaXB3ckdRYUVBUEJVVC81
        THNYY09qZVZoSDB3TTZBNzZJTU0rT3lSV1Q5YnRZWEhueEJDa2dScGkvSHN1TDVY
        dFdNZ2ZFaEtIUmxIczdGamovSVF4VGdBNGIvaU1HSHhBVXFWdkYxVHByd2pTVmhk
        UmVWMVFHTmtINVFsTEF3ZU5oSkxoVTJoWUQ0Ykx2MHBNTXY2STMzU001alVxZmFR
        c21NSW8yS0ZhRVEyOFludVo3RGg4eGFGTmdBNUNlaGRnYUQ0TXpEMlZORnlIYnpt
        dHVMQWVDS0xzUExxeUR6ZGorak1KVUdYd2hwR3BqSjgzSlQ4NnIzd2Jqb1FtM2VZ
        S0JTclhuVzNibVFlSll3alBwME1KTnM0ejlpNXd6RFV6bnBHYUNyaWRIV1MzWUVD
        bFVQVnlBKytRKzZSWEgvQ3ZUUzhqM0ptTzBiMlVncUhLOUVRSmRzWnJUOUFKYkF1
        WkRxaEVQZDVmZ090Ynh0WEk4N0FHd2FrZWlPRysrQ1B2OTd6MDZjVTNGQUp1SU9q
        SGNwK3FhYUtaR1lBMFRYQzlyVlhWSnNNY1pxUjBNTHkyemxRcE9uckZ0RVkyVmZT
        eFhUYy9hdVBuN2JWS3NtWExkVzE2Y1gvMDRLZzFmVTNWamhXaFF2TTZBRTBhTWRt
        U2dDT2ZTbWQ4dlF3Z2laaExxZ0ZJNnR1WUZmaWtkWms5R0ZSbFZXMDdFTFRZN0VB
        bGdUMmxtZERwcVE1NWpDV1hGQUJsUkNia0FxSDZqTEtJbXJPdC83REVvdytxTzB1
        encwVGJZQk54T1BVUWtDRFg2WVYxTTYyUTZnTGdLN21UMnZHMEUzYUJJRlA5alpu
        OGRERURHMmR5OWx6Tyt0OEliV21nWVVWVlg2N05SRXhmSGNLRWZjaVhiblFMZi9D
        TFk5U0hvZE1CeFd4YUZ5SkZZRk1DQ0pSK3o2MGhiL1ErVHR3cTYyak80WjVsanNT
        RkFXZ0lqdklnMFBiZmxwNC9uZ3ErcHhKWW5abzY1aGFHSjQ2TzhEOGVqaVk5Rnh2
        aUgwQ2NZSzFWQ1Q2Q2w0WDhKY1JqdnpGNUQ3VFErQU42dUxpRFdJZEROZEV5cGxv
        ZDZDZllRRmlRUzlpQ2ZqSDZ5S0ZLTEJkeHlybWlQREs3OHlHdnl5U21hU2pIQQpw
        VjRiRlFwLzV2ZXcvamdyQ0NlWXJMY3dtalFzaWFFdXIvb3NkYVdxZk93Ci0tLSA2
        aGRXZ0lCU3R2M283Zmphb25MY2lXTE1xZWR3WGRRYjk1d1B4UHY2T29NCvA72z/v
        j7W0vn9+sQxBD7EMFAdjvmXtnLb665WaMZNiO/sUgrY3HsJgQobQoi2lcnExw+Ff
        y3/g0D/2J+RBOkk=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1pcc952wp5r5svd72s6anpqzpth2m3lzzp7t5p072dxss4jeymjwrrq8gw5c7szx0lwtazuyvnlupq5n8zv2nxhq7yzwp34pkxdvnaj2u3evlddrkyqxrje255vefhhru9jzqe9z7yja78wgw5ffvlzlqcgrrsu5n0dpaxf9ra8gzdryyht90z4w45wa03keqrgfxyfmrsz30wz7dkgrhr6us499q2pnuj6pthq48qksqmqy8tlpnfv7qr2kswqycnsdal5srludhclg80enjvth6ngmfwmp82u3thdsjghge5zs77qqzm5as39v4e6mxz8lf8g0wg3ds6gaguhj9f3hqs448c988x4hcqyfe97urr00qhverqec22flfkgkgngs8awpkwjeez93mp0zuk7agmygmdrcy8z9zsp6z27sl8f3x6tsgelg3gf8tj86pedvp0etllw3qqyw6wpdq0fggq7qcv6xw6eghzdhv0ljkwwg5v9ahdsy5ngs6673khfhqr8ae7yggk29mhqncgttx966fhfvq329edcza827tgmwvnj60x6hg4qnz4stsnfncmk6m0t00czqrpzuskvm368yth2s9gev0k7g762h6gx6709sred9qp6gr0qes9jadv3d94pynkpjhwmz449ypfy3pdqvhhn78zj92p9snqqqxavz8lzk88mcjdkeqhqvz4dgffja78pe44cukue7vxwdfstwgj24p4632fmzmnfrevst44ssr42kz064ez49mtyjvxmegrdsvadv8k635qffefl42w90f56mn5g0ww725tlay8hsuvevth0uh8vjjfaagkygr3cp3xpjuc9rwc2nyup6df4pk669f256m3ny3s53s6z6ra3sr773803z6z6f70zdqd2uxd36xtanrszj8scq882u8djntyreylvn9gppfyr4xgf67e7at542222cvyusm8jchcqzy7xpuh6v88qf59cw7j5vmmx53q2cpvdgsxeeptyp9tq4pvxshkz9c9muv6lz5ttupxss43z4er7tnsdg42kfzy2qvtfsypfk7wqupv63kg9kfp30nyqcf02v8pd5gl0dzj02eheq35u8fxy705wmu9gp9ytptetz9yrdszzxmszac90un82sgvf42g4v4jp9f4a70gkazhf5vng2pct7z99ggh46lccwgvfjxvmwfz5ff8j5jmzrhpu9nzmtvr8x8evn82gl9h6p5gkm28uhurlwtg32uh8yst3zlq9xygwu2hcm32lj0f3h0kecvvd4m59gteyjs9zpelyj90k4p0g9jrsz5y8edjrhdzanrm353xd6hymuh2qu890k97dgp3ppds56gsza50ddcxve36xr3f4ft08dxlax5589nscuagaa8v0zcntf4d5asrzu8jknr42rk2y34mu54r0cjc0quy278yf657ez2nt33cr9qy3xesvx9uc60juwteuqvttec8knag9mv3q0d3jq9dau8cp5295m4dzjzya384k36rpjgl85r5weaqk60vlymnuugzpj5tyur3sxjds7p55ndjeflhu237zuu84fdpze2csnqzf3ak8q6qz7cjxsaqjhnv5y5ysp99w35u6rxs4u0f03ks7tv9de90cv5cca6sq2pfr6mv4nw8eu52qtp93dn4hgnzfven2r3lrpwelkr3mrpwn4wcrwcqjzytcuzse54ug9hdfnxn8f6edpqy9ztjwnp9mfy2w32keapqjk8dcvjd6n6yzkk2hry55d8cww4p74sdgwrghh84hx4wg57udyul3tmzpmfue7te9wtrxpn6gu287eu42xz2h3f88genu26030ve4nwvs0xcghmflvcjpp0sk5h9476vezhvp2k3kqyjvvt57qel7y8n4f70kn5ffna4m20x3pn2uy3d5c2ywqt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-22T15:14:29Z"
  mac: ENC[AES256_GCM,data:LOO3UfWEZb5piGmMKRccxFuNvTRIBqKu093C509OmKLsh8s9xJVC+dJ0961DOruAOx36TdxcX6P+2AnzeCYVUgZ5/4wqVzv3Rsly5SpKqmxrcfqllh7ueQyrys1+K8utwGmI3LolwcGYDDTJzWgz0kA/NAAQfBHom+4Fi3FuuiU=,iv:PSqe4nGqccbZE1gn1YApMioqFlpstUF6ioW7pYAPoA0=,tag:gtplUSjO3ZL4JE7WGHcLXw==,type:str]
  version: 3.13.3
