apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authelia
resources:
  - deployment.yaml
  - httproute.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml
configMapGenerator:
  - name: authelia-config
    files:
      - configuration.yaml
images:
  - name: ghcr.io/authelia/authelia
    newTag: 4.39.21
    digest: sha256:b2a221b30da111d6717bdf81bdf0b180915921447dde4c533a796c9a33a75d72
labels:
  - pairs:
      app.kubernetes.io/part-of: authelia
      app.kubernetes.io/version: 4.39.21
