apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authelia
resources:
  - deployment.yaml
  - httproute.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml
configMapGenerator:
  - name: authelia-config
    files:
      - configuration.yaml
images:
  - name: ghcr.io/authelia/authelia
    newTag: 4.39.22
    digest: sha256:936134132eaf01bfa2faf85055afbc1e0cc1cc5ca4547e9c06408fd0dd784646
labels:
  - pairs:
      app.kubernetes.io/part-of: authelia
      app.kubernetes.io/version: 4.39.22
