apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: headscale
  labels:
    app.kubernetes.io/name: headscale
    app.kubernetes.io/instance: headscale
spec:
  secretName: headscale-certs
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
    size: 256
  duration: 2160h
  renewBefore: 720h
  dnsNames:
    - connect.guedescloud.com.br
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
