apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: headscale
resources:
  - certificate.yaml
  - deployment.yaml
  - namespace.yaml
  - persistentvolumeclaim.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml
  - tlsroute.yaml
configMapGenerator:
  - files:
      - config.yaml
    name: headscale-config
images:
  - digest: sha256:0e7f1c6e4ce6c2a2a001103ecd3fa645a045adf30ac8a5234fe037b43000cd72
    name: docker.io/headscale/headscale
    newTag: v0.29.3
labels:
  - pairs:
      app.kubernetes.io/part-of: headscale
      app.kubernetes.io/version: v0.29.3
