apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: headscale
  labels:
    app.kubernetes.io/name: headscale
    app.kubernetes.io/instance: headscale
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
