apiVersion: v1
kind: Secret
metadata:
  name: soju
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/component: database
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  password: ENC[AES256_GCM,data:yWC4kU4XHFgU6kKvlT6nN+cmZqwNEytgdwtXdmKCYRGuvZi2xP/aQc2AyW+TD14HNag8dwb352ZSQCy22RxbZQ==,iv:Y2qGk4v5C+zsPwnzrRRPmHjNFasGbzCFPKCAjUsocpA=,tag:OweIldcX0+HcKyLo1n/0cg==,type:str]
  username: ENC[AES256_GCM,data:6KU+cQ==,iv:Ky0sWjYmJcsAPXsXFErsbqb5c2qx5D2mZXnXU5Hua98=,tag:Z7k8jg2Pcbz44G6VpUNoIw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEZRUHFJUFcz
        T3NhOEtFWG56dkgra2x5TnBDWXFOcWxNZHBjZUxmbXFEL09BS1QrcldJRVlucExK
        bzhRWUJ6UHJCMWFyZml2V2l4ckEwdUlZUmorcVpCNDE2bFBSa0xHSkE0QlMxWk9x
        V2l4UWp5eXhBOU9vQURsOXlYcGg2RTdOMlUxYm1NakxpS0NZT0tQZDBuVFI1WU9J
        UHFjZ2cyMWQ4OE5KZnNQZFlYclZ3emNTdVpXNWRVYzlNZ1dZWUtLa2wxUkdzUVVB
        OHE3Y3J4NmZWZXFxelpFTkRvTFNwOWlRMU96REhseW5DaDFKUjNEVEtFSkhIUWhm
        SFNYNzJrODZsUk9iQVIxVjBxMk11TzR5ZEJFV0JKNFBmeXR1dzVJVWIvZ2kyLzFx
        RjUvK1BxV1hpZW1WTGNQY0NFZ1kzWk05ZmRYd25MWGIxNVg5MHlMMEIvcHk0SUpX
        eTZRWWdPQndoYXhSbjY2N0hrNWQwQVc2amk0TFJXWkk3eERWTnd5MlpVZklhOEtP
        Nk9JNDlab256R2dsNHFmajdDbngwb01qTXU4dHYzYURzaUwzRVJTWTIzMmFzNVdl
        TGdjQ1UzRHF6aXJjcVVHMWxWUXg3QXdEZlB4ZHR6MitXeHFrY2VhRU5Oa2dRS1Qz
        VERpeXVpSWFWK2NraFN5SDRyejNvWnZMWktpQzBKREs5QXRKR0dCUkxRMU9WQXk4
        TXJCSTRYOFdZeXVlSncxSGV3S0dVR2sxc05rcFI0Qi85YXM0WDlrS1crMWdUbmMw
        bkNBRVdDMzh3bGVIQXk2UkI4N0ZqUTNjMmI4cDRXbllkUEFRNDcybWVBWFRiTWt1
        MTF4K2dsb2tzWkdDdkpoUmJOMWM0bXZYSW02YUdPMWQ1T1NDMVdwaEErQU4wNkdw
        eTZQcXpMSWR3ZGdyZG16Y0VRcjdqMXJ4cksxQ0ZlNFpsUTkwOTlBRE1oMG01WWdH
        YlJlYUFyM3AzTzdMTnpzZjZJNWZHdWRwVHVMT0lrRjV5SUduSFl2MXFiWStoQ3c5
        TkpsZFhtME45L2pnWmc5VVMwY2dnN2gwanloMUUxYVlINGNvczViNFZlVG8za2lx
        UVkvcUVRNEZENG1OMjhSa1lTVFZiTGIrK1NMSGlxWkoxa1ZDK2pIamxJNTh5TXVn
        ZlQ4dTNBQVJDY0J1UEc0RGUvL3RJRTB1VTFaVnFVTXdpc0JxMmxxcENESVM3MzJH
        bHE4MDlNcDNwZzFRZnJsWWtSMzhIQm1pSjJPN1ViM0gzTVl2bXU3UDVwNVdqSXl1
        NjFETXpjalRXU0JFTVZmQ0hVVTJ5L3JNb2t3VERuRHlKcXpJVkdwcmxwa2ZFU0dN
        TFVhVlJYZFNDMG5sMWVTL1F5WkRlSlZFYUYyUEVYMjZ4ejdkMkt1NU5DelNEcy82
        OXMrUFJNTEh3djRsQzZEVHAzTVNGZEJrMnBhS0s4R0IxOCtuTlhTSkFXS29ZQk01
        VzVHeXEzUThPc1RFSldJZlRXODl4T1NpcnJtRzJKYUF4SkN6cm5xZTJJczFwaEds
        THhqcGRiYnZ4SGU5QjdsUk5TOXdYRElxZ2lBc3lRdzdIU0lxcjJHTFlYZGNFM0RC
        eEtBVTVkZFpiaXZsTmJNQ2Rja3pZbWV1Q3NRZlp0bktFUDRleGpOZWh3U1ptNEQr
        eTZQMVkvY3FodlpIRklENWYrTUJHUWdITkxlUit3S21SUS9JdlNBV0ZqSW1Bd3JK
        NmVVVDhhMWV6WjRxa0N3MHRQTjVNRHdJTVh6MDR5dk1zWFhvOGo2Z01BcVRVcU5q
        RnZlQ1d2NVpTYUtsT1lUdlk2MFhZQVVpMXExY2ZxYWh0UWZiVDh5SnB4NEFYNExU
        TmZjeVQ0czlQVy9xT3d5ektBeTdVa1Jac2RXRmkzb0tUbFBlMHFFUFpmYWEvSjFS
        QzRGQUNuY0FPZHBrdlpYMjhYUFprbFBpeVNHU0pqbnExNUhLL3kvd1RpdkJOQQpj
        MmZ6NXJlb1ZlQ09GVHM2ZW9mQ1RzczVlbXRmM2VzVFFWaHVYWE9idUpvCi0tLSBH
        Rmp3Ky9HdXJrcXVUcnlTOC8xOVQzbjFXUnNsb1JTMnI2d05Hc1hDaWo4CpwaldEs
        JAx02RQD6GVn2bLOMX0U8Eo+Da5JIw0khNAYvn63HIz6wFZIwaCU8PWAqb6aSeEz
        +Q9kGbmPhXhbc8c=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1pcc952wp5r5svd72s6anpqzpth2m3lzzp7t5p072dxss4jeymjwrrq8gw5c7szx0lwtazuyvnlupq5n8zv2nxhq7yzwp34pkxdvnaj2u3evlddrkyqxrje255vefhhru9jzqe9z7yja78wgw5ffvlzlqcgrrsu5n0dpaxf9ra8gzdryyht90z4w45wa03keqrgfxyfmrsz30wz7dkgrhr6us499q2pnuj6pthq48qksqmqy8tlpnfv7qr2kswqycnsdal5srludhclg80enjvth6ngmfwmp82u3thdsjghge5zs77qqzm5as39v4e6mxz8lf8g0wg3ds6gaguhj9f3hqs448c988x4hcqyfe97urr00qhverqec22flfkgkgngs8awpkwjeez93mp0zuk7agmygmdrcy8z9zsp6z27sl8f3x6tsgelg3gf8tj86pedvp0etllw3qqyw6wpdq0fggq7qcv6xw6eghzdhv0ljkwwg5v9ahdsy5ngs6673khfhqr8ae7yggk29mhqncgttx966fhfvq329edcza827tgmwvnj60x6hg4qnz4stsnfncmk6m0t00czqrpzuskvm368yth2s9gev0k7g762h6gx6709sred9qp6gr0qes9jadv3d94pynkpjhwmz449ypfy3pdqvhhn78zj92p9snqqqxavz8lzk88mcjdkeqhqvz4dgffja78pe44cukue7vxwdfstwgj24p4632fmzmnfrevst44ssr42kz064ez49mtyjvxmegrdsvadv8k635qffefl42w90f56mn5g0ww725tlay8hsuvevth0uh8vjjfaagkygr3cp3xpjuc9rwc2nyup6df4pk669f256m3ny3s53s6z6ra3sr773803z6z6f70zdqd2uxd36xtanrszj8scq882u8djntyreylvn9gppfyr4xgf67e7at542222cvyusm8jchcqzy7xpuh6v88qf59cw7j5vmmx53q2cpvdgsxeeptyp9tq4pvxshkz9c9muv6lz5ttupxss43z4er7tnsdg42kfzy2qvtfsypfk7wqupv63kg9kfp30nyqcf02v8pd5gl0dzj02eheq35u8fxy705wmu9gp9ytptetz9yrdszzxmszac90un82sgvf42g4v4jp9f4a70gkazhf5vng2pct7z99ggh46lccwgvfjxvmwfz5ff8j5jmzrhpu9nzmtvr8x8evn82gl9h6p5gkm28uhurlwtg32uh8yst3zlq9xygwu2hcm32lj0f3h0kecvvd4m59gteyjs9zpelyj90k4p0g9jrsz5y8edjrhdzanrm353xd6hymuh2qu890k97dgp3ppds56gsza50ddcxve36xr3f4ft08dxlax5589nscuagaa8v0zcntf4d5asrzu8jknr42rk2y34mu54r0cjc0quy278yf657ez2nt33cr9qy3xesvx9uc60juwteuqvttec8knag9mv3q0d3jq9dau8cp5295m4dzjzya384k36rpjgl85r5weaqk60vlymnuugzpj5tyur3sxjds7p55ndjeflhu237zuu84fdpze2csnqzf3ak8q6qz7cjxsaqjhnv5y5ysp99w35u6rxs4u0f03ks7tv9de90cv5cca6sq2pfr6mv4nw8eu52qtp93dn4hgnzfven2r3lrpwelkr3mrpwn4wcrwcqjzytcuzse54ug9hdfnxn8f6edpqy9ztjwnp9mfy2w32keapqjk8dcvjd6n6yzkk2hry55d8cww4p74sdgwrghh84hx4wg57udyul3tmzpmfue7te9wtrxpn6gu287eu42xz2h3f88genu26030ve4nwvs0xcghmflvcjpp0sk5h9476vezhvp2k3kqyjvvt57qel7y8n4f70kn5ffna4m20x3pn2uy3d5c2ywqt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-23T07:39:35Z"
  mac: ENC[AES256_GCM,data:AlA3+gSa5A2gLPcFhE3B09cVv/CpJ9ODtgyKTSV8DiXmmdqTyKLo0ZN2xaEt6ovjIc0scxtOwH/hPY3GYYgf6swMPsnoqcagg5EdilLAXCoJrNcf1LNdeIw3tBPyKiGEx4veLCEYBxWmHPIlHN6lCqcCzPc7nctQ62zyZem2kwU=,iv:8wO9FtclcRErsdB6VH9dfkZYoRK6Rp4DhBj9Uuq1MX8=,tag:llllLaFsyr7qGHZ2tIXvTg==,type:str]
  version: 3.13.3
