apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: ntfy-db-auth
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/component: database
spec:
  cluster:
    name: postgresql
  name: ntfy
  login: true
  passwordSecret:
    name: ntfy-db-auth
  databaseRoleReclaimPolicy: delete
