apiVersion: v1
kind: Secret
metadata:
  name: ntfy-db-auth
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/component: database
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  password: ENC[AES256_GCM,data:gTtD3Z1//m8TXaTIjACBBOKRKPYxvhJeJa5UsiT3/l406khhziNCikthPiOuuYWVquTnXm8TaRKoH+AyqVbY/w==,iv:gdU1W9886HSvNnah/JV+wdfRVK3CGXBhpTyka9H4sbw=,tag:CH43RXlhYjHjgQ2DdL4fuA==,type:str]
  username: ENC[AES256_GCM,data:BFQ4EfO/7dqOTkEp,iv:cPOJ+LOq89bWgBWZnJUzk6oj/4LBKXFYM842Smy8Xvc=,tag:SfRxbVvJBEg23kbme4zP+w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDlYUzVUakly
        bHhQTmhyWDRBdU14ODZXUXB0cENCNkxjYlNwbXVpcEdsZktOeFlQY2R0cHpaUUdS
        ZEhYbVBvZGJhK1ZvSEYxMHBha0FUVUQyYlllOW1mdjJ4Z2JSN3N3YnY3L0tGV1BK
        ZmxJdXBFWnBybk15Qk94Z3dOS0JZcUtHcEltMWdlUVlCc1hqSGNZb2svK3hNdE12
        b0VkWURLQnN1Rm8rcEQzQ1ptajI5dmJNcXEwOFBzSEkyMkI0a1hreVJVUy80STBX
        K1NOQmF5UW1jUFdhVzBvY1FhclBXZnAzazlWbC9XTnV2dkNTR3ZBQWJxdjRsWENG
        YmhvUXJCYm1PWjVmdyt3RHpiNGFHS0FNYndsekQrVXhOK0J4SlBMaFAzYVBqY3RY
        aTJtbk1GYUwrQ3d0WndVZlFGbjZxSEpBdkxlbnBCNUdBSll1NFlUaWlQSjB6Zk4v
        S0VoUkZRLzVYeVZEZVhYb21xZ0daTUlCc3lka0lncjAxVldrYTlLb2tTaGJmbEdD
        SlVWWUJEamFxWm5wdEtidmI3QVZtakRnOWlmYjRsQjJqd013ejdnYTg1Wmx1cWl6
        aEdrM2hPR2YxUlNGZGJCWnFwYmtxdXJjaHg5Qnp6eWZlMGI3ZnV2V21DUUZ0aHhu
        ZVk4SzUxa0ZxRnhBdGtNQzlGWVVTbjhFQ3N0RHlXQzcxTkVuZzFyL2xBNnh5aGlS
        ajlqRi9rTTFRQmZXYVN3cEsxWWxHbFArbTdvclh5bmh0YStya2RrWFZidk50ekIy
        N3RTZVdWV3krYlhuRUxQd3hwTjF4SE5leWVYeDVXVmlKaXJLL2hqS08zMCtJVUJX
        ZlcvaWhDcUozMkw4SWhvSVZ0a1psRU9EOVFkM1BVMHNQYXBuczl0aGN0MnJtbWVr
        TlVGbEtTN0MxdWNPT3RQR1FVVSt6MTJ4ODFpTWFlS3NNQlZQM1dBZmpKMFozYnVR
        cHFVRjZ4RnJxS1A2aFlZUlRuRUNkRkRVOG5wQThleGJVUy84SnVnZExSTndWaTZ2
        M1pXZUMvRkxGcGpXOHk5dnl3WTBjbjlYeW8xWFR6RU5ldUFtdzVHUDY3SHh6Mi84
        cmlXUE16bS81VTB6dTVRRUJrNVQ3N0ErcW1HRFd5R21LaFRYZmo5RHplc2wrd0RW
        RkFDL1Mwak9VUDFTa3gxL3paMTc5alJKcHYzWjVieGRzWEdQQkpEaHNmN3pVNXJ3
        K1gwdkp5cnJ1OVpYZkNSM2hJT3NVTGx3RmZDRUh0MFUxLzI5V0FDZm1MU2c1aXgr
        dURXUTJ6NjhZa1M4L05jdDlYb20rSnlOaEZPblBqZjdNZEcxWmlBRGR4TWpyaEQw
        eFFXMHQ0a0xmQ2ZueFFSYzVzT3k3WUlZOWUzRndxZDg1dXNodlNwWkZWUTV0QStM
        TmEwUERmUGV3OW53K1Y4L1NnY294U2pvT2xNTDNEdzB3Wm90Zys0RVlmSGhYMVVs
        bUxNZlV6UE4xUUEvZmxlVUtxc2RESjZhQ3lpTUFSdGprbEJEWk1FMGw1dmJGT0tx
        V1lMV3pzeU1XQVJaSzVZL25Hb1N2dHNnaWFMWlN4R0I5S1pEc3NQR0VsVHM1YUU3
        WTluMThFYTMxS3FkUEVSREF1VUorZ2RHMG1VWHZOdDJobFFtSVlDVTd5bGJPaVk1
        ZTZyOGZ3alY2OFZuNHVkblZmM0d0cFN1aXljV0ovUENHbkZYRFFVTXhyWkxjWWln
        MWRwYVJqWWNFUmt5KzJEZUNmdnhwV2Fkem1pR1lMR3F0MzNlcEpQR0E1TTJnallk
        aldyNHpmN0RjZis5MVFNTlVqVks1WHBNMG1uNlpFME1GUFdSbW12K0dmQzFxd0pY
        emhOUnNNWnY3ZzZsMnNtM3IvdXhyYjBDb0pVeG1LR0R3U3I5ZlJURlRxSk5TclpU
        MVg2WE1qY0JyZkhDUDFvL0V4ajMwbXlSRUF0WmRmRHp0enArZGorSGJtZGpQUQpx
        TXR2V1dtc01Md0FWOXFOMmlaejRUMEU3c1NEK0E4WHhKbWxONTBzdTVVCi0tLSBn
        Y1U3WVlOam1GTkFvczBWdWZNeCtCcmVaL2xVTjhQNzV6NWlrUWtFU2trCjOBkax9
        +EiRdvweEF+hApW52oKMg2TVrOee+r+hMMG0R3kGFN5hXT0luonP8Oit/fhwQQ75
        lB5g2Yg8isTKB8c=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1pcc952wp5r5svd72s6anpqzpth2m3lzzp7t5p072dxss4jeymjwrrq8gw5c7szx0lwtazuyvnlupq5n8zv2nxhq7yzwp34pkxdvnaj2u3evlddrkyqxrje255vefhhru9jzqe9z7yja78wgw5ffvlzlqcgrrsu5n0dpaxf9ra8gzdryyht90z4w45wa03keqrgfxyfmrsz30wz7dkgrhr6us499q2pnuj6pthq48qksqmqy8tlpnfv7qr2kswqycnsdal5srludhclg80enjvth6ngmfwmp82u3thdsjghge5zs77qqzm5as39v4e6mxz8lf8g0wg3ds6gaguhj9f3hqs448c988x4hcqyfe97urr00qhverqec22flfkgkgngs8awpkwjeez93mp0zuk7agmygmdrcy8z9zsp6z27sl8f3x6tsgelg3gf8tj86pedvp0etllw3qqyw6wpdq0fggq7qcv6xw6eghzdhv0ljkwwg5v9ahdsy5ngs6673khfhqr8ae7yggk29mhqncgttx966fhfvq329edcza827tgmwvnj60x6hg4qnz4stsnfncmk6m0t00czqrpzuskvm368yth2s9gev0k7g762h6gx6709sred9qp6gr0qes9jadv3d94pynkpjhwmz449ypfy3pdqvhhn78zj92p9snqqqxavz8lzk88mcjdkeqhqvz4dgffja78pe44cukue7vxwdfstwgj24p4632fmzmnfrevst44ssr42kz064ez49mtyjvxmegrdsvadv8k635qffefl42w90f56mn5g0ww725tlay8hsuvevth0uh8vjjfaagkygr3cp3xpjuc9rwc2nyup6df4pk669f256m3ny3s53s6z6ra3sr773803z6z6f70zdqd2uxd36xtanrszj8scq882u8djntyreylvn9gppfyr4xgf67e7at542222cvyusm8jchcqzy7xpuh6v88qf59cw7j5vmmx53q2cpvdgsxeeptyp9tq4pvxshkz9c9muv6lz5ttupxss43z4er7tnsdg42kfzy2qvtfsypfk7wqupv63kg9kfp30nyqcf02v8pd5gl0dzj02eheq35u8fxy705wmu9gp9ytptetz9yrdszzxmszac90un82sgvf42g4v4jp9f4a70gkazhf5vng2pct7z99ggh46lccwgvfjxvmwfz5ff8j5jmzrhpu9nzmtvr8x8evn82gl9h6p5gkm28uhurlwtg32uh8yst3zlq9xygwu2hcm32lj0f3h0kecvvd4m59gteyjs9zpelyj90k4p0g9jrsz5y8edjrhdzanrm353xd6hymuh2qu890k97dgp3ppds56gsza50ddcxve36xr3f4ft08dxlax5589nscuagaa8v0zcntf4d5asrzu8jknr42rk2y34mu54r0cjc0quy278yf657ez2nt33cr9qy3xesvx9uc60juwteuqvttec8knag9mv3q0d3jq9dau8cp5295m4dzjzya384k36rpjgl85r5weaqk60vlymnuugzpj5tyur3sxjds7p55ndjeflhu237zuu84fdpze2csnqzf3ak8q6qz7cjxsaqjhnv5y5ysp99w35u6rxs4u0f03ks7tv9de90cv5cca6sq2pfr6mv4nw8eu52qtp93dn4hgnzfven2r3lrpwelkr3mrpwn4wcrwcqjzytcuzse54ug9hdfnxn8f6edpqy9ztjwnp9mfy2w32keapqjk8dcvjd6n6yzkk2hry55d8cww4p74sdgwrghh84hx4wg57udyul3tmzpmfue7te9wtrxpn6gu287eu42xz2h3f88genu26030ve4nwvs0xcghmflvcjpp0sk5h9476vezhvp2k3kqyjvvt57qel7y8n4f70kn5ffna4m20x3pn2uy3d5c2ywqt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-22T15:14:29Z"
  mac: ENC[AES256_GCM,data:eRY5b9VniFlfe0DW+yokdKdi0wEPD1pzsBSYADzBY3ylDsvvt5CxosIWFt5++bdzeWFPhhAc2XfGjGmqsIpAD0MzBOGFlE/ClWxkdOtwUarO+cJxNZdbxEeoonnOvg63PklhO0q3yNTE4gcqcBtrny/oJucjuxzNrC2cmhrFp8I=,iv:1Q8Q1Mgi/cwGrmZGDcRAU7B/8JZXYWAQ++BLWiOzEkc=,tag:Te3c9qModncfNaXb1L3+ZA==,type:str]
  version: 3.13.3
