apiVersion: v1
kind: Secret
metadata:
  name: ntfy
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/component: database
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  password: ENC[AES256_GCM,data:2aGdcEsOaGOqb+VsloXatEMhIC7R42hxlvmQgjYaAxDPtRPvnfBMxnqhyTfcA6pa7u/xOb8icomQyMKeJXVKgg==,iv:Y/64b+vWq7iZGvxiQd5L4d/Y8sKUMkY5bZGnr6K1aNk=,tag:VjXJuNp4oS0439uRM2XBkA==,type:str]
  username: ENC[AES256_GCM,data:xGNbyQ==,iv:UbzCC8NParRkbJLEFd5R06TLQbU+zDHjqbNSFsFwhAE=,tag:ICLlECx/WMn58UPgE9czLg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFB4bEZ0Q2hD
        VURnNHlGbVB1cllWSXlWanEyT0NLMklQM2RCNlRva0tPZ1hQQ1huQlRMeG5mRTRV
        YVdhaDZuOTFTeHpJT2MyeWVsdkd1RTBFdUlvSlM0ajhPYkRlVGN0QVB1NTg0dmN6
        dkFuVmJ5Nm9YVkI3WDUxSWtaRGwvNGdWRWRhN0FJbzhkRDVMK3R3K0N4N3JzOXFz
        SXNGVHFmaGFOL1JOT3A1MlFDN3FrbWo4cmYwOWpnejJydkRkemk5KzgzdVdsWVFS
        ZE14RUJXaHhJZHphL1phSlRQajg1QWJ1MU1oQmViVXBJYnZ6V0U0S2F5T1dXaWJN
        Mld0ZXFReHFqSEluSmFrUHlLK2Zsa3QwRXFSV2pIWVZCckhCZndBNHFHNEFLR2dN
        UXZYV0UxUHB6b0RtMC9qVXFTcnk3dGRmVmpYbnlDczhvempvaWkzdWxpaU96eUMw
        RHZMeHhDUE83RGFESWdwTVViYXRtTHpsZHdsa2VGbFdCZUtDZkZVQVMxWUtnOW5H
        U216ZmJJK1BETTJXVHBjRDEwZmNPNlB4d0tIcXp4MVNUQWswVVZrcGdINEJuOVk3
        MXZBWmdLbUp4akpiaUo1a1UxQjFXSS9sc0tZQ2EvOEVtOTcvbzEyTlZkdTVwSWZn
        OFQ1QmlaVlRLc090bGhrYXBFdmdia0kvb0Vuenl0WUo2Wk9YM2ZTcmJXSys0YzF4
        a0hjN0EwREUyQUcwWlBaMmZNQUJ0UjB0alNMNzdObnE5LzZycnd0OXEvWGFPdEpm
        NjNncURJcStYZnB6Tk5iN3JDa2pWdmZPRDVFNDRNOWJwY2VuUW0xZUp4bXhIb05k
        c3JyMk5za2JhYUZJbFhCQWtjNGU3ejlFTkNRcXNsUjRQWXlDNkFOaDhSbFhJM2M5
        dzdReFhMYVBPYjIwZkdtclY2RkNiSlkwK2xKMmZINTVJSEg1SVlmazBuekZveU83
        S3Bib29WZmh4LzA0TDB3YkQxcjB3angzSUcrRGp0d0dMYUFLUDlKc29jY2hLYjUy
        OHlEa0JrdjNudzJjdVZXNlF1ZlpNdjdlS3ZzMVQrNnhuMVAzZ2R2UWZ6SFp0SkRm
        T0VuMnFvNExSRHhMMXk3My9ZbWM2bUNFQ3dKTjZJY0Y4VzlZcE50MTJrYUVWTXBV
        eVlNWDJDd3FNTjZWNjdSc1htb3lvaEhyWTFvZnUreUk5cEV4MC9QbHdwNnI2RVNq
        OXR6eGJxWTdISnhUM3YxTGo5SHVFQlNDN3dhUWdUWVRkNGRLYmtkSjE1SzBETS9P
        V09QZlVENElrZnA4LzNwZ2JINklTdWdOTlJwT0FsMC9nSHExckw0cURPbGd4anlT
        T1ByQ1hiTmNDWVU3aVlMNmFrTWJoYlJYckJNKzg2bU01c0hDYk1ZZWNyUnhXelY3
        eUNPdDVsSTM0TFV1K0dRV0VxZzduUkNZc0Z0Vi9naWFibGc2MStVc3RodXlBczh2
        SFRjQ0QzbmhLMllvejU0dzd1RXJNNHR1d3UvZGk0bUZDbnpmcGhFTFZhRlF1QU9H
        Zk16Sko3ajVsZlRYQzZBQ0M0VDJ3TjMvMzlCcEJIT283RXAvQlg2bm40MW53WHE1
        dEJHakQ1MkNZRjJPTFNYRGFNa0FiK3VtOUgzVXdPekQ2QXJQWFRYZFBGUS9uVHpz
        VlFTSkhudTNxaWFjMU9yczVHM1lqd2FPY3AwbXg5WU1RYndVdXYyNXo4WnZtVGgr
        bjJiOVdZbmdPMHQxRG45RVU5UklFUEVkelI4NE16TEFBTlJFelQrYVRIUHpnZkUv
        Y1Q0bXJvTFVRcnp6SUx1RGcwWEtzM2VFdCtESUVmNXB0YjN6MjRIbW1qOUY3T3Nz
        WHYvNTBKMTBmajV5QnBmampzNU5EQklNbE1wUDRDSjVNb2NSeXBnNXFmUy9jcWNx
        SVgwOG9VQmJJZmhvVnBKdE1Pb3dWakhtV20zYmNpU3BnN2tETUtUQk5uUlZFQQpW
        REY1bGdYUmdzU05yVlZwdittT3BlY0JURWppbmFoZm41b1dMQlBvOFVZCi0tLSAr
        a1BMRGVxeGVIZ0ZrUHcrMXo2REdFTGlPUHIvTVF5SmNyaTA3dUV3UWFFCklLhV7e
        LA+TATRxXSfxxB6wf2R6MEifxyyYML5Y7fNcO9QyfHhJWxBcTH9IAsHyDnvCkuaQ
        FF6RpAVqXHFTlgE=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1pcc952wp5r5svd72s6anpqzpth2m3lzzp7t5p072dxss4jeymjwrrq8gw5c7szx0lwtazuyvnlupq5n8zv2nxhq7yzwp34pkxdvnaj2u3evlddrkyqxrje255vefhhru9jzqe9z7yja78wgw5ffvlzlqcgrrsu5n0dpaxf9ra8gzdryyht90z4w45wa03keqrgfxyfmrsz30wz7dkgrhr6us499q2pnuj6pthq48qksqmqy8tlpnfv7qr2kswqycnsdal5srludhclg80enjvth6ngmfwmp82u3thdsjghge5zs77qqzm5as39v4e6mxz8lf8g0wg3ds6gaguhj9f3hqs448c988x4hcqyfe97urr00qhverqec22flfkgkgngs8awpkwjeez93mp0zuk7agmygmdrcy8z9zsp6z27sl8f3x6tsgelg3gf8tj86pedvp0etllw3qqyw6wpdq0fggq7qcv6xw6eghzdhv0ljkwwg5v9ahdsy5ngs6673khfhqr8ae7yggk29mhqncgttx966fhfvq329edcza827tgmwvnj60x6hg4qnz4stsnfncmk6m0t00czqrpzuskvm368yth2s9gev0k7g762h6gx6709sred9qp6gr0qes9jadv3d94pynkpjhwmz449ypfy3pdqvhhn78zj92p9snqqqxavz8lzk88mcjdkeqhqvz4dgffja78pe44cukue7vxwdfstwgj24p4632fmzmnfrevst44ssr42kz064ez49mtyjvxmegrdsvadv8k635qffefl42w90f56mn5g0ww725tlay8hsuvevth0uh8vjjfaagkygr3cp3xpjuc9rwc2nyup6df4pk669f256m3ny3s53s6z6ra3sr773803z6z6f70zdqd2uxd36xtanrszj8scq882u8djntyreylvn9gppfyr4xgf67e7at542222cvyusm8jchcqzy7xpuh6v88qf59cw7j5vmmx53q2cpvdgsxeeptyp9tq4pvxshkz9c9muv6lz5ttupxss43z4er7tnsdg42kfzy2qvtfsypfk7wqupv63kg9kfp30nyqcf02v8pd5gl0dzj02eheq35u8fxy705wmu9gp9ytptetz9yrdszzxmszac90un82sgvf42g4v4jp9f4a70gkazhf5vng2pct7z99ggh46lccwgvfjxvmwfz5ff8j5jmzrhpu9nzmtvr8x8evn82gl9h6p5gkm28uhurlwtg32uh8yst3zlq9xygwu2hcm32lj0f3h0kecvvd4m59gteyjs9zpelyj90k4p0g9jrsz5y8edjrhdzanrm353xd6hymuh2qu890k97dgp3ppds56gsza50ddcxve36xr3f4ft08dxlax5589nscuagaa8v0zcntf4d5asrzu8jknr42rk2y34mu54r0cjc0quy278yf657ez2nt33cr9qy3xesvx9uc60juwteuqvttec8knag9mv3q0d3jq9dau8cp5295m4dzjzya384k36rpjgl85r5weaqk60vlymnuugzpj5tyur3sxjds7p55ndjeflhu237zuu84fdpze2csnqzf3ak8q6qz7cjxsaqjhnv5y5ysp99w35u6rxs4u0f03ks7tv9de90cv5cca6sq2pfr6mv4nw8eu52qtp93dn4hgnzfven2r3lrpwelkr3mrpwn4wcrwcqjzytcuzse54ug9hdfnxn8f6edpqy9ztjwnp9mfy2w32keapqjk8dcvjd6n6yzkk2hry55d8cww4p74sdgwrghh84hx4wg57udyul3tmzpmfue7te9wtrxpn6gu287eu42xz2h3f88genu26030ve4nwvs0xcghmflvcjpp0sk5h9476vezhvp2k3kqyjvvt57qel7y8n4f70kn5ffna4m20x3pn2uy3d5c2ywqt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-22T18:26:25Z"
  mac: ENC[AES256_GCM,data:Uf6rAE2VYqw2JoWCUUG6rCodvjGNlZYN1apcrxj/erfY8lQpkqHsIijmfA2HZ8uIuWCICQonmzQBo7vK5cJPVkRje2c7ZAbdMRR/pNMRNvQKmve6dwCkNBA2A2J85DQJwBBhcgXIgQjrtak/aH7Y5urwlZMG6Bn7GpiqCx5KYiE=,iv:RIaR8YIdOFYat8YtG2LCsPZXC7TKi4llyl/hdgvPOtA=,tag:9FSDvxE82KIk29mhg3kbQA==,type:str]
  version: 3.13.3
