apiVersion: v1
kind: ConfigMap
metadata:
  name: navidrome
  labels:
    app.kubernetes.io/name: navidrome
    app.kubernetes.io/instance: navidrome
data:
  ND_ADDRESS: "[::]"
  ND_AGENTS: audiomuseai,apple-music,deezer,lastfm,listenbrainz
  ND_BACKUP_COUNT: "7"
  ND_BACKUP_PATH: /backup
  ND_BACKUP_SCHEDULE: 0 0 * * *
  ND_BASEURL: https://music.guedescloud.com.br
  ND_COVERARTPRIORITY: cover.*, folder.*, front.*, embedded
  ND_COVERARTQUALITY: "100"
  ND_ENABLEWEBPENCODING: "true"
  ND_ENFORCENONROOTUSER: "true"
  ND_IMAGECACHESIZE: 6GB
  ND_JELLYFIN_ENABLED: "true"
  ND_LASTFM_SCROBBLEFIRSTARTISTONLY: "true"
  ND_MAXIMAGESIZE: 100MB
  ND_PLUGINS_AUTORELOAD: "true"
  ND_PROMETHEUS_ENABLED: "true"
  ND_SCANNER_ARTISTJOINER: ", "
  ND_SUBSONIC_ARTISTPARTICIPATIONS: "true"
  ND_TRANSCODING_ENABLECANCELLATION: "true"
  ND_TRANSCODINGCACHESIZE: 6GB
