apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: navidrome
resources:
  - configmap-navidrome-toml.yaml
  - configmap.yaml
  - deployment.yaml
  - httproute.yaml
  - namespace.yaml
  - persistentvolume-apple.yaml
  - persistentvolume-backup.yaml
  - persistentvolumeclaim-apple.yaml
  - persistentvolumeclaim-backup.yaml
  - persistentvolumeclaim.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml
images:
  - name: docker.io/deluan/navidrome
    newTag: develop
labels:
  - pairs:
      app.kubernetes.io/part-of: navidrome
      app.kubernetes.io/version: develop
