apiVersion: v1
kind: PersistentVolume
metadata:
  name: navidrome
  labels:
    app.kubernetes.io/name: navidrome
    app.kubernetes.io/instance: navidrome
spec:
  claimRef:
    name: navidrome
    namespace: navidrome
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 64Gi
  local:
    path: /srv/navidrome
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: disk
              operator: In
              values:
                - local
  storageClassName: ""
