apiVersion: v1
kind: Secret
metadata:
  name: navidrome
  labels:
    app.kubernetes.io/name: navidrome
    app.kubernetes.io/instance: navidrome
type: Opaque
stringData:
  ND_LASTFM_APIKEY: ENC[AES256_GCM,data:lUHzyIC3HThlj2xoAx5LBDs8Fd3Zh5UgLsggfpArHPU=,iv:BEougOXV8GDtxloPWLj4BPNTj4AiINbcslPomhphOC8=,tag:mWZjBDHKkXcKT9RfWcGSKw==,type:str]
  ND_LASTFM_SECRET: ENC[AES256_GCM,data:ux0ip744ogxbg6xM50QZaZC9bZIYUYv1dIG5z5v73OI=,iv:rP5R3l4xd/Zpqpn022SmU85G8WXnI+Cu3VMXGe2JlZo=,tag:d87l3SM/709z/DccgPC1FQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHRjaHkxbXB6
        aVIrczNORzVSNnV5Q1Bkd2RsTTVTRTRoOGw1eEJiT3hYbjdEQmhpbndXSU9MK2Vr
        aEJKdUdBalhTbkpUS0lobGlXUzdwLzRacGJubThsRWZPZXBiOUJhWnBhVjlYWEc1
        L01DS2xuSjAyS2Yxc24yTmhrUCtGUE5CaUVPamFKNE1IZWlxSmVWdVR1aE1pMHFt
        eUljbm5kUEpqeUxPQlVIRjV6NW9za24xUGhGYmFYYXZ4V3A5TFFtTTVvemlCeHVZ
        UlZObkdOOXlKL2VBajlERURvR2pacENKSTh0SzZDSDZGWWJ5b0FmcDA5QXMveFY2
        Nm9BZ3dUbFRqU3UvaXIrYU00Q01QbVY2Qkg2NmhFY3lYQ29ZZ3JBc3R2Wm0yV1pi
        MVdaeklPQ1ZpZ21EVXU1R0tKb0FoWndidDBrVlZrRFFXaEJWTnM3eFlMYytnU09N
        WHAwTlpWTjlYZ1dPRWNPOFVGLzhpZ1UrcUR5eXhZK1dsaHFmdlNLbUNEQ2VFUkxP
        QWJ1bXVwZHBZUVU5cmp3TS9OdHNNVXZBVU9IYk9FSTlzaWhJazZhL1dYaExCNDBI
        ZVVZVHZJYmRvT1NVUDFtUDhDdlhTL1ZVaUxQakdZQTVSMjBYRHhGMHd5MDU4c3dI
        blFodFp5WXdPRmZGanRQWTJheVg3MU9DbEI4MWZMb3d0VTJiNEswZTZwTkhodjFt
        NFVXMzFaa0JSdFNTTk5iUlZCZkJ3R3NxVVlsaWRnYlZQMkpzSEdaZHJnMkcyWEZu
        ZHdhTFJRUzkvR0FrQ2RGNkVXRjUyOGVOYlZxVXh6Qlh1REpFMytzOSs1Sy9MSzdi
        WlFCcFdkRnpabEZtaDVvNWt5dzRQb3VxM2w5SXEwYm9LL0tTbmxKVlBOSzNlSFgr
        YVUrVjh5a0NHd0NYeW1RUDNid1kvRTNFRmJYOGZTN0ZyUVFlNThwU3A0SFBXaEk3
        S0hveGNCQ2VFMDdwTVBwWnU5MEFKUUdReXIxUmNZcTQ2UG9EWnd4WnNidFgrTWNC
        N0J4U25aNUE1WFNzSjVTc0Z5M3FpUnB6V05kR0RVdjlTUU9Tb253MXNpa1FERFhr
        dUNJY09VMzgxdWw1b0hHcDZ5VGNzWWFxNGpBcWZQKzZQQVRNZTl6NjZVOW5mL0Z4
        M0NTdnJPY2g4WllGaEZpZFVNYnVDUml3QS80d3M0d1hoOFlaOWNtbmVPcUEwSVNG
        ZCttQWxuQ3EvMnRDUkxPNWFDUlkwd29Bb21Mc2d0bEN1UkdGTU5UR1lCcXMwUHly
        UHoyN0hrRXZQQ2x4ajNzUzZhUnE3a0pZeXJkdk1GOHpvT2hzYzdpcXBSM0hIVHN5
        TkVJNVNuYTIycVNnazFTTVd5ZEhoYnNia1RoNkhNT1RPcnk4TVNTN2tOMm16Y2dP
        QnlES1NQd21ZUTN1Rk5MSlBIeEx3YnBKajNDb0UrQU45ZTcyU0hINVYwVytoVWN1
        VkJxcmFYbWY3bjNjbFRsTG5KRnNtbk1mSTVZdnpvanVQdEZOR1JZT2ZPeUhnNWJJ
        bURzVGFxZFlXQXdqMkhWS0JLVjg2TlcwcUh2WFFkSU1zU2FQamFRT2RtZWdyUTZm
        dVB3bVFidWpLNWZrZFdoUlY0RzJaa1RyOGVnWWVaL0pQUXh2ZklVZmg0Tll0K2pG
        ckxwektLcWFXZW9vTlBOenRmMHhrcmg5YmR5eml0dmFQeTcraDBweG9vRDRjSktz
        MFJkQTgzZDI0T2IwdFJWSmdKWXpKU0YydjFkamZ2MzN2bUlyakRaeXV1Z1VVWFVu
        MkZrY2x3SS8zQ2ZCY2VWalJZUEhwcGNRWlpxVEN2dk9vUU5sVE5aeXpnc0ZuOUZE
        azdteTREVzh4eE9zQkovYTN1MkJZaVgyMUk3cHh1REwvUjdHaEQ3REYyeHltaGNo
        Qmhpd0pPWjNWczdIL0FLVHJ6bXFEM0dpVWtqMU11RWNsL2wrNDRGcEtLcUliZwps
        NEdOaGl3NTB4UHFMU2lRTklxcjVYc21IVktKWlJEaGs0Z0VIQXhsaGxzCi0tLSBI
        YXBzNnVFV3MvdnVGUzQxT1NvZGF0TjhTN0pQV081cE1jbFozdytGdklvCgJYC3W/
        WLG3DerhUOpLL2+UzpgsUdbMlUL42maNDSEXtbeFNVDN4mvQJmQuG63Zqb7FgB2o
        siDfo6eIfelR7MQ=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1pcc952wp5r5svd72s6anpqzpth2m3lzzp7t5p072dxss4jeymjwrrq8gw5c7szx0lwtazuyvnlupq5n8zv2nxhq7yzwp34pkxdvnaj2u3evlddrkyqxrje255vefhhru9jzqe9z7yja78wgw5ffvlzlqcgrrsu5n0dpaxf9ra8gzdryyht90z4w45wa03keqrgfxyfmrsz30wz7dkgrhr6us499q2pnuj6pthq48qksqmqy8tlpnfv7qr2kswqycnsdal5srludhclg80enjvth6ngmfwmp82u3thdsjghge5zs77qqzm5as39v4e6mxz8lf8g0wg3ds6gaguhj9f3hqs448c988x4hcqyfe97urr00qhverqec22flfkgkgngs8awpkwjeez93mp0zuk7agmygmdrcy8z9zsp6z27sl8f3x6tsgelg3gf8tj86pedvp0etllw3qqyw6wpdq0fggq7qcv6xw6eghzdhv0ljkwwg5v9ahdsy5ngs6673khfhqr8ae7yggk29mhqncgttx966fhfvq329edcza827tgmwvnj60x6hg4qnz4stsnfncmk6m0t00czqrpzuskvm368yth2s9gev0k7g762h6gx6709sred9qp6gr0qes9jadv3d94pynkpjhwmz449ypfy3pdqvhhn78zj92p9snqqqxavz8lzk88mcjdkeqhqvz4dgffja78pe44cukue7vxwdfstwgj24p4632fmzmnfrevst44ssr42kz064ez49mtyjvxmegrdsvadv8k635qffefl42w90f56mn5g0ww725tlay8hsuvevth0uh8vjjfaagkygr3cp3xpjuc9rwc2nyup6df4pk669f256m3ny3s53s6z6ra3sr773803z6z6f70zdqd2uxd36xtanrszj8scq882u8djntyreylvn9gppfyr4xgf67e7at542222cvyusm8jchcqzy7xpuh6v88qf59cw7j5vmmx53q2cpvdgsxeeptyp9tq4pvxshkz9c9muv6lz5ttupxss43z4er7tnsdg42kfzy2qvtfsypfk7wqupv63kg9kfp30nyqcf02v8pd5gl0dzj02eheq35u8fxy705wmu9gp9ytptetz9yrdszzxmszac90un82sgvf42g4v4jp9f4a70gkazhf5vng2pct7z99ggh46lccwgvfjxvmwfz5ff8j5jmzrhpu9nzmtvr8x8evn82gl9h6p5gkm28uhurlwtg32uh8yst3zlq9xygwu2hcm32lj0f3h0kecvvd4m59gteyjs9zpelyj90k4p0g9jrsz5y8edjrhdzanrm353xd6hymuh2qu890k97dgp3ppds56gsza50ddcxve36xr3f4ft08dxlax5589nscuagaa8v0zcntf4d5asrzu8jknr42rk2y34mu54r0cjc0quy278yf657ez2nt33cr9qy3xesvx9uc60juwteuqvttec8knag9mv3q0d3jq9dau8cp5295m4dzjzya384k36rpjgl85r5weaqk60vlymnuugzpj5tyur3sxjds7p55ndjeflhu237zuu84fdpze2csnqzf3ak8q6qz7cjxsaqjhnv5y5ysp99w35u6rxs4u0f03ks7tv9de90cv5cca6sq2pfr6mv4nw8eu52qtp93dn4hgnzfven2r3lrpwelkr3mrpwn4wcrwcqjzytcuzse54ug9hdfnxn8f6edpqy9ztjwnp9mfy2w32keapqjk8dcvjd6n6yzkk2hry55d8cww4p74sdgwrghh84hx4wg57udyul3tmzpmfue7te9wtrxpn6gu287eu42xz2h3f88genu26030ve4nwvs0xcghmflvcjpp0sk5h9476vezhvp2k3kqyjvvt57qel7y8n4f70kn5ffna4m20x3pn2uy3d5c2ywqt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-22T15:14:29Z"
  mac: ENC[AES256_GCM,data:i6CyDXz9FyvJXjkC2d+gqoI3t45AF+d2lYLw5mown9FufFRZ1ihLn45vLHBfDXxkB7PrExdJgRTOBxjGwjT845lmSIhEdhbSaT4AvOLp6H2hp3+gPAjq/zcp0aZiTea04Uw50srQyUUG7N+fociUyu938Ms8JEFuw9jDocsBahM=,iv:eOIcTQqIdbh8ViHoZRLGeAGUgbcyNNcX0GueXtXyivM=,tag:JT8IEmEka4/JaHqa/hLfQQ==,type:str]
  version: 3.13.3
