apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: authelia
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/component: database
spec:
  databaseRoleReclaimPolicy: retain
  login: true
  name: authelia
  passwordSecret:
    name: authelia
  cluster:
    name: postgresql
