apiVersion: v1
kind: Secret
metadata:
  name: authelia
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/component: database
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  password: ENC[AES256_GCM,data:bos3kb74iO02Xi/iuneUU42Hr+gnsapcFzS4CTkomislr7OvQEhWAuzajwHIyFH0Rirb8P0kZKBD1jWVWIu8Lg==,iv:F2QiQbt5rd+uu8a6ltEAxGB+NaszN2p+b2IbNlUjPPs=,tag:HO/azXxIlXeWViMYiPkkQA==,type:str]
  username: ENC[AES256_GCM,data:GJbwa14vvWM=,iv:UWoJ9o1QhdlWmG5xKSG5U/1z3vtp6SPDU3T5eR5nGq0=,tag:zFDlUCLsAHKeXk64Enh3qA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGJkTkR6RGtn
        OU1oWnlHbWpkWHFpdy9mQVZ4T2txeWZISmJiKzhEc1NDSlN6c1EzYWNPcUwvMlRl
        ODJCZWpaRTMxM0E2ZkNxd1BvdmFBMzNtc0pJMkVVVzJrQ0F4MWU3NFBUaFZvZk9L
        Y0VZa3JNVTZoTm53UXhUcTA3K1pxQUEwT2cvYXMrSG92Nm5ERE5hU0tVUGRVbXJL
        bUg1M282RmNKZFdKUitscUxQaHkycnlhRFJlcVRzeVpONE9mYTg1VlQ3a2dSMlFM
        Vkx3aStDUTJvbHNSZS8vUmdiTFFPRUtNc3Vid2hJamNobFJDK1ZrdGMxVjNCVW55
        TGZaNDVQdnBIL1l5b3BmL1RDUlp0QWpGcVJqSFBBeUZKa1VuUWhLTWlMMnpleFAy
        aS9jblRXUDZEOUt2RHprREsvWC9PeEpLbHlvTFZMRmFIRXhPWVlFZ3FjbGFHMkdD
        SHJzT1FDN1lmelJVNTRsNzlPMzZsM1lOR1U1ZTB2NEdLRUVPTjA2cnFtUXFXZkty
        ZU9lWnp5UjhXaVZVUTkxVjNCNVVNV3JzUDZKODFmUEdvSDMvQXZ1em5KanlmVUhu
        WmR5aDBIbFcrSjIvZmF2M3FqQlhLWngvSkIxUTk4Wmw2R0FVUVZpYXczaU1Ld1Fm
        RjROeHFxMFdMeVdKWUJCVU9sTFROMjI4QS95am5sWmxMZWZWRlVFUlh0N1pKSncz
        ZnpZQUJmSEp2UHBhVEVHakVnRFVSQ2VjUTBEUG9NZVd0QkJxRUNBTGNMSVdJZkJj
        UnVBb1FMWmlVOEdjS1R0dk04NTF4TzFMcjRib1JFWHpjZU8rVEFudjlyZElSQnJw
        aFdSS3Z0Mmx5MUlWMGFONnh6Skl1WXlPdWp0RG01MU9QYTNmQ25HdG1FdkF0aWUy
        U0xJUGV4THlMV0hvcSt1R2psYm1HMnBROXBVYmFKU1VaUjNoRDRmdVd3MkRCT2tI
        cjJTODdybFdSVW1OUjNDaWIra1Y5SXRlZ29jQ1UwcnIzUEh6aTJzeUdyajIxYmls
        OEhWeDdOanEydUlRV05nVHNHcDhBMVZFM3hJVFllKzNINnlCRGZiZ1ZCdm1taGdQ
        c3hkMWRTS3dJbFpoRHFGUzZjM3k3RlhrTjlzV3RKYmdVS2ZiUkM1em9VR2tBVVNt
        clRqeEpPQytRK0pxWGdMZFhLbC9qcHB1cXhjT284Tlc4dmhBZTQ4cFQ2aWc0VjVv
        OW10aTJsWktydnZvcmV3dXdPTFYzQ2xyOG9qOFhRZm9rSHg5Qy93SEdoNnY1bHNS
        d1NwNzBQalBzWDBKbTIyR1ZnUWVUSWtzakhEcnZBRlQ3Q1BoSGVwbDRlSmhYL0Nt
        cElTYlBlL29tY1BXUXpOZmRoM1lMaHlLQ1hSM29jWjJkdXVHS1o1dU03VVY3SEdV
        ekFGYk1CRWpydEJ2MUlkemFpdjgwRXVwY3gxaERSdnZpdEJlYk53S2FKY0UyNWQy
        cXBQZkw3T1c1Z1FFOWxFLzJvR1lKTWFoS20zKzRUM01jb1B5QUxGcmxIanFvOGRq
        RkN2dUtnRy9jNFZtVHB4OTJyR3Zvbm9qZ0x0SnFlYjdDTjgyOFdlU1h3blFnL0xw
        MXNlU0kyNFVwY0dRdGZaNEJNOGdLdzk0SlN1RHA4Sm0zWXczNGJXc2xJelJ4RHF6
        WFVKYWsrYWNsb25Cd0NaY25iOGsweXdQRTdsVEZZbWNWb3BqMnVOcVYwTUExdUNp
        enZsMis1WjQySngzSjR6SVJscUNFWi9HRUgzLzg4R0JNQVlNaTBFR1ZtamZrMGxH
        LzJrcUhWQ01wNFNpOTgzSDIrRlIxYnZ1RW1oR1YrclFBdFdYViszR2E0NFBXa1RJ
        RmR2WDVTSmFNK3lrZnhJSG9QSEZyTWd3WVQ5bUhSdTducmoxUFpSbmtaMlAwWm1u
        MFZ6WTZTMER6aUFMNmYxN0IrUzFBRGpTZGZBejlqWGxRdndGL2hIS3ZoT1ZYQQpF
        R1ZFQmdwMmVYQm5xYm9OeEsrKytpandqYUZoUFdYTFIvaklLOG16dHpRCi0tLSBx
        MkZIMVJvK1FQZWdHWHhaTGFkZ3ZwaHc2TXlvTFFkN3ZVaUNKODhNUkRjCmkFPIDg
        BePIcpBRbaAz/WpVEPmy0DAMSvtZYnDA+aCKJsv3gmX9NrTZcrQDMeeWvLCWzfm6
        PtEwOxHqENSJaTY=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1pcc952wp5r5svd72s6anpqzpth2m3lzzp7t5p072dxss4jeymjwrrq8gw5c7szx0lwtazuyvnlupq5n8zv2nxhq7yzwp34pkxdvnaj2u3evlddrkyqxrje255vefhhru9jzqe9z7yja78wgw5ffvlzlqcgrrsu5n0dpaxf9ra8gzdryyht90z4w45wa03keqrgfxyfmrsz30wz7dkgrhr6us499q2pnuj6pthq48qksqmqy8tlpnfv7qr2kswqycnsdal5srludhclg80enjvth6ngmfwmp82u3thdsjghge5zs77qqzm5as39v4e6mxz8lf8g0wg3ds6gaguhj9f3hqs448c988x4hcqyfe97urr00qhverqec22flfkgkgngs8awpkwjeez93mp0zuk7agmygmdrcy8z9zsp6z27sl8f3x6tsgelg3gf8tj86pedvp0etllw3qqyw6wpdq0fggq7qcv6xw6eghzdhv0ljkwwg5v9ahdsy5ngs6673khfhqr8ae7yggk29mhqncgttx966fhfvq329edcza827tgmwvnj60x6hg4qnz4stsnfncmk6m0t00czqrpzuskvm368yth2s9gev0k7g762h6gx6709sred9qp6gr0qes9jadv3d94pynkpjhwmz449ypfy3pdqvhhn78zj92p9snqqqxavz8lzk88mcjdkeqhqvz4dgffja78pe44cukue7vxwdfstwgj24p4632fmzmnfrevst44ssr42kz064ez49mtyjvxmegrdsvadv8k635qffefl42w90f56mn5g0ww725tlay8hsuvevth0uh8vjjfaagkygr3cp3xpjuc9rwc2nyup6df4pk669f256m3ny3s53s6z6ra3sr773803z6z6f70zdqd2uxd36xtanrszj8scq882u8djntyreylvn9gppfyr4xgf67e7at542222cvyusm8jchcqzy7xpuh6v88qf59cw7j5vmmx53q2cpvdgsxeeptyp9tq4pvxshkz9c9muv6lz5ttupxss43z4er7tnsdg42kfzy2qvtfsypfk7wqupv63kg9kfp30nyqcf02v8pd5gl0dzj02eheq35u8fxy705wmu9gp9ytptetz9yrdszzxmszac90un82sgvf42g4v4jp9f4a70gkazhf5vng2pct7z99ggh46lccwgvfjxvmwfz5ff8j5jmzrhpu9nzmtvr8x8evn82gl9h6p5gkm28uhurlwtg32uh8yst3zlq9xygwu2hcm32lj0f3h0kecvvd4m59gteyjs9zpelyj90k4p0g9jrsz5y8edjrhdzanrm353xd6hymuh2qu890k97dgp3ppds56gsza50ddcxve36xr3f4ft08dxlax5589nscuagaa8v0zcntf4d5asrzu8jknr42rk2y34mu54r0cjc0quy278yf657ez2nt33cr9qy3xesvx9uc60juwteuqvttec8knag9mv3q0d3jq9dau8cp5295m4dzjzya384k36rpjgl85r5weaqk60vlymnuugzpj5tyur3sxjds7p55ndjeflhu237zuu84fdpze2csnqzf3ak8q6qz7cjxsaqjhnv5y5ysp99w35u6rxs4u0f03ks7tv9de90cv5cca6sq2pfr6mv4nw8eu52qtp93dn4hgnzfven2r3lrpwelkr3mrpwn4wcrwcqjzytcuzse54ug9hdfnxn8f6edpqy9ztjwnp9mfy2w32keapqjk8dcvjd6n6yzkk2hry55d8cww4p74sdgwrghh84hx4wg57udyul3tmzpmfue7te9wtrxpn6gu287eu42xz2h3f88genu26030ve4nwvs0xcghmflvcjpp0sk5h9476vezhvp2k3kqyjvvt57qel7y8n4f70kn5ffna4m20x3pn2uy3d5c2ywqt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-19T17:08:11Z"
  mac: ENC[AES256_GCM,data:umEh4+8J3vP+v7Lgxy8Ar5k8ugykpKtIRYqvUTCzTVqhSuEdCD/sApyB1xt0gcp7tMmUNpY7R+QdERTtI3mzXuC9qPuaDbRNqUW5APpTpjbKtBPu038NxSrqVSf8e7nkHn3myRJD96nt6cSkoyW6VjKhUt5yZxuk7gp2AeyGM9g=,iv:ljGwUX3dX/BetSXkPni0dlGqNQIETSljsxkKdh+Dfzg=,tag:R8QOT8LSvSDe7oovWWFIHQ==,type:str]
  version: 3.13.3
