apiVersion: v1
kind: Secret
metadata:
  name: grafana
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/component: database
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  password: ENC[AES256_GCM,data:pUchFSW91U2hJmOJsi51t2V0DZWqA5uu3J580aM9kVF+nixrSl9e6L4Sa2FJctclrvpPOOM0pbnhTaRWVhUJIg==,iv:ODEcoxG4b30RHHljSMfznYDwjUME2fysHnQf+tB6LyQ=,tag:+5paoCbOxqJ5cKEB0kjUdw==,type:str]
  username: ENC[AES256_GCM,data:fHEQvhXo1Q==,iv:bnvkijz8Wbk63nD1TQVPWCPa080MqOMF5RX6AQtqxxE=,tag:RMI2jZQVi25MczurbZqJ+A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDhzUGNidk5C
        cWo3YjFPWXk2SDlQTkNQb0xyU04yb2d5eFU3WDR1azBvTWxqT05DMmgyTEJOb1Z6
        NXFpbWF1VG52TnUzWkdCN0pXbXN2UFQ5dWFveG9VODBFbjhoa2pydkhQbjVqSHp5
        M1pvaGVmNHRjT1VveDE1SWIyM2dMemVNNS9VWlRJNStSS0hYZ09KSlVxdHdtTWtq
        TTN6WlVGbEwxSkpkZWQ0UUxyK0lTNElGRHdTYU1MZFhWYS82K2lPQ1hMeXozengw
        cXhaRmU5Q0R3K1ViT1FiZHRZczBHUjRHYUd3cmVGZm9wTzZjVXlibEtaMVpJNXlG
        OXVuQTVTbHFvYy9jNkZoTTBHT0xGbk1nZ3ZFemZ4ejUzUG1DMkZrb1BtdFhMUlJ2
        WmhFWVM5ZXR3VWk3TXg3aU4wOWNZTHZrUDBnV1RVQ3RlRVhuVnN6RnVuWVRtNkF3
        elFleDJLTmdNQlVtR0pwVGVScWhFa3pialhKRWpqMktTc2EyVnNDM1NEMlR0dWNn
        cTlxUlJ5M1lCaXRXbWxid2gvdityS2E3ZWwrWmM5N25SMDlvNUsvYVZFRC9VZFZv
        MDJWSlEyQktzRWorWnh4ZGM1amV1NzBDNFVYV1ZJMDROTlBlMWFKSnZTem5wd0hK
        T29qTzM0WDhCaFVIcTN4RHVrbGRNV3E1YVNyeCs5UC9BaWlIUjdqTWFtd00vaTVP
        ZmJjdmxjOHp3NUpYbHdCT3hIdHhTNVFkYWpRaWFqTXJPMWxUVi9ZT0lwaUpvNk1C
        SDBsa01EeTVvVnFuOVN2L2FXOHRXazBzbkwzTjlyVkM5M3p4eXV5YmNHZnJrdmVP
        MFBpMmhPS3AwY1o2LzNpLzdHcDN3RGI1VVJYYzlOWVdTQ0gzbkl6MEw5N3lTVWlz
        U3hlM0phRW9pSkJ6bzNOZWtjMHVZVWVnbnk2Yk1nSGhaYy9wSEgrZ0lVTFpOcHhu
        aU9vUU5wWEtiVmQyNkgzb0wzMjM1cVJjUlk4Z0g4YUtDNDJXRmF2cllmdWZXZWxV
        YklDRGZwd2hNYUtaaWVnQitxTXpCR3FPT0NERFZ4eHJobEpSSis5SENsWW50Umhx
        cWYyNE9mdkdyRjMvUDRVeXpnVlgzOEt2T0dXVVVJS1dnZzBic2swRUFYUG56MXdG
        dG1nd1I1ODZkdmNUc1huaFhIeGlSa214VjdnWGV5ZXdranZmR0ZyOXZpcjJGUFFG
        LzF0ZUhFQWk1dWVuZFY2bDgwMW9oRmhWekRTeVM3S1pEcmJSa0RjQ3ZNN1FPb3I3
        NHRZTGdWVWFNeFRtZFBGbUIyalp6S1A2cEFRNjlPYXpmSnB4QW43K0Rhdk1wTjVT
        SE5kRzBVamoxaktMVm9hSERHVnlyUDZLY251MGNLVWlmTXZaMFc2ZHE2WDN0UDBZ
        ak9FczdGNEdMMXhvRGtEK0EwZEpBM210TzlTU0F2OVRLY0NTTXl3R0F6SUlKZ0cr
        TXowOWNBdXFVYnJLNjhyWStHcnlnSTNMM0hBN1REZGROb1djVTRCbGptclFlRzNz
        K0dHcngydW5iUWR2UmVJSWlhZjFPdlNzTXljQStVRlpuNlZqVWNZWHdvRGhLNXFk
        K0hLRE5FRmtFRiszMnFheEkxS2R3aUZ1QlBqa0RQbll4MXUrZzhqUHFqSHJEdmpK
        ZHRGalQ3Wml5S005WVduUXNKTkt2MkJ5d0FPUjRXdVRWbXRoVU5JVnNpVmsyVkFP
        ckVsY256Wi9qMUxvdXJRZm9hS0Jka3p1SjJiUFhzRGgzeVdMSjZndEd5dmU4Szl1
        dDFEZG4xaGVXSkZzaW53YzdLSk5BNWFKcHVtMEMySnkyRk1HQm5hZnBVQ29hL21y
        cGh2a01DM1RPN0xHek10QUFkN1ZuRE83Y0srbG1pZE1nalo0YXRoOG9oTTlhdUtL
        RHBiWE5HL2tVQW9MVTVkVTFZUU1VNmc5VWVsN1B2MlR1SVhsQlFEeWRPa2VSUQp6
        MnBsRWNCMXFFelBnYVhEOTdvTkFvSEZnMWVBVGxqSTRRdjl4NS9TdlZ3Ci0tLSBx
        QUJpSzZuUkVvWTZQSlhvZ2JsNFBlU00zNzNJSWtUSjBPMklMK0M0NGQwCh6GZOKR
        42sgfHHpe9hlF22wei2Ar8ac+9QQLjf310TWmGU7kzp4HY9S3NjB4ZnDGIKJ2V2g
        njVq3vf2a/lohXY=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1pcc952wp5r5svd72s6anpqzpth2m3lzzp7t5p072dxss4jeymjwrrq8gw5c7szx0lwtazuyvnlupq5n8zv2nxhq7yzwp34pkxdvnaj2u3evlddrkyqxrje255vefhhru9jzqe9z7yja78wgw5ffvlzlqcgrrsu5n0dpaxf9ra8gzdryyht90z4w45wa03keqrgfxyfmrsz30wz7dkgrhr6us499q2pnuj6pthq48qksqmqy8tlpnfv7qr2kswqycnsdal5srludhclg80enjvth6ngmfwmp82u3thdsjghge5zs77qqzm5as39v4e6mxz8lf8g0wg3ds6gaguhj9f3hqs448c988x4hcqyfe97urr00qhverqec22flfkgkgngs8awpkwjeez93mp0zuk7agmygmdrcy8z9zsp6z27sl8f3x6tsgelg3gf8tj86pedvp0etllw3qqyw6wpdq0fggq7qcv6xw6eghzdhv0ljkwwg5v9ahdsy5ngs6673khfhqr8ae7yggk29mhqncgttx966fhfvq329edcza827tgmwvnj60x6hg4qnz4stsnfncmk6m0t00czqrpzuskvm368yth2s9gev0k7g762h6gx6709sred9qp6gr0qes9jadv3d94pynkpjhwmz449ypfy3pdqvhhn78zj92p9snqqqxavz8lzk88mcjdkeqhqvz4dgffja78pe44cukue7vxwdfstwgj24p4632fmzmnfrevst44ssr42kz064ez49mtyjvxmegrdsvadv8k635qffefl42w90f56mn5g0ww725tlay8hsuvevth0uh8vjjfaagkygr3cp3xpjuc9rwc2nyup6df4pk669f256m3ny3s53s6z6ra3sr773803z6z6f70zdqd2uxd36xtanrszj8scq882u8djntyreylvn9gppfyr4xgf67e7at542222cvyusm8jchcqzy7xpuh6v88qf59cw7j5vmmx53q2cpvdgsxeeptyp9tq4pvxshkz9c9muv6lz5ttupxss43z4er7tnsdg42kfzy2qvtfsypfk7wqupv63kg9kfp30nyqcf02v8pd5gl0dzj02eheq35u8fxy705wmu9gp9ytptetz9yrdszzxmszac90un82sgvf42g4v4jp9f4a70gkazhf5vng2pct7z99ggh46lccwgvfjxvmwfz5ff8j5jmzrhpu9nzmtvr8x8evn82gl9h6p5gkm28uhurlwtg32uh8yst3zlq9xygwu2hcm32lj0f3h0kecvvd4m59gteyjs9zpelyj90k4p0g9jrsz5y8edjrhdzanrm353xd6hymuh2qu890k97dgp3ppds56gsza50ddcxve36xr3f4ft08dxlax5589nscuagaa8v0zcntf4d5asrzu8jknr42rk2y34mu54r0cjc0quy278yf657ez2nt33cr9qy3xesvx9uc60juwteuqvttec8knag9mv3q0d3jq9dau8cp5295m4dzjzya384k36rpjgl85r5weaqk60vlymnuugzpj5tyur3sxjds7p55ndjeflhu237zuu84fdpze2csnqzf3ak8q6qz7cjxsaqjhnv5y5ysp99w35u6rxs4u0f03ks7tv9de90cv5cca6sq2pfr6mv4nw8eu52qtp93dn4hgnzfven2r3lrpwelkr3mrpwn4wcrwcqjzytcuzse54ug9hdfnxn8f6edpqy9ztjwnp9mfy2w32keapqjk8dcvjd6n6yzkk2hry55d8cww4p74sdgwrghh84hx4wg57udyul3tmzpmfue7te9wtrxpn6gu287eu42xz2h3f88genu26030ve4nwvs0xcghmflvcjpp0sk5h9476vezhvp2k3kqyjvvt57qel7y8n4f70kn5ffna4m20x3pn2uy3d5c2ywqt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-22T15:14:29Z"
  mac: ENC[AES256_GCM,data:1hadzJ25evjzHk1YC2GubQ1ZB4/TYo4g5cevADuyWCgPyaNz7/kxSqWWMza1diX/KUOXHicOW4XVJgS3Ibgr76l6DsN4D2X5CuG4Hsnsxu9Fxzc2AtAZFKTZ0u81Tg+JJeUu23M0PslAX6S12hYFpiQTKDeELkw3j7E8Z0RuCFg=,iv:ocPoCQoIUrQKIE6D7AQhDdscV9U6bTZyUWJfNbG9KKs=,tag:owae4hkms+jeBkEwp9gAnA==,type:str]
  version: 3.13.3
