apiVersion: v1
kind: Secret
metadata:
  name: grafana
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/component: database
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  password: ENC[AES256_GCM,data:oSIv8gD0lRynpsl4Gg7W7GlvPktN1/o40CKYT9pIoYITOPKXgRIkpF1cYSvZo9DYVrgZYWxf2O0AXGT+bPyOog==,iv:ZALs87Zis74MJTS0vAjAYoBSgXBW9CSyA0YN1fGz2gA=,tag:oihNGturyS4g5rV+QmeSsA==,type:str]
  username: ENC[AES256_GCM,data:b/0DywMpOw==,iv:660tOvHxyHGreBmyZQwsq0Y583bc3eRPXhPkJwG46LE=,tag:E1ypWkwjC16by5PGUcE8GA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGprdGVBUXhX
        MjNFNHoveVdCTVJhWkFSSmZxcVZ6UGJmNmNPZFVlQ0QwYm84d1FMUFBpM0FqL1B5
        UWlrUG9sZExiYjJSS0Uwd2U0aUJFd3FUQWJKS0RjY3Iwa211QmtkMFE3bDVLaWUy
        N082QkpWTUhxdUZOQzZuOWpkeTBES3JxL1RpVkpaRk5sbytmVWI0cStCRWI1bldv
        dnpNbzVWWUtsem5IcDVCbGE3VkxzRHV6QjZsVUUxSmdGNDJoT2ZxVjBKQ1NpeGx4
        dG4vRmc1UXJaZU9iTzlOdHN1U3dNbE9yd1I0dWxnd1F0T2M4OTVJTUJHQXBoRlhh
        VnRlb3Q3b3pPaTdVN09vSjRmUkpSTDhMTktOTUpJWFFINk1aOXJlaThWY1Q1NTRY
        QXNDa05TbCtUZUEwK2xDdFl6eHhNai9IYm9QOC9KT3lBcXJMM0wwQ3dVMUZRdlJy
        YlJxVEVKWFZHekRXWE9WZmVMaEEwcDRnRTBaQVdLNmh1cVdZOEc1R2pYckVxT2tC
        cWhOTlpsOCtXWStyc2xMQUgwc2h1TktTQjZGUnF1Z2hCS3AwT3dHaVN6eUhreTBs
        S3g2aFl3V2hmUjZqcURLSjBBbmxxTTlXb2owMDcwUGt3cXgwSXkvSzU3a2pkSGV0
        WGcwVzUwT2lzUy93MUxMRjFWTkhYRmlGUnhhc1ZnUWI4V25YK3lzTWEwZ2VWdDMz
        c3dxU2J6T0NHNFBQVEtmM0NHYXNtWGhaMTRyNmI5Sk41UnJ3ZnlwcmQwU3NHUDRk
        YzlPUzdlMEQyOTVEVEp0VTNxRGxlaG1oWHpJMm5ZL1RmbXN4SlRBOEJsY3ArWE9Q
        dXUvRHFlb1VrVXYwOFdNeEZxZFZ1RFJxVThHOEFyZ0ZwS2cvZHB0TU4xMzFyTnpz
        ak52YmVoVE1iTGZqUE5Ia2ZyY0RqZlVzS3NEZGN5eEVOSzYxem1jelZjc1NabUg1
        SDh3amIzWnlzVHJUM0lGL0pZWVd5QXN0SEFUeFdqUkRNbXVrN3I1WWpKdHl0TkIr
        RTA5ZkJwUEtJSHNzazN1emNxdEp1T0dEVnp1RnY3SCtNeHB0UmxvUmJ6aTd5L2hK
        d0VNUDMvNVhybUtGendHc0J6NkhNWGFMWHBRK2J5OVI1VzZFT0NOcyttOXB6eUVl
        SnhJdUZyRE5ldmpBdkVnYmNlc2h1S3crYjhRTENPR0RzUU55SDF2VklKRDcxMEpo
        OTIxQWV4bUZBaW9CWWlsNGZhSUFFbVRFbWlGUk5nc3o4eENrb2NCWW84RWVnYTNH
        eUZJeXU3ZHAwTDhOYVhIUCtUTWMzOXFYTnBiMnBLWHF6MFVsWmRkOWRoWmV4MWpM
        K2Y0ODczNWdmVVJuYWdGRFBrVVdtcFBRWXNUTlZOMUhKb0d1Qm44NCszNTYwd3RX
        b0xLaTY0enVQWjlDOG9CMTJMMGdmSUNiSGZQNjg3UmlqTUI2SEUramVVUW5WeTg3
        dE1aY1lGOTVaRWEwL0RyOWpwWlV3NlpQV0N3NTRwY3BBK1FuNE5VQWw3RnRJNmJz
        Q2JxUFNYQk1rVXMyaXp2VlZwTExPZ0pCTmdZZnVpYnJJc1dzV2dlczl3cTI0TXhp
        cUZ6VlZsdExXVUZWdkFpbGYrVlRGNHRNRWhzYlpkeGJjZnA4UThFMGQ5K1Z4Q2Vk
        eHlNYnRrdTZ5Vm1VWW1qd3lDUGYzTWduT09rVlBGTTlWSFB4UCtzY2NYekFJbXdJ
        K0djTXNyT2tLNHRrOVRTcnp6MnVPWG45bnZOWXloK0RkcEF1UzBRL1BFZDN2LzY0
        SVlONlkyanFaMEprQzFvV1lNN2QzRDdXVVR0dGJSYWxhaHFaTi9pYS9CNTQ4V216
        T2FJM3pUYVA4VFdTc2FkT3orOWloaUNJNWhiQlRGUWpxQU1KSE04UzA3RWtTOVow
        aGFtcTJvVUU5cmc5RjM2b3ladjk2WDRzMXY4Ykh0RkdtUHljVWoyMnJWTzNCZwpS
        Qi9FTFo0Y093V0dyTms4QnF6dWpsWXVFdVJrTUlyL0FXcGtCa0gxWGJVCi0tLSBY
        SE9FbmJTNzh5aERQSThkVytsSEdROTEzc2tFcUdGMjBoNTA2NTluWkZnCjbgrUqq
        nJz9Xi40gB0jRhR8MiX9C5N8lFOAjfnA6nXD1+Xf83RLgqqL8WVcwf3kzTsJHq9a
        Cawd0Ug9poy9Ppg=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1pcc952wp5r5svd72s6anpqzpth2m3lzzp7t5p072dxss4jeymjwrrq8gw5c7szx0lwtazuyvnlupq5n8zv2nxhq7yzwp34pkxdvnaj2u3evlddrkyqxrje255vefhhru9jzqe9z7yja78wgw5ffvlzlqcgrrsu5n0dpaxf9ra8gzdryyht90z4w45wa03keqrgfxyfmrsz30wz7dkgrhr6us499q2pnuj6pthq48qksqmqy8tlpnfv7qr2kswqycnsdal5srludhclg80enjvth6ngmfwmp82u3thdsjghge5zs77qqzm5as39v4e6mxz8lf8g0wg3ds6gaguhj9f3hqs448c988x4hcqyfe97urr00qhverqec22flfkgkgngs8awpkwjeez93mp0zuk7agmygmdrcy8z9zsp6z27sl8f3x6tsgelg3gf8tj86pedvp0etllw3qqyw6wpdq0fggq7qcv6xw6eghzdhv0ljkwwg5v9ahdsy5ngs6673khfhqr8ae7yggk29mhqncgttx966fhfvq329edcza827tgmwvnj60x6hg4qnz4stsnfncmk6m0t00czqrpzuskvm368yth2s9gev0k7g762h6gx6709sred9qp6gr0qes9jadv3d94pynkpjhwmz449ypfy3pdqvhhn78zj92p9snqqqxavz8lzk88mcjdkeqhqvz4dgffja78pe44cukue7vxwdfstwgj24p4632fmzmnfrevst44ssr42kz064ez49mtyjvxmegrdsvadv8k635qffefl42w90f56mn5g0ww725tlay8hsuvevth0uh8vjjfaagkygr3cp3xpjuc9rwc2nyup6df4pk669f256m3ny3s53s6z6ra3sr773803z6z6f70zdqd2uxd36xtanrszj8scq882u8djntyreylvn9gppfyr4xgf67e7at542222cvyusm8jchcqzy7xpuh6v88qf59cw7j5vmmx53q2cpvdgsxeeptyp9tq4pvxshkz9c9muv6lz5ttupxss43z4er7tnsdg42kfzy2qvtfsypfk7wqupv63kg9kfp30nyqcf02v8pd5gl0dzj02eheq35u8fxy705wmu9gp9ytptetz9yrdszzxmszac90un82sgvf42g4v4jp9f4a70gkazhf5vng2pct7z99ggh46lccwgvfjxvmwfz5ff8j5jmzrhpu9nzmtvr8x8evn82gl9h6p5gkm28uhurlwtg32uh8yst3zlq9xygwu2hcm32lj0f3h0kecvvd4m59gteyjs9zpelyj90k4p0g9jrsz5y8edjrhdzanrm353xd6hymuh2qu890k97dgp3ppds56gsza50ddcxve36xr3f4ft08dxlax5589nscuagaa8v0zcntf4d5asrzu8jknr42rk2y34mu54r0cjc0quy278yf657ez2nt33cr9qy3xesvx9uc60juwteuqvttec8knag9mv3q0d3jq9dau8cp5295m4dzjzya384k36rpjgl85r5weaqk60vlymnuugzpj5tyur3sxjds7p55ndjeflhu237zuu84fdpze2csnqzf3ak8q6qz7cjxsaqjhnv5y5ysp99w35u6rxs4u0f03ks7tv9de90cv5cca6sq2pfr6mv4nw8eu52qtp93dn4hgnzfven2r3lrpwelkr3mrpwn4wcrwcqjzytcuzse54ug9hdfnxn8f6edpqy9ztjwnp9mfy2w32keapqjk8dcvjd6n6yzkk2hry55d8cww4p74sdgwrghh84hx4wg57udyul3tmzpmfue7te9wtrxpn6gu287eu42xz2h3f88genu26030ve4nwvs0xcghmflvcjpp0sk5h9476vezhvp2k3kqyjvvt57qel7y8n4f70kn5ffna4m20x3pn2uy3d5c2ywqt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-19T15:28:22Z"
  mac: ENC[AES256_GCM,data:Za/dxw5xvbEGxv1zZsBtw22G6oNwi1lXu/KWCesgPlHE4+hLD0+eIrApfRInC0f6rTw29xVTxGwx2VTIfzqJ6m5Ig2Ucmxretw80res9ZuN7W1EhHPmDV0xXLdokkQuUsPwDwn8ikCUwhnwxgSpOnlt/VteEgAGR1AyzxpHrSQM=,iv:uns0JsUcfbwcypaar4Bw79Jg2Lw6p0/R1iCWG/sGoiE=,tag:a3/liUmOxQqeDtwRHp2lvQ==,type:str]
  version: 3.13.3
