apiVersion: v1
kind: Service
metadata:
  name: immich-machine-learning
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/instance: immich
    app.kubernetes.io/component: machine-learning
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app.kubernetes.io/name: immich
    app.kubernetes.io/instance: immich
    app.kubernetes.io/component: machine-learning
  ports:
    - name: http
      protocol: TCP
      port: 3003
      targetPort: http
