apiVersion: v1
kind: Secret
metadata:
  name: soju-config
  labels:
    app.kubernetes.io/name: soju
    app.kubernetes.io/instance: soju
type: Opaque
stringData:
  soju-config: ENC[AES256_GCM,data:Z8PRjSIROxzFcUAo1X+N1ONF4p684kePRorIB2Lv6mInNbFd9/K5lJaA/4oqcmfwlm67iEUPKS8TeU3xvfKa1CM9yg/Nb/I3E6Puxe+1qG5VtaXqhHxufBuP15KNQj2jkew9e9vRzQ03AhD8RZsIWgA1VBVsa6nwmemTjgH2csikl7xkQQSFyavrdGSN0iYdmEFVSQUWIsrMUcap3yAIlOY/+KxczyW60AAFoMyRRqsPZMGK9YtWos0WJPSmOrJAW/7G7XMzfEwDK2m8eIr8u3WupNPmzi6k24zzbBnHkTks4xpEpFEvQM5MvAMapTaKQAfieKWVdZQsQVPQKHkEfGAtB59E6lsVFvbckNr6GCvRmxGt3OWgJyHT8wZSQOuG1arVkz/EGwX57dF7e1TJ3/ghjS2GAmwBUOP+RDRJGAAaeCkxl/dnjP64DljR0xm43utdLFrVxxKDpaGifNRnKa3QKjZqyWjI6anplEF20g==,iv:nyzY1zWGDCMcB7WSwCPRiKa5JGPMZYjZhSVsv/pR6NM=,tag:yvUSuvCqnIt2fHltFuGeWA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IE9WaVdWRlVN
        YTFuZlZMcGZYY1lrUmZLNTViZkE4eExuYVBvYy9wZTFzZGVLd09MZVhMVGs5NXc1
        cmc4MmlUME1pSDh6SjRQKzRscERhQkM1QzlUVHMyK2wwSlJaYi9Da1JvNGh1UkJT
        ZG90Vy9Ic1pVNENCWDA1YmxtbTgxSVFwbng4UTZJMmVHcG9rRC81KzVxS0laV2cx
        WElDSGNKWStzeFR5b0l2cURuZDcyRlRFK0puZE1RTW11SGhzdXlrbjl5cjhnRENm
        QTBCWGNudG92dGhqQUJTcHY1TEM1QUF6S0k2ck0wZFpqdGh2QkQvMDZMNFNWWkQ3
        T3NHSXA2TTdVZS9lbFZqVW1qcWRXeTZsQUlTQUVrOVV0VG1ENTgxUkJBUktjUWp5
        MzdWdjdqTDM1UkxBRG9rMUpUSURrT2w3ZG5YOE4zZ0UxbDdoSmluczUzWnAzek5O
        amxoL0tBYzZSNzVtdHRZanpNc016SWszaDd6NEZWVERGU1N5OE9meUwxaHZ3Q3Fv
        TVdUS2tiZmg5dlJWWVVRVVBpYjBhc255Q1Y2Mk4rbWZSTlFHMUhnQlhCUEt5bE0y
        L2NZVUdsKyt4dk4vNFRuajJUaGg5dit4SlZHVzM4TlpRWDFqdXFwaTVPSVZGQ2g3
        ajlUbDB3M3NjMzBlaXpkZDNTUytQM0JDeTRlaXhVNkVNRjRjVER6Q1lOR1hNU3Fo
        ZDMvL2lnTGFQdk9RSnV6K05UQ3dBUnNuMGlRT2tDN2JLa3cvdkhXUEdlOWpya0pL
        WjRxQ1A1elhhcHRDbTBmcm1DemlPNFFsUlBYbGVuNjRIZVhDNTc3dU11eVdoUzNj
        RlF5UndSR3NmcWpyNmxISVZwWUtvV0kyT0ZMWTRHQm5wd0Nsc01nbXJpWDk2aXND
        bElpb3Fnd2k3T1l6cjlnalpSdDg3QWRiemFJbzE0UVJBRjBZNGVXa1RPMWFVWWR2
        RlJGSU5CckdiamhiYlR3VDB0bi9JekpPNlpDZU4rUkl3L0wweGZZT1Frb3N3UzF2
        UU43cG5ZRDM2dmpTVkpKTEZJdVRoR0lwaXpvbHExbUpCUEliSHpQd2YrZDJKeGlr
        NVQ5ck1UNXg0ejJTeUdKVWxMUTNZT1gzWTFURVBJTldLdS9QamJzSzJ2a21PSG15
        eVFnUkhHL3JxanQvZmlWREhZU3FGV0NoWGcyZmZJa20vZitLdXlxNDFxeWVlem1l
        YVdHRllpbFhKYmsxZksyODBCazE3OHA5TkJWcjZKTWtpSkdaNnRma3pKNDBQMURy
        NXhoVUpHQlg2bmpsKytLRU5ncXEvcnF3Y2M3SVFGNFBPSDVJa2pzdWxMdm5VMzdu
        c3U3bUtZZUxMWHZZeUJtWjg4R0MrOFZiWXE5NGtXekhERHdwOGU4SGJsUlRaYzNL
        T2Zib1lPV2NPTG5adEVveHMxMDh6UWdBR2lKNm1Xck5DSW1DS3RNSkh3ZU94cjhJ
        ZFdnVSt6TEs2bVk1QXEvZTRxZXFJWHg4Qy85N25yYzJEY0NDdURTQlljemtnbUNT
        RXpJcXdGOFZDSzZ3R1MrZFpRcGo3UWhDbGZ2Ty9hbk5DR0x4UjJ5d1pROU40N3BQ
        aDhBT0Z3b2hQazhhek5EZEZMTkJobGUrL21RdmdDMEcyV3ZnUXA2QkczV1JNVVEy
        QkxqU2pFaXRoenRHQXRVMWNGdHlGdWpMOW5mLzBVUW91TUttRmp1VWwzMWFlMXVq
        ZWlMU1FrVTFQNnArUVhPQ0VZZno4Ymd1Y01YQndqZmJvY0NacGppa2p5bXg4VHla
        R1FVUnJ2bHl1TmdBNUFuWFR5bmhOUFMza1RDWUpPb1dGK0VGMS9lTWFZOTZnZEZw
        N0FVWFhvTXFpeWdReGFwRjBDUTlXNjV5dXZ5WmJtdnFubXp3aWlQTnNiUU1OMGRP
        d3lqbElLdGRSa0taaGczQmd1Z3FxSHpQbnlCZGJoYU05dW5mUEFUZmdXTHhBZwpv
        OEt5NU0vTFNUWXZJaEhGaHhxSTlaL0tDenNmNnZrRm4zZ3dWSVF0d1U0Ci0tLSBY
        MU9GVUVPZFJ6OXFrQnkwTUI1MVU0cU9GQ1ZkZ05GMUVJNjMrWEJxMnBZCsHqyv2l
        dXvihFnfnGrn7c4WAbFyXe3gkzX2v8WhWEhJ1xw0qH45k4SDLLjpoJYT4EDFen5w
        QxqQ+wvmKfDovfI=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1pcc952wp5r5svd72s6anpqzpth2m3lzzp7t5p072dxss4jeymjwrrq8gw5c7szx0lwtazuyvnlupq5n8zv2nxhq7yzwp34pkxdvnaj2u3evlddrkyqxrje255vefhhru9jzqe9z7yja78wgw5ffvlzlqcgrrsu5n0dpaxf9ra8gzdryyht90z4w45wa03keqrgfxyfmrsz30wz7dkgrhr6us499q2pnuj6pthq48qksqmqy8tlpnfv7qr2kswqycnsdal5srludhclg80enjvth6ngmfwmp82u3thdsjghge5zs77qqzm5as39v4e6mxz8lf8g0wg3ds6gaguhj9f3hqs448c988x4hcqyfe97urr00qhverqec22flfkgkgngs8awpkwjeez93mp0zuk7agmygmdrcy8z9zsp6z27sl8f3x6tsgelg3gf8tj86pedvp0etllw3qqyw6wpdq0fggq7qcv6xw6eghzdhv0ljkwwg5v9ahdsy5ngs6673khfhqr8ae7yggk29mhqncgttx966fhfvq329edcza827tgmwvnj60x6hg4qnz4stsnfncmk6m0t00czqrpzuskvm368yth2s9gev0k7g762h6gx6709sred9qp6gr0qes9jadv3d94pynkpjhwmz449ypfy3pdqvhhn78zj92p9snqqqxavz8lzk88mcjdkeqhqvz4dgffja78pe44cukue7vxwdfstwgj24p4632fmzmnfrevst44ssr42kz064ez49mtyjvxmegrdsvadv8k635qffefl42w90f56mn5g0ww725tlay8hsuvevth0uh8vjjfaagkygr3cp3xpjuc9rwc2nyup6df4pk669f256m3ny3s53s6z6ra3sr773803z6z6f70zdqd2uxd36xtanrszj8scq882u8djntyreylvn9gppfyr4xgf67e7at542222cvyusm8jchcqzy7xpuh6v88qf59cw7j5vmmx53q2cpvdgsxeeptyp9tq4pvxshkz9c9muv6lz5ttupxss43z4er7tnsdg42kfzy2qvtfsypfk7wqupv63kg9kfp30nyqcf02v8pd5gl0dzj02eheq35u8fxy705wmu9gp9ytptetz9yrdszzxmszac90un82sgvf42g4v4jp9f4a70gkazhf5vng2pct7z99ggh46lccwgvfjxvmwfz5ff8j5jmzrhpu9nzmtvr8x8evn82gl9h6p5gkm28uhurlwtg32uh8yst3zlq9xygwu2hcm32lj0f3h0kecvvd4m59gteyjs9zpelyj90k4p0g9jrsz5y8edjrhdzanrm353xd6hymuh2qu890k97dgp3ppds56gsza50ddcxve36xr3f4ft08dxlax5589nscuagaa8v0zcntf4d5asrzu8jknr42rk2y34mu54r0cjc0quy278yf657ez2nt33cr9qy3xesvx9uc60juwteuqvttec8knag9mv3q0d3jq9dau8cp5295m4dzjzya384k36rpjgl85r5weaqk60vlymnuugzpj5tyur3sxjds7p55ndjeflhu237zuu84fdpze2csnqzf3ak8q6qz7cjxsaqjhnv5y5ysp99w35u6rxs4u0f03ks7tv9de90cv5cca6sq2pfr6mv4nw8eu52qtp93dn4hgnzfven2r3lrpwelkr3mrpwn4wcrwcqjzytcuzse54ug9hdfnxn8f6edpqy9ztjwnp9mfy2w32keapqjk8dcvjd6n6yzkk2hry55d8cww4p74sdgwrghh84hx4wg57udyul3tmzpmfue7te9wtrxpn6gu287eu42xz2h3f88genu26030ve4nwvs0xcghmflvcjpp0sk5h9476vezhvp2k3kqyjvvt57qel7y8n4f70kn5ffna4m20x3pn2uy3d5c2ywqt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-23T07:50:22Z"
  mac: ENC[AES256_GCM,data:USrHIwIyw9coXbZbvtas35VfiLh/m3FO8EHmE5P6qGmHIf9R0Sg/pEUxWoJSgWmfYVAcmaLMV9CHKPnLuu7ehoH0V3YL5//G/LZhPhkinhBKdMOr7h/PY1nTcEtVmtTsF7ybYUFiJ6QOtvjwZ0eP0rIKDpevzCxx4tPxNoV7eW8=,iv:OHdxgiciATRXJDH2huasozcmWAts+LuOHeMVdi++tEY=,tag:ieDGHqYMmdttXXUcswHz6A==,type:str]
  version: 3.13.3
