apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: audiomuse-ai
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/component: database
spec:
  cluster:
    name: postgresql
  name: audiomuse
  login: true
  passwordSecret:
    name: audiomuse-ai
  databaseRoleReclaimPolicy: retain
