apiVersion: v1
kind: Secret
metadata:
  name: audiomuse-ai
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/component: database
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  password: ENC[AES256_GCM,data:HJn/eZZu1kRjmltIIztwy2vbrNlFOPCwBQwI9KBemd6WdTV3KLbdAMJrOt9m9sqIA4McQwR2BRYiTo2XpTWDyg==,iv:nnemiV0f1FFRnXeLLxtAucYDd9Shlm02QTKgLOZ799M=,tag:dBiIdmhTohZ0+8d0lgsSzw==,type:str]
  username: ENC[AES256_GCM,data:pxkLQEhl69Qq,iv:yS1i+UDElhNtEGf90pE6XbzfVXlrWanqq5AL2w7fES4=,tag:lUxudeFYPQ7FqH8A2o3tVg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGY5dFZKSm5x
        Y3dSREFUZXZnV21vUS9GUGFtYUhGcjNwRmlSbEdDamJuMzRvelRFajdua2N6K1cv
        WmJpM3lJanZ4Q1AvOEtnQWxZeE56S0J3WGFNdzhleHY2ZjB1ZGgvMXpqaU5CdWhy
        MTNqU3VPcmR1S3lSckFTV1pLWURCaTR2eWJMS3R0TjMrNjd6SmtVVHVoUEU4VFVy
        alozQ1dRVDBhSDRWVU00T2dEeC9nRk85Sm5nWHR1c1o5WVprQjg2M0tGMHhFNEFL
        QlI2WTI4NjgxTmkwSkkwS01lK1Y3OHo1NENxRnZKSjlEMmRFVTJEbzU3OFpzdXli
        R01IY1VvaFZOTzZMZW9nTEFZa2JsZW12SWcrbVhnbUNoa2lWczJhY1EyYXVRcHM2
        NVlqWVNTbTIzY01ERjJwUHllSUNBUDhrekdFVnJ2YlQrbSt0SkVWYm1CVGxta1Ix
        Z0ZvMFp5clh1aGw1L2Q4Qyt2N1ZnWmxRZzdNcmxlUE9ONmxwZmFjK2tlaGZaOUQ0
        VUpUZ2x5NlZYM0NOWmt0bzZma2x1Vkp6WHNJdS9DRjFXSmpENGVWdDI0THZRK09j
        OW9kZFR3TGpHYkQ1ZE1PTWkwYTNhSG8xWGVIUGN2bGxod1ZVbEpUZW9icHFWUnd1
        aHRxNlJXdWE0clYzY2VkdkNIVUhyWXBTVkdCTkFSalZpUlZGdDFLSGNQZ1pvblJ4
        cFlhcit4WUcvY1lsNXZqY3BWdGYxYjk3eDhBaHpweThMT1FJTG84TXBta1F2TGhm
        aVA0czhqUkxLai9RR2RGUC92UlJBbjBNVUtmWDlaMnhFVHZ6eEI4eFVESGpGL1lW
        SnBnV21nazJrM2dtTDR3YVg5VHAyaDI1V1F3cDVCdkFaYzZUelh1b0tBU1Fqa2Iy
        QTEva003TVV2bFJ1Q2VMeEpvd3BpK0dCaEJtaitHWEEzWlVrSDIrT3VJNWVTaTg5
        dmJxZmRKL2tBNVR6ckVZUnp4S0JxVUttd0FaUzkwaGdZRXJaR1d2OUhncit0OXVP
        cDZ6N0w4T1pTVG5SREsxVWY5dlRPbSs5SUQxc1RmOVRPZXhCWmtaZXRrUXp1d1lu
        QWZLR0ZrK0VFVitMMDYzREdzYmpUTXZBSTczV1VOaUw3YjdYNG1PVEZ3Vm96dTI4
        N2lZZUZ0am5qWHdoak42eGh6Qk1QY1J4dWdDbCsrbnZoSDRlS3RqN1ZGTFNHSVcr
        eXZoQ0p6NGZ2VDNSMDhKaDVSVVFRVkdZL092RzR3RytmSGpDTGVZaWRtaXJzV0dl
        dlBidGxwSEdMSy9LZ09DZU5ZdjQ4VjZsaFU1ZXNHaXhUa1dJb2VmNlI2VDJWVnNy
        eWQ4dksrZGNNV2hyU0E0OTBQWVdOUW5EekIwbzBNZ1lJWkJSVUpWNGdlQUlaNjNW
        N3NWQVlwb0FOZXlUaHdiM0gyRmJaa09lNjRKS2UxaEhBVmVVckxROEdKNktZMmlk
        T0RiQ2t5RjlXUGR0clNxeEdMVDhjcDFQeTFKNUhWRUNrZVNEUDA3K09ReEpRSHpG
        YjBqL1cwbmhtbS9FYUlJMkFTQ01TcXJQR21mNGlWMzBlWGJxZzB1RGFoemZXRmxp
        ZENWRGRnRFJuOUJOYllqNksxMFJVNmJXR0RVUmJwb3Q5MG1VMDc1ZTZINnE5QTRN
        UktwZXVDc01reDRwYjFwQllhWXJZY0t2aExaMk1xenFMTjV2MkJyRkFpNGdqdUh3
        WUNPKzUvenFKSXhKSG1EcVlMaUoxQWJxaEhqUlRwV2xlYmw3QjlTNWF0T0R5YWV4
        ZDlMWUZwa3hjRXMydjdjZE9tQmxsMnM3Y0c0U1pRWlFKUzUrUm1EOWxnLzJHRmhU
        Q2ZLZXF5TS9zVkdHaGJjOU1TVnB0YmFFc1o4SVlaOGY4OSt1Z1gyK3JiZmxRRUR1
        YXdRNHVsbzJTTEhVZDdUbWpKOEE3N0lHeEVoMEI1MkNPclpBUU5GNkY1bmREQQor
        c2JzWjBndFp3dmNHcFRSM2J1ckxOd3ZoQm1MVnI3ODI5d0Z0OFREZ21ZCi0tLSBk
        UzdIOFI4UWh6MUhUNVJCMStTMEM4enZ1N05zODVDN0IzclZhUDFRNm5nCjXb/i4j
        R/sHlQmvyXFS5lUOGtUB09tDLTNwC7Ukh4W5PN2ak+uSKO6hXxGUWJ7pJT4CoyFw
        B2m4acVS22pE4Mk=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1pcc952wp5r5svd72s6anpqzpth2m3lzzp7t5p072dxss4jeymjwrrq8gw5c7szx0lwtazuyvnlupq5n8zv2nxhq7yzwp34pkxdvnaj2u3evlddrkyqxrje255vefhhru9jzqe9z7yja78wgw5ffvlzlqcgrrsu5n0dpaxf9ra8gzdryyht90z4w45wa03keqrgfxyfmrsz30wz7dkgrhr6us499q2pnuj6pthq48qksqmqy8tlpnfv7qr2kswqycnsdal5srludhclg80enjvth6ngmfwmp82u3thdsjghge5zs77qqzm5as39v4e6mxz8lf8g0wg3ds6gaguhj9f3hqs448c988x4hcqyfe97urr00qhverqec22flfkgkgngs8awpkwjeez93mp0zuk7agmygmdrcy8z9zsp6z27sl8f3x6tsgelg3gf8tj86pedvp0etllw3qqyw6wpdq0fggq7qcv6xw6eghzdhv0ljkwwg5v9ahdsy5ngs6673khfhqr8ae7yggk29mhqncgttx966fhfvq329edcza827tgmwvnj60x6hg4qnz4stsnfncmk6m0t00czqrpzuskvm368yth2s9gev0k7g762h6gx6709sred9qp6gr0qes9jadv3d94pynkpjhwmz449ypfy3pdqvhhn78zj92p9snqqqxavz8lzk88mcjdkeqhqvz4dgffja78pe44cukue7vxwdfstwgj24p4632fmzmnfrevst44ssr42kz064ez49mtyjvxmegrdsvadv8k635qffefl42w90f56mn5g0ww725tlay8hsuvevth0uh8vjjfaagkygr3cp3xpjuc9rwc2nyup6df4pk669f256m3ny3s53s6z6ra3sr773803z6z6f70zdqd2uxd36xtanrszj8scq882u8djntyreylvn9gppfyr4xgf67e7at542222cvyusm8jchcqzy7xpuh6v88qf59cw7j5vmmx53q2cpvdgsxeeptyp9tq4pvxshkz9c9muv6lz5ttupxss43z4er7tnsdg42kfzy2qvtfsypfk7wqupv63kg9kfp30nyqcf02v8pd5gl0dzj02eheq35u8fxy705wmu9gp9ytptetz9yrdszzxmszac90un82sgvf42g4v4jp9f4a70gkazhf5vng2pct7z99ggh46lccwgvfjxvmwfz5ff8j5jmzrhpu9nzmtvr8x8evn82gl9h6p5gkm28uhurlwtg32uh8yst3zlq9xygwu2hcm32lj0f3h0kecvvd4m59gteyjs9zpelyj90k4p0g9jrsz5y8edjrhdzanrm353xd6hymuh2qu890k97dgp3ppds56gsza50ddcxve36xr3f4ft08dxlax5589nscuagaa8v0zcntf4d5asrzu8jknr42rk2y34mu54r0cjc0quy278yf657ez2nt33cr9qy3xesvx9uc60juwteuqvttec8knag9mv3q0d3jq9dau8cp5295m4dzjzya384k36rpjgl85r5weaqk60vlymnuugzpj5tyur3sxjds7p55ndjeflhu237zuu84fdpze2csnqzf3ak8q6qz7cjxsaqjhnv5y5ysp99w35u6rxs4u0f03ks7tv9de90cv5cca6sq2pfr6mv4nw8eu52qtp93dn4hgnzfven2r3lrpwelkr3mrpwn4wcrwcqjzytcuzse54ug9hdfnxn8f6edpqy9ztjwnp9mfy2w32keapqjk8dcvjd6n6yzkk2hry55d8cww4p74sdgwrghh84hx4wg57udyul3tmzpmfue7te9wtrxpn6gu287eu42xz2h3f88genu26030ve4nwvs0xcghmflvcjpp0sk5h9476vezhvp2k3kqyjvvt57qel7y8n4f70kn5ffna4m20x3pn2uy3d5c2ywqt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-22T18:46:49Z"
  mac: ENC[AES256_GCM,data:GUSJJOcow4XqgTVCT1N6hNGlLE+iKuR6r2xRqHfJx5AXePbAxdQqGyQtMO2ZZPLcCR0qHGsjinT7PjYGj5EORDhW9Cvv6GnH0FTANcTIV7MbF0GfF1sxCTin/YmzyYEmoW3XlxFvmt5UrvjQIVeXnIXyYJogdzQZqUZXyFSK/XY=,iv:LzBrZTorjr6g5T3laCKcOZgcWFWH4Xc9C4r5gwkbWio=,tag:Xi/OFTiY1p+KX58lNPrOIA==,type:str]
  version: 3.13.3
