---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich-server
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: authelia
    - name: cilium-gateway-system
    - name: immich-machine-learning
    - name: immich-postgresql
    - name: immich-valkey
  interval: 5m0s
  path: ./apps/immich/immich-server
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m0s
  wait: true
