apiVersion: v1
kind: ConfigMap
metadata:
  name: vaultwarden
  labels:
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/instance: vaultwarden
    app.kubernetes.io/component: vaultwarden
data:
  DOMAIN: https://wallet.guedescloud.com.br
  EMAIL_CHANGE_ALLOWED: "false"
  IP_HEADER: X-Forwarded-For
  PUSH_ENABLED: "true"
  ROCKET_ADDRESS: "::"
  ROCKET_PORT: "8080"
  SHOW_PASSWORD_HINT: "false"
  SIGNUPS_ALLOWED: "false"
  SSO_AUTHORITY: https://accounts.guedescloud.com.br
  SSO_CLIENT_ID: vaultwarden
  SSO_ENABLED: "true"
  SSO_ONLY: "true"
  SSO_SCOPES: openid profile email offline_access
  TZ: America/Bahia
