apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden
  labels:
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/instance: vaultwarden
    app.kubernetes.io/component: vaultwarden
type: Opaque
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:JvZzLOEFU4T/04oyMk82snZwYv5IGr1F+GLm6h9F/Wyxx9DpjtWq2DZ1O03OBnJr+gXfDAOS67Mdgd+cAc7QCehXLvlC6yBWcngzW9tKelwqG1odctsXDAbEnyIRE+TxTC8WOegirJlEwPbUmq0OJlhnzOKdeNpQ7U7MeX1fkF7nhnZluMJaF7Oh8eEH6JglPUClzDw=,iv:g+0fS8/HUnzrnfExt5An/jXfRBM6RlqIQe/PzuhgaIQ=,tag:8Z8w6s+Ljva/Eov9bLB0LQ==,type:str]
  PUSH_INSTALLATION_ID: ENC[AES256_GCM,data:s5ddvaeEOBnQAejtBoMJUOislqhvQn4mniScTkYRXWHVbdS6,iv:zoWcmUn9AoaB1EEtaRJApbooe5EwqMq79v4kvCH2xP0=,tag:I6BUcsL6v1sr/VsphQHUkA==,type:str]
  PUSH_INSTALLATION_KEY: ENC[AES256_GCM,data:Ut12BJ5m1l8HIePO5vFKrrtwctM=,iv:RZoh5OSnuWZk2OSfieTUvu3/u8xK+R/vXmEdMynF6S8=,tag:jQNckichPMk73ZwLkoLvVg==,type:str]
  SSO_CLIENT_SECRET: ENC[AES256_GCM,data:l6eL4g6O7ePD3ttRJpLcB1qGDQgwhJjN3DJDhtC7WThWNSc6MWwExv71HltWQsrwdGUB8nbpKH+7w2BW6dU7dw==,iv:QIBXhiCHrzmSfv63wBWHsrdCJ3Vgv0+QchQYI9kuR6E=,tag:+iuP0kg1Cc46OlfF3BP3nA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGU3OGNNY2hs
        WDFtMWVsSHljZW40dWl6N0x1b1ZXUzNtUXVIcXhEWW04QWNzemx6SlE4OXFLMnVq
        TW9BZ2NmUktZYkNTYnVGUzR6SGRpenNnbndpdnh3bHQyMVgvcmhVdVQ1b29oTzcv
        dElCK0NQcFR0eHJKbktqOW1kR1VOemVkOVorWVA4dlA5R3pEeUFadUd6MTlFMDY3
        VVlJaUhsMVlNb2FqK1crNHpBTmNydHZHOCsxN1NzeU16M1BDaW1LR2wrMlFrdWd0
        REJMRDNGbzZaQ2FEVHlaLy85bkl6NlBqWjFiZFduRWRPWDkyc3dXalhGUXE0dE45
        NytLTnVsdDZlOGVDaGVSZUg5Vll6dXFHUGhWOUc3UUlIbENnbmhNVHZ5NDQwTkVY
        RlliNHJ3MHpoVzI2a2Z3V1BSY3lXWnd5dUF2bDlrcUViZkZOR1BFODc2RFBwMWE0
        azFTeXI3U2VhY0RGdEJ4WUpqWGNBb2x6SjlsOXNTVDh6OEhEdWlpWG5xd0lYQzQ1
        S08yc3NzeVlKaHlMbTFWWVEzbmZJWklRMml5VGRtWUFLVHpqNVJldURWTDZFL1R3
        amxZa2d6WmpYMW5DeUJ6bXk3bXZvVEx4ZjE0Slp5TjUzSjBXaHB3NGQxVlAxWGpM
        ZXFlSGY1bXR1Sy9oL1A3V282WUtKTElhbDBBOHpSelh5anFhTHUrRmt5U1M3ajc0
        b1pibVJ2ZFFZZ0tJUHprSG1UN2dvVzNOM1FLdG40L0ZLakhveXNETGZSQ2JFOEcz
        VlNYWFBJL2YyM3pYS2lKWDEvNHVaSmNtMVdhTW9qd0tCZlpnblRpZWZ1bEtKZ2xs
        WG43dFZFZ0JlcmtFR25ES1J3RWpBWWloN29XNEg2bTgwTUZZRzJpUEFDVHZSVFgy
        cnBmdDl5UzNPV3pzSll5SDFGYWNlSFh1Tk5Wd1ZoN2dUeVJTTUd4aTlkNTVoUlpT
        NXJPdWRGMzV0YTd4OGl5WW83MGtkT2R0a0xQVmJoUjZSb09PWUxOWXFqRml1ZU9J
        NnZyalFGWGZPN01YM3pZSHJJYnZ6VjJWOEZnM3k5NTFnYXFPQTc1ZS9jdmVPYXgy
        UDA1SlFmREdNOHpIRjJ4aTNiNUg1alE4NDlLUDRpYTFQejd1RmxrdU10WUh3TVY1
        eFFXeGN6TnR6SGpGQ2VYclh4RGh4VWRoWmdTSzBydjBITENPYk80c2N1amVNellV
        L3pNa2ZzOGtpNEFrVUN3VU0veUVWS3NsUnRSa2t0eUgrS1FBaG1kS3JSODkzN3hZ
        YUNXOWVzOCtXbnRUbWsyaG5iODBLdDhJdVBFckV6L2dMSk9ER0tqTTdSYUdra0Uz
        dTFISjRnWHB1RkdoakxIR2Z4QmxRM09qTVBybkV0OVZDTHNtT0gzWEJnTm1yVFBz
        T0ZuYkFlZXdWelNOaUhNdVNwWWttRnVIUkNyUDRhaTFoeXhLM1crV3ZjYzQwUVlj
        d2NrdC9XNW1UcHdTdVkxKyswNyt0Q0VmRGhZK21SVVdnYzVRT1Rya242QWRacElK
        czhERVBJSVllaE1hM0FiLzFGYlNKNzk1dHpBem5OQnloN1JvT1A2RDRyN0lWVlVF
        VWxBNWJ4VFBkUXprd2YzL1F3MmRKTDkreVZBOGVJMVgvTzRTTGhZdHFVRHJZd1lY
        NXlFM3NDNGFscFI5cmZHNXVSTWp2WnJ5Z2pYS1ZwWGVXTmlKWDJWSWp4NlA4TlRn
        V2xFQ0dyY2NETy9lMnovaWgvakhnT3FCVWlwTU5LdElJVldqRjk0SkxaOGIvckRl
        dzZOWkJEUE1MTjBDV3VnR2ZHdlRJeUo2Nmp4dU5BZWNXbVBSOGltY29sYXpWTGhp
        KysrRlRiQkZCMW1yRDJyZXg2QXdGeUNmN3NSOW1IZHBJQzc0ZnFCZXNidlllTURo
        dUFEY1VMWEs0MG1iNFMyMzF1em5FQkJqV0hjZzJ4cVRhTG9FcmpjUWtMemlQdwpG
        VXZIU0FLTXZha2h6SmtoS0p3dHZhTVhJUDdPdDhNSjRNZVpUSlV6N2xRCi0tLSBo
        N0s1eVdtYU9nN3VyckFZQ3VHRm1sK0Zoanc1Ymw0ZFpzMkhCN3JIYXhZCpQQDHng
        +/s1q/rb6g9v8jR4mMyeMeE1g00oa08YHoFnfOoGTp/ieEmEsA3X3DrR7atTzYeM
        nk3ZmVSZjfulzxc=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1pcc952wp5r5svd72s6anpqzpth2m3lzzp7t5p072dxss4jeymjwrrq8gw5c7szx0lwtazuyvnlupq5n8zv2nxhq7yzwp34pkxdvnaj2u3evlddrkyqxrje255vefhhru9jzqe9z7yja78wgw5ffvlzlqcgrrsu5n0dpaxf9ra8gzdryyht90z4w45wa03keqrgfxyfmrsz30wz7dkgrhr6us499q2pnuj6pthq48qksqmqy8tlpnfv7qr2kswqycnsdal5srludhclg80enjvth6ngmfwmp82u3thdsjghge5zs77qqzm5as39v4e6mxz8lf8g0wg3ds6gaguhj9f3hqs448c988x4hcqyfe97urr00qhverqec22flfkgkgngs8awpkwjeez93mp0zuk7agmygmdrcy8z9zsp6z27sl8f3x6tsgelg3gf8tj86pedvp0etllw3qqyw6wpdq0fggq7qcv6xw6eghzdhv0ljkwwg5v9ahdsy5ngs6673khfhqr8ae7yggk29mhqncgttx966fhfvq329edcza827tgmwvnj60x6hg4qnz4stsnfncmk6m0t00czqrpzuskvm368yth2s9gev0k7g762h6gx6709sred9qp6gr0qes9jadv3d94pynkpjhwmz449ypfy3pdqvhhn78zj92p9snqqqxavz8lzk88mcjdkeqhqvz4dgffja78pe44cukue7vxwdfstwgj24p4632fmzmnfrevst44ssr42kz064ez49mtyjvxmegrdsvadv8k635qffefl42w90f56mn5g0ww725tlay8hsuvevth0uh8vjjfaagkygr3cp3xpjuc9rwc2nyup6df4pk669f256m3ny3s53s6z6ra3sr773803z6z6f70zdqd2uxd36xtanrszj8scq882u8djntyreylvn9gppfyr4xgf67e7at542222cvyusm8jchcqzy7xpuh6v88qf59cw7j5vmmx53q2cpvdgsxeeptyp9tq4pvxshkz9c9muv6lz5ttupxss43z4er7tnsdg42kfzy2qvtfsypfk7wqupv63kg9kfp30nyqcf02v8pd5gl0dzj02eheq35u8fxy705wmu9gp9ytptetz9yrdszzxmszac90un82sgvf42g4v4jp9f4a70gkazhf5vng2pct7z99ggh46lccwgvfjxvmwfz5ff8j5jmzrhpu9nzmtvr8x8evn82gl9h6p5gkm28uhurlwtg32uh8yst3zlq9xygwu2hcm32lj0f3h0kecvvd4m59gteyjs9zpelyj90k4p0g9jrsz5y8edjrhdzanrm353xd6hymuh2qu890k97dgp3ppds56gsza50ddcxve36xr3f4ft08dxlax5589nscuagaa8v0zcntf4d5asrzu8jknr42rk2y34mu54r0cjc0quy278yf657ez2nt33cr9qy3xesvx9uc60juwteuqvttec8knag9mv3q0d3jq9dau8cp5295m4dzjzya384k36rpjgl85r5weaqk60vlymnuugzpj5tyur3sxjds7p55ndjeflhu237zuu84fdpze2csnqzf3ak8q6qz7cjxsaqjhnv5y5ysp99w35u6rxs4u0f03ks7tv9de90cv5cca6sq2pfr6mv4nw8eu52qtp93dn4hgnzfven2r3lrpwelkr3mrpwn4wcrwcqjzytcuzse54ug9hdfnxn8f6edpqy9ztjwnp9mfy2w32keapqjk8dcvjd6n6yzkk2hry55d8cww4p74sdgwrghh84hx4wg57udyul3tmzpmfue7te9wtrxpn6gu287eu42xz2h3f88genu26030ve4nwvs0xcghmflvcjpp0sk5h9476vezhvp2k3kqyjvvt57qel7y8n4f70kn5ffna4m20x3pn2uy3d5c2ywqt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-22T15:14:29Z"
  mac: ENC[AES256_GCM,data:Eyg84ZqVtDpeXFU58ZPDB/8cunWokIEuJsYq9nhucPrYJukl1C8mN00S+FDW/i6jDxmaxSUbPY7OHjw1gxWFseDUyzjOV5oKPaDW6Vafi784jTP7U8LM0QOAQRMkMh5HCl70Pk0IjKIhtNJtPQi5uiGsGSKvC2CnEe1hBynVybU=,iv:dbt2niD50JvuU0VWRXua97mnmWQse+ZxoLf00x4mOT8=,tag:98kiIwN9d7engOyq6oJmAQ==,type:str]
  version: 3.13.3
