apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: audiomuse-ai
resources:
  - configmap.yaml
  - httproute.yaml
  - scaledobject.yaml
  - secret.yaml
  - service-audiomuse-ai-flask-headless.yaml
  - service-audiomuse-ai-flask-service.yaml
  - service-audiomuse-ai-worker.yaml
  - serviceaccount.yaml
  - statefulset-audiomuse-ai-flask.yaml
  - statefulset-audiomuse-ai-worker.yaml
  - triggerauthentication.yaml
images:
  - name: ghcr.io/neptunehub/audiomuse-ai
    newTag: 3.3.1
    digest: sha256:c89d17a3584a37a4da0cc0427fffc20a80680e78046d1ae6b0a27fa8af98fb90
labels:
  - pairs:
      app.kubernetes.io/part-of: audiomuse-ai
      app.kubernetes.io/version: 3.3.1
