apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: audiomuse-ai
resources:
  - configmap.yaml
  - httproute.yaml
  - scaledobject.yaml
  - secret.yaml
  - service-audiomuse-ai-flask-headless.yaml
  - service-audiomuse-ai-flask-service.yaml
  - service-audiomuse-ai-worker.yaml
  - serviceaccount.yaml
  - statefulset-audiomuse-ai-flask.yaml
  - statefulset-audiomuse-ai-worker.yaml
  - triggerauthentication.yaml
images:
  - name: ghcr.io/neptunehub/audiomuse-ai
    newTag: 3.4.0
    digest: sha256:25b104373db717c4465d44e1125fc35c589af9eff97f44b578c1c6923ec55b1f
labels:
  - pairs:
      app.kubernetes.io/part-of: audiomuse-ai
      app.kubernetes.io/version: 3.4.0
