apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: audiomuse-ai
resources:
  - configmap.yaml
  - httproute.yaml
  - scaledobject.yaml
  - secret.yaml
  - service-audiomuse-ai-flask-headless.yaml
  - service-audiomuse-ai-flask-service.yaml
  - service-audiomuse-ai-worker.yaml
  - serviceaccount.yaml
  - statefulset-audiomuse-ai-flask.yaml
  - statefulset-audiomuse-ai-worker.yaml
  - triggerauthentication.yaml
images:
  - name: ghcr.io/neptunehub/audiomuse-ai
    newTag: 3.5.0
    digest: sha256:244bb151e3aa1a39730be82d92f93e90f8ea0ca79548ba6bcc8aa6dd344eebf6
labels:
  - pairs:
      app.kubernetes.io/part-of: audiomuse-ai
      app.kubernetes.io/version: 3.5.0
