apiVersion: v1
kind: Namespace
metadata:
  name: audiomuse-ai
  labels:
    app.kubernetes.io/name: audiomuse-ai
    app.kubernetes.io/instance: audiomuse-ai
    pod-security.kubernetes.io/enforce: restricted
