apiVersion: v1
kind: Secret
metadata:
  name: audiomuse-ai
  labels:
    app.kubernetes.io/name: audiomuse-ai
    app.kubernetes.io/instance: audiomuse-ai
    app.kubernetes.io/component: flask
type: Opaque
stringData:
  API_TOKEN: ENC[AES256_GCM,data:E2BfUG5uP/+0ACQI6sIuKl2LMY+v6lVVktgTeBsPic9FbIobk+xfJVPPoMjOMOsnx62ooW07jxNyY1W6QpnImw==,iv:R/lqQxFSV5/6NV/4M5mVE1QFiT7x1GOu15sVgvR3cps=,tag:b4htwzbOeEBBUllLy8300Q==,type:str]
  AUDIOMUSE_PASSWORD: ENC[AES256_GCM,data:PQnBfxOlZfOPTuljA0XEH5vo/68=,iv:KmaPkARm8smdzRTMEC4wyanQjXHyIdaWmW+tRALWDUY=,tag:irRRYGoChpz73/uLT+EzVw==,type:str]
  AUDIOMUSE_USER: ENC[AES256_GCM,data:dwRwRx+4+A==,iv:NH9LsxE/2d5QXpUXjiaF513gyBoX0LukTOiWk1+qjZU=,tag:ly89H6x3Wnrh/b7Z49/huA==,type:str]
  NAVIDROME_PASSWORD: ENC[AES256_GCM,data:Ohfqn6UfY6/g44ygr7+BGCY9mvM=,iv:WeDj2EA6Ipf2/3tXDY8scqAIVro0gXkhAEjjeuy6hqE=,tag:13Cu8TbGWfSXgUXEj4GRgQ==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:rjZrDPXl53on4aXtVcCs+4CGnsGqU+YQMbjoLEHpzBySot6A5aKl23emwgZebSjWhAHNDpy2Laiu9z242kWlAA==,iv:DI+aaBoX7EngOmc/+BNl79TsdollVfqnJCkRbo4RKSg=,tag:9czHuNb8Xjh11Qrk24qaHg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHplQW8wQWla
        VDdJM01xYVQ3cUdvNklVemRFdEplSUIxQWprb0l6OHRmSDBuc29GeXlNRUl4cExC
        STFrVXh6d2dQNE5LQ3l4MGR6Z1dXQldKRGl3dkZ1MSt4ZW1ZQkZnYVY4S2p5dCtB
        Sm4vc2t4TGZxbk5oMFF3M2czdlZPWUovN1UyNWRHaVk2cVNnWU1LTWRESnloU1c0
        L0ZsTnpUaVBZVW1FM1VCam50cnlEcGRTQmR4aHhsb0Jsdkh6eU9MWUJxc2dCdUhD
        czhjbTNxeHp6OEtkU2R1TUkvQUNJMWF2Zzl1amZNZVRsTjVsdjdFR2dqc3F1aUlR
        eHVQVVpCdmVUUU9uRHRTVFMrczVzVk5XVFBSTkhCVHFObit4a1VWQVJoUVRqaVlu
        YitxcnI0d2ZDVWlRZjJ2cTAzQnVrVWozbVp3dzZOZzlqQ1IrVVdZYkFtMktKQzV0
        TG1RN3M3UnJiYStROGlPVVFZRjUrSDZ0d3RJeGUvZ1RjTElQaUNlcy9hekJ0Mmg2
        eGxjVVd0MVRsL1RsNlJQL0cyRFZvTjN2eTl2eTRjZnZvMTd3dkkxTHd0NW5DYlFM
        Z0pwLzIvTS9jaVBFeFdwZFZkSC9qVWlCK09zV1hEemFtTTBxdFVnVFNlell5OFFI
        NlFnTHA3STJocURCd2J0YTVvTnhiSW5MMkRPOWhpcnREbk5zNWNLTDErTWtVWExX
        RmxMSFBoa25qWExLMHUrWFJDOEZnOFZaYnZWZ2orWG5RRjI0OTVUN0FOdUJyb2VT
        NEVRUnpBVzhkYVVjVzFZekhlKzZGMU02bE84VnRtaHIxU296R1NOUHZSMHRraTJW
        UnRyN2M0L09wOHdZMjRLRDRXVEtnazhCQlpNTGd4WUY3cXFMQTZvc01Qelo3Y0lu
        dEthSmlzZ3NWZnBGV2EzZGpjK0NMcExRL2dQNkZsT3A2L3lxMG1TMFdvK2tmbUNU
        MS9BSUxMZ1U1VEVmS0JWTEoweUxBT2lBU1EvL0QvRWtiQ2NPOWMxekFIcjM4VElu
        d3RUcDVXbHBURjdCQytIMU96NGpEeUljKzVkK3Y0TlhoSHg1YXVjb1o0L094blBM
        ZnJrSCttVllVcUZ5aUVaSnlqbVI3OHNRMk5tQlRnSWNHR1RXSE5VeXhUYmdVdGd6
        SkQvOGxBYjVGNk0zSlNSbHZiVnNLdVpLVzNZUkFRZURiS3FibVQ1OXNzZnJBaUxz
        Y1NGTDdtUkxYKzlJZmR3b1VZSVF6enJCSlkyNCtuQ3EraUNveFRwN2l5cUM1WWJr
        V1FEcU52YTdLaWwyMEdMRm5ocStZbUtOU3pCb0xIZFUva1A1VEtrNnRBRWcwSEUx
        L2tOSThONUp6T0dGakg3NVZsckliM2w2eVZ6RE02aU1xbXlKQTBYWS9PK1FRL3Rr
        MXZqUGRFNk0rUVhWTWZQMnpTQ3lpME5VTHRCdkQ3QnBUeXAvRlBpalFsVWd6cWJj
        UXRUUS9aWFlxY3BTZkFXMzNFU2xvOUx1aU5JbHFXbjlyNzRYZVZ2WE80U0FiWkxQ
        RExmdXo4dWhrUWVhYnhyUXVDamo1YjV1QlB2YVR3ZEpEOWlRR1JOMjk0d1IyNW94
        T2ovOFlObzJhYm5EY3I1YmxHQWZVcjdkVkJsaG00bFViZU45YWpJNmtnSjdJNHVh
        cFFjWWVBV1hvbFlzRnBpK0xST0xFZkc4TWFQbEM0VlloTTUyZWRQUGFaSEVUUUlz
        V01nZnJxNTVoOENGYkdIUERRMUlGTGpCajNWUEw1MmQwZTFNVk5JRFhVWnpjSExp
        QWxyWUJrNGNIN1ZNTlNpOUVOTFRKbmFrSGhYSlA3MGlIdVNYdTBYcTk5RHlWa1pi
        UjNLMGhNOEl5V2FEN0ZIODAxR0h2NkZvYlBiVzlVN2xYUm9TZUM3alFUWFQ4enpU
        dHRSajV1em5XbXlsSGl6dUlwa2RsK3RRaEMxVzNaYndnUHpJSlorZ1pBTkZSZwpE
        MVN2MnRmSWZRTDJPZ09RblZ4MUV1c2tPTlFyaEwwbndtRGN6RUJzYnk0Ci0tLSBk
        SUEvRTVNR013VTM3cVIzSVlhaHFGWUhDcmNhR0czZnR6dkVEdjZ5ZkNZCmb9r58E
        qZpchFWp+cjLccTnDyaS5g//0MpciXicsjjwbF45TLtrpms2X9v5oVjMpOkAuq7h
        Tnm8I/g2mHKQyps=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1pcc952wp5r5svd72s6anpqzpth2m3lzzp7t5p072dxss4jeymjwrrq8gw5c7szx0lwtazuyvnlupq5n8zv2nxhq7yzwp34pkxdvnaj2u3evlddrkyqxrje255vefhhru9jzqe9z7yja78wgw5ffvlzlqcgrrsu5n0dpaxf9ra8gzdryyht90z4w45wa03keqrgfxyfmrsz30wz7dkgrhr6us499q2pnuj6pthq48qksqmqy8tlpnfv7qr2kswqycnsdal5srludhclg80enjvth6ngmfwmp82u3thdsjghge5zs77qqzm5as39v4e6mxz8lf8g0wg3ds6gaguhj9f3hqs448c988x4hcqyfe97urr00qhverqec22flfkgkgngs8awpkwjeez93mp0zuk7agmygmdrcy8z9zsp6z27sl8f3x6tsgelg3gf8tj86pedvp0etllw3qqyw6wpdq0fggq7qcv6xw6eghzdhv0ljkwwg5v9ahdsy5ngs6673khfhqr8ae7yggk29mhqncgttx966fhfvq329edcza827tgmwvnj60x6hg4qnz4stsnfncmk6m0t00czqrpzuskvm368yth2s9gev0k7g762h6gx6709sred9qp6gr0qes9jadv3d94pynkpjhwmz449ypfy3pdqvhhn78zj92p9snqqqxavz8lzk88mcjdkeqhqvz4dgffja78pe44cukue7vxwdfstwgj24p4632fmzmnfrevst44ssr42kz064ez49mtyjvxmegrdsvadv8k635qffefl42w90f56mn5g0ww725tlay8hsuvevth0uh8vjjfaagkygr3cp3xpjuc9rwc2nyup6df4pk669f256m3ny3s53s6z6ra3sr773803z6z6f70zdqd2uxd36xtanrszj8scq882u8djntyreylvn9gppfyr4xgf67e7at542222cvyusm8jchcqzy7xpuh6v88qf59cw7j5vmmx53q2cpvdgsxeeptyp9tq4pvxshkz9c9muv6lz5ttupxss43z4er7tnsdg42kfzy2qvtfsypfk7wqupv63kg9kfp30nyqcf02v8pd5gl0dzj02eheq35u8fxy705wmu9gp9ytptetz9yrdszzxmszac90un82sgvf42g4v4jp9f4a70gkazhf5vng2pct7z99ggh46lccwgvfjxvmwfz5ff8j5jmzrhpu9nzmtvr8x8evn82gl9h6p5gkm28uhurlwtg32uh8yst3zlq9xygwu2hcm32lj0f3h0kecvvd4m59gteyjs9zpelyj90k4p0g9jrsz5y8edjrhdzanrm353xd6hymuh2qu890k97dgp3ppds56gsza50ddcxve36xr3f4ft08dxlax5589nscuagaa8v0zcntf4d5asrzu8jknr42rk2y34mu54r0cjc0quy278yf657ez2nt33cr9qy3xesvx9uc60juwteuqvttec8knag9mv3q0d3jq9dau8cp5295m4dzjzya384k36rpjgl85r5weaqk60vlymnuugzpj5tyur3sxjds7p55ndjeflhu237zuu84fdpze2csnqzf3ak8q6qz7cjxsaqjhnv5y5ysp99w35u6rxs4u0f03ks7tv9de90cv5cca6sq2pfr6mv4nw8eu52qtp93dn4hgnzfven2r3lrpwelkr3mrpwn4wcrwcqjzytcuzse54ug9hdfnxn8f6edpqy9ztjwnp9mfy2w32keapqjk8dcvjd6n6yzkk2hry55d8cww4p74sdgwrghh84hx4wg57udyul3tmzpmfue7te9wtrxpn6gu287eu42xz2h3f88genu26030ve4nwvs0xcghmflvcjpp0sk5h9476vezhvp2k3kqyjvvt57qel7y8n4f70kn5ffna4m20x3pn2uy3d5c2ywqt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-22T15:14:29Z"
  mac: ENC[AES256_GCM,data:fkPq8OE4J7XyNSnxGZqXTQ0xG8SZn5CDE8P20bLGUiCOsHL2xIQN6dcNA2mxMHTI+psb173xtcrD8dE71ksfDoFr/7vMOA2GGtvxGvpM06h2rZERJdOcondTrmiS1xDx63KtgXbTYae0BleIruGhNXcUBzngUWwAldXThMZ30Zg=,iv:xPZTon3qRIt3Fx0zsqfwNNluUyq9M/a3vlNKAoxiUvM=,tag:jGLujxz6qST7TXviQXYUug==,type:str]
  version: 3.13.3
