apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: audiomuse-ai-postgres-auth
  labels:
    app.kubernetes.io/name: audiomuse-ai
    app.kubernetes.io/instance: audiomuse-ai
    app.kubernetes.io/component: worker
spec:
  secretTargetRef:
    - parameter: password
      name: audiomuse-ai
      key: POSTGRES_PASSWORD
