apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ollama
resources:
  - configmap.yaml
  - deployment.yaml
  - persistentvolumeclaim.yaml
  - service.yaml
  - serviceaccount.yaml
images:
  - name: docker.io/ollama/ollama
    newTag: 0.33.3
    digest: sha256:32931b46719f673c05fdbaa81ccb26da18ea4a1c57590a754874ab28ba269eb2
labels:
  - pairs:
      app.kubernetes.io/part-of: ollama
      app.kubernetes.io/version: 0.33.3
