apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ollama
resources:
  - configmap.yaml
  - deployment.yaml
  - persistentvolumeclaim.yaml
  - service.yaml
  - serviceaccount.yaml
images:
  - name: docker.io/ollama/ollama
    newTag: 0.33.1
    digest: sha256:075246f72d4109385b4a01c3ac8e9cbd26a0bcb21cd7aa30edbccd24e1b3180c
labels:
  - pairs:
      app.kubernetes.io/part-of: ollama
      app.kubernetes.io/version: 0.33.1
