apiVersion: v1
kind: Service
metadata:
  name: ollama
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/instance: ollama
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/instance: ollama
  ports:
    - name: ollama
      appProtocol: http
      protocol: TCP
      port: 11434
      targetPort: ollama
