apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lldap
  labels:
    app.kubernetes.io/name: lldap
    app.kubernetes.io/instance: lldap
    app.kubernetes.io/component: lldap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
