apiVersion: v1
kind: Secret
metadata:
  name: lldap
  labels:
    app.kubernetes.io/name: lldap
    app.kubernetes.io/instance: lldap
    app.kubernetes.io/component: lldap
stringData:
  LLDAP_DATABASE_URL: ENC[AES256_GCM,data:+KVgSg/qS8LJW0zjfaCkSHECRCDAi8ETOo0bgCyZ6TlH7kYUETXfdP2ELYVHmHWhStdnJ1GyQmpyrd1ttH9ZkU++I6Eh+OHZBAlLj3c3BZKfb5sjv/o99E86VQT2MeXL0tWrAdzpdL8iFTP3O1vK1S5CG0WAnLIXjjmZ2vWjs/v4Kl5eDoxK,iv:7R7sMq3Vbqklkn8LdGC94rOSMHvjUmf0zhkGj748Y68=,tag:M521Anfxdkcv3BjwLVT3oA==,type:str]
  LLDAP_JWT_SECRET: ENC[AES256_GCM,data:thLH4e/+MUy9bb0+o34hhRstPnhNp0UbIv6mpEDIDCDDe+m63QLdxbK1r7s=,iv:KgDLXOpLYx8s/az0wbFvamqBm5umOuypOPhXXlCaxRo=,tag:RHtiK1oxhNHifSpPzu3arA==,type:str]
  LLDAP_KEY_SEED: ENC[AES256_GCM,data:4k8VePOPM0QDnmizlabdTmRxHAs5R9UW9SdzvygNXtXZ55J37P0YjmTPpXE=,iv:oeqkEffY5o/XCScAYA8ivP9ZZhriDA/oEP2LhuVSoDs=,tag:YUl5crvE54qN+cDt7OJZvA==,type:str]
  LLDAP_LDAP_USER_DN: ENC[AES256_GCM,data:SPZ+DQs=,iv:Dw2axFiH7Tzd4sjuboz82HZR3ggKHPh2qxQFChGVAnY=,tag:DyjvGxi22FvYgFo4rNdCVQ==,type:str]
  LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:Cik4lFfB0L0gEdLH0lYwu5TBUrw=,iv:Icde/cYf5O64sCT3plbvUe6uMO8YCC31GHdjHVG6UV4=,tag:AyrjUh8xtCx6Ig4wcGnB6w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGpjdTA5TGk3
        MEg4R3lyWk85VFNHYUswNmtRMEFDZWhBQjZkbXJRT1RzN1FyZWRzaTJ6RVRudlBD
        NjZGZkM4Z3h4eXErWVdhT0FkTjl3QS9mR0JsTHJ3Q3dBR1JGRTNXZnJZV2JyY0lP
        SGdTeVZWZXU3bFkvUG0vWUl2czZ1SlVVelVkbXZtT0liWmg3UmhzVDZBaGZaeFZO
        V3hudk5neEFOSG9lTmhnL2RoU1ZwVTJlUUwyQ2xQWjhDa1NMKzFqbXNiWnZ2S0cw
        cWswOU1MVDBCTTJabkltMVB1anJrdThzVTBXakNXVmxWcGtrOGwvMlpGT1JrME5Q
        K2RIbUgvVXhuWU5wREY0MU5wcTRRZG5aczkzZ0V4QTRQM2hoUU05ams0c0NJb0o3
        MFlIeUlzZDEzOVlJNUU2Q1UxWGowb2did0FrNzhXNDBqSklwRm5nd21ZemdwaXJC
        bGFITExOcWdpcERZZ3hTVW5GT085bERpSnptM2lSR0hHcDNDemptdkVuOUNyYVlV
        ZVhtMkQxeGFEcFF6VnY5b1IvZEo5disrN3NzRUQzSElmRU5UZGxDVGZ3YlFWOHNE
        TUxwZTBxNHBsRnRUeGVZTFRmMWVwazZUa0t2TFVsQWpFU0U2dDR4dDArTW5RMU1n
        YlFhazg0N2dYdVdUVlQzNDU5ZDlBY3VYNGxmTVEwNWpyR2hhY1drV2t1Zm9IT3ZG
        TzhLb2VlMzJyTDNXb1M1WjlqRk5oanJLV3RLTWpEdVJ2V3BzbE01em51TUM4bmVx
        bnJjaHllQlZNckJ4bkZ3ZFZqYUd4dGZYNUVFMGlneXBUSFJGTkxhOW1MYVVFVFBy
        OXkrYWtBRVdWSTU0ZnI5a1ZVVFJ5WHhTUFhoeDRDRW1taWpKRStQanVTUkdkNGhM
        ZlpYWUpzbHcwZkxFRDU3UFg2T0dWU1ZmVnRWcXA3Y2FsYS9DSkFKTGdOU2VQY0dp
        RFpTUFJ2RU1sRUhVbUoybUtja0dGQVBVZmpSWmdvNERIQjZzK1ZJTDJibkd1M2ZD
        K2xlMXhGOTRLcExIRWk0bmFDbnBaaTRvdEJ6QTMxM21Zc3dOK0xaSElXMDE1dE5B
        QjlvclpJa2oyRFE2MGxqL2Q4NHRKSkE5aEZITWZ2QXA2MC81ZW5RSVZMV3BlM0d3
        V3N0dk5QM00zSkVWQ1dkRFRzdDNaNldaSVdGN09Xc0l2TWU2aVlYZDBvKzVOaWFY
        NThNSU5hV1FpUURzSTNOcHZxbytyVW9kMzlRaFRVS0xFNTUzMTRidW9RRG1hczFx
        RFpET3ZCdnZpQVZuV1Via2RyQXhlUTNOdlN2Uy9rTy9DMlJIQjlDbm56dmViN09u
        bFdPeHRWTkdoclJDaWRMUUJMR1NyVHB4WkZiRk44b29IbVk2TmU5dU9PRFV1T0xJ
        dFU5RWVlTG5uTDN3aU5Zb2JMcCtZVjUrV3RROWVCQ1VwNkh5c1M2cUhrd0tqL2tR
        VzF2amwxUDMyMjRwTGN6c1hrTVRwbVY5bmREZXA4b0tNOVdWZUpRVWh4ZkY0cTRP
        TEZsK1hQVlN6WFlLSE9QTTJQaHpYRURnVDlhSC9OeWkyWGRyVnRueEtlcHFLSHVS
        SHJKUE04ZzJxelpneTBPSnVmcUlLNCtsN3dyclhhVW1MSGxaYkswMlNQb29sREM2
        b25zUHYrSTZKZTNkUzVlL0RkeUk5RlJ0Y251ZXg1WVFYQ3NTL1k1OWt2SjBhT293
        RTI3Zy9wOTRIdEZBbm0xbWNLYUpta0RtUFhxdGZ6dUdtVVBCcUxtY0ZWNy9pN0Z2
        bkswSU5JV0lwaU9PQ0dIMExaZU1WQ3ZMS3VDQy95NW5uWWtyTjJzSVVDa3ZQTWQz
        RFhFSTRKUFhpVkphTzRLZWxNejBNbHVSNk9mSFBDbDJZbkFnN0RNeHRIWmcvdW8z
        RWFmRDJrc1l1Sm1VenVNK0JGYjArdC9TRndiV3NUR2pIY01HOTd2S1VndU1ldwpR
        SVprY1FncXpGVDkzOEtCaDl3SElydUYyU0daR01waG5GTSsvTTFPbzQ4Ci0tLSAy
        SXYwT2d6TkFETXVxZjNkTWhjcTJpYndxL1hzRlBhQ2ZkUEltYVg2RnZrCicJ/VvH
        uziwt4hRGkRZli3r0Emg4990Cn/Kr6VSc9tW2TMwGRMWgY6EKuGPxNunDM53VxE3
        advD5s8BNroJiAY=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1pcc952wp5r5svd72s6anpqzpth2m3lzzp7t5p072dxss4jeymjwrrq8gw5c7szx0lwtazuyvnlupq5n8zv2nxhq7yzwp34pkxdvnaj2u3evlddrkyqxrje255vefhhru9jzqe9z7yja78wgw5ffvlzlqcgrrsu5n0dpaxf9ra8gzdryyht90z4w45wa03keqrgfxyfmrsz30wz7dkgrhr6us499q2pnuj6pthq48qksqmqy8tlpnfv7qr2kswqycnsdal5srludhclg80enjvth6ngmfwmp82u3thdsjghge5zs77qqzm5as39v4e6mxz8lf8g0wg3ds6gaguhj9f3hqs448c988x4hcqyfe97urr00qhverqec22flfkgkgngs8awpkwjeez93mp0zuk7agmygmdrcy8z9zsp6z27sl8f3x6tsgelg3gf8tj86pedvp0etllw3qqyw6wpdq0fggq7qcv6xw6eghzdhv0ljkwwg5v9ahdsy5ngs6673khfhqr8ae7yggk29mhqncgttx966fhfvq329edcza827tgmwvnj60x6hg4qnz4stsnfncmk6m0t00czqrpzuskvm368yth2s9gev0k7g762h6gx6709sred9qp6gr0qes9jadv3d94pynkpjhwmz449ypfy3pdqvhhn78zj92p9snqqqxavz8lzk88mcjdkeqhqvz4dgffja78pe44cukue7vxwdfstwgj24p4632fmzmnfrevst44ssr42kz064ez49mtyjvxmegrdsvadv8k635qffefl42w90f56mn5g0ww725tlay8hsuvevth0uh8vjjfaagkygr3cp3xpjuc9rwc2nyup6df4pk669f256m3ny3s53s6z6ra3sr773803z6z6f70zdqd2uxd36xtanrszj8scq882u8djntyreylvn9gppfyr4xgf67e7at542222cvyusm8jchcqzy7xpuh6v88qf59cw7j5vmmx53q2cpvdgsxeeptyp9tq4pvxshkz9c9muv6lz5ttupxss43z4er7tnsdg42kfzy2qvtfsypfk7wqupv63kg9kfp30nyqcf02v8pd5gl0dzj02eheq35u8fxy705wmu9gp9ytptetz9yrdszzxmszac90un82sgvf42g4v4jp9f4a70gkazhf5vng2pct7z99ggh46lccwgvfjxvmwfz5ff8j5jmzrhpu9nzmtvr8x8evn82gl9h6p5gkm28uhurlwtg32uh8yst3zlq9xygwu2hcm32lj0f3h0kecvvd4m59gteyjs9zpelyj90k4p0g9jrsz5y8edjrhdzanrm353xd6hymuh2qu890k97dgp3ppds56gsza50ddcxve36xr3f4ft08dxlax5589nscuagaa8v0zcntf4d5asrzu8jknr42rk2y34mu54r0cjc0quy278yf657ez2nt33cr9qy3xesvx9uc60juwteuqvttec8knag9mv3q0d3jq9dau8cp5295m4dzjzya384k36rpjgl85r5weaqk60vlymnuugzpj5tyur3sxjds7p55ndjeflhu237zuu84fdpze2csnqzf3ak8q6qz7cjxsaqjhnv5y5ysp99w35u6rxs4u0f03ks7tv9de90cv5cca6sq2pfr6mv4nw8eu52qtp93dn4hgnzfven2r3lrpwelkr3mrpwn4wcrwcqjzytcuzse54ug9hdfnxn8f6edpqy9ztjwnp9mfy2w32keapqjk8dcvjd6n6yzkk2hry55d8cww4p74sdgwrghh84hx4wg57udyul3tmzpmfue7te9wtrxpn6gu287eu42xz2h3f88genu26030ve4nwvs0xcghmflvcjpp0sk5h9476vezhvp2k3kqyjvvt57qel7y8n4f70kn5ffna4m20x3pn2uy3d5c2ywqt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T20:02:43Z"
  mac: ENC[AES256_GCM,data:CiXJ3Y+B960gJq0QDIxL/NTO8wAHlV92B1DWGJyPOAL/oVEVltkubD2s/y1ZGWvGSZShmi4j7xUyOrr2Z02MCBV3/Hpnzb0J5vwUZe5t56Cvva3eayOknVUjv0eBQ2fX92qvUiYwN/+RzyAN3lf414O08IaA34bjF0YlY7iFbF8=,iv:fwWPsR3IrN+jPaMagfwFchBR/tIr0y/6gJGX4MPTfLI=,tag:6gWzJhfrj64GQn2Vua6pkA==,type:str]
  version: 3.13.3
