apiVersion: v1
kind: Secret
metadata:
  name: lldap
  labels:
    app.kubernetes.io/name: lldap
    app.kubernetes.io/instance: lldap
    app.kubernetes.io/component: lldap
type: Opaque
stringData:
  LLDAP_DATABASE_URL: ENC[AES256_GCM,data:1RoVvrnJlILBkmyp1eflunnuC50KmvbLaxt6vVDVRBKLCu0FiRKXKpFs5pp/x1FjhlPaRw+BZSGkmv9WSGe84YXttZnO3YHwTdopLU2HYcwrypONjLMNI9IL9jAvYaZW9MXpm2xDTyrJUAKTsoHryFLih22/HV+K2mBeDm/41z+gAyaFZaDT,iv:EltROSJ6x8pBNNY/k7d8V5nm7LNhxUBv3MhlPVxhyME=,tag:hLoNTorcZe4OSJFuLaj/tA==,type:str]
  LLDAP_JWT_SECRET: ENC[AES256_GCM,data:kD8AN95WrcFJl1mGlRa9Qg/O9kfUa9Lsx58Vf3mrlEuO17mkEAtM4JztdmQ=,iv:i3KmyX721aapve4eW4CbMeKkS4NorvUmzIzTg2cZZPM=,tag:JeSPnh//suzEYAFOtw62lw==,type:str]
  LLDAP_KEY_SEED: ENC[AES256_GCM,data:rIR/981N07y1oubg4WneturdAomvBdoNRFq4fGPOJ+VRJ8qWIH7e3eKFjhk=,iv:+5crfigx2q8d3tNtM2W2uhwAkkbmVYCVyesRmZC0Ck0=,tag:QBqjETQHZa5SWEDzthQS7g==,type:str]
  LLDAP_LDAP_USER_DN: ENC[AES256_GCM,data:/l94BoE=,iv:HL2fL80Us7vpKI8mMBzzuoEcPfeecXjMOC7ivxKtwoQ=,tag:UQO3fJAYn2BnrQi+E+6Now==,type:str]
  LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:aUkPVYJ9V4S0LtEPyfFoVAe+TQk=,iv:FDF0zCoHfUnfeqBZIvoI49yU4zpyQT25tGCLfNnCQ+g=,tag:DtbQnwgXqLI9U6UG2Xx9Jw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFF0ODJLNnhN
        dnZJd3U4cW1kRFVhaEYreHMzcHBiNDBCdmtDL2p4aGlRYmwvNytjS0ptdkRIR3hs
        ZktkcmlaTXhyOTdCcTVYY00rVGV3MStYZllxckpSUjk5UUNJSFUyWTcrbVNYMnVR
        NmlQT2oxOTdVd3Rqa2FqcDNtdytSQ3dtam15bmo0VlorTUxMM2srakNTZmtkMUxa
        ZXFFWVlIS2RCQzRSM3VJVUR0elFwNm9QWTVqS2o2S1hPQVl1b0drTThXNmZkVTFO
        empMRnFpbXpKdjdiMUROVlNqYTNkcWovamhnQTRRQ3phREN3QXQyeVBIcmNWaFhm
        eUdYKzlXaDIwblVLSmtSSFh0SHJtVlI5UFcvbjI4WGNvTlpGUFJQSjFWa2FNRGJi
        M2hVSUFUWFZ5N1J0TktBdWVOdTFTSmJQN0pnTTQ5UmRwK2pVOUdma1J5cmVadm01
        VURoVFltUTZxVnRnZS9DOVBHVXp3UTNqSHN6Rm5lUGNiQ0pkK0FCSmNsUXpiS0Qv
        NFVIUUo2VUdLWVJqbWFMSk5nbXRHK3lWUCtlU3d4b01xdW55azUvdFZDcUxYUExJ
        L0tNWmZuK1BtM0dyaURlZk01TFhjSDBzQnlxaEQxV3NIWUJqcWFTVEZrS2cwK09t
        akxINmtBajJrRHdKVVdkbFYydDRWNUdGM0laRlNmdVM1YWJVUEpydjYwQ094OFFa
        ejVERWRva1JCcXVZcFFDdmd0dFhmY1FoU3owTEk4N21tZHVFdnRNVmordFVjR3cz
        cUcvcXoxMU5DeGVmdENKdzJkZmlHd1F1V1ExMWZITU5OdVJJNDhSZ2ZWQjR0Wnln
        Y3AzRzR6WWx4azU2Z2laNmNXT0JyY3B1algvQXlqSVgyQVUrbmU4SEhILy84T29C
        TGlmUFgxYm8ydkFzTGtYNG1BLytLT1MwWi9IMmlPQUc2SWdOZTErRE43TWkzNDI4
        eUtMTjE5WXpodzNYbzNaNWFCek8yYWhjM1ladXY4N0MxL3FUZzZ3R0ZQWjdDamVD
        cys3U3dXaTVFS3JHRUZCTmlHL1czbEw0K2k5aTM5dU5DMitqMk14emh2WEtpbS9J
        bUtjQzR1eGxDZ1ZmT3FVLzFVdWpsWlV3YlhZMkJDWEVyRERGSjdaa2FoRVhidzNs
        SUh4ME8rbkVqelFOWEEyeWsrTVF5UVMxL0NEbkhqSGozcHNFOUIweWxmaFlUNmRq
        MWY2NUlRNFJOZERxcTFENjJkOXJCN2kvdDQrU24vTTg4YUZqZ0o4MFdHWkhZRlo0
        dm9vK04yVGxjMlJBOXNNUlA0Q2V0YnE0TUtKZTZwZU1BaHo2am9aazA0OUxCeW5S
        MS9Zc09ydnJUcHFBRjZBMHBKL1NEZjVONWZ6RHVVbmZhbjRtQ2ROSzJjM2lISUVT
        Slgxd1JjUEtaWm5YeTlTYUU3VkpTNTJ5UW1EOVdwSFBRa2Q2UGZ3Z2Ryc0drbWNr
        SGlOaExIN21XaHRHNytiTzM4TmRUUXZyWkFwcDB2ZE9vOW9td2trWFVkVm1JUmEv
        SFgzdkp0OU1HdTl0Q0ZtMlpCTW1NekdYR1VzU0g5RlJoSmJ0MnRhbFZoZXdmWjVj
        UDNESG9XQ0wwbHJvaVFCcFFCRTJtMnY3Q01HTTdOSE5UakY2QkdUc0ZEQzJkUzJ0
        SHlSdVVSUUpFQ1d1MVpNREFYSWEyeGNHZ2lQczdhRnIyd1lBUWhmQ2pPczJCZUFM
        ZEZybmlVRnpnUVVJRE5mc2RxWVZnYWUvczRSSkZZT0J4QW5yRGkyS3ZyM3ZvVmJi
        eWs0cnZxZEJRbTZaQTY4T0RJYTZqN0NlblE5a1k4VWR2VEFLTVVQM0Z4T283T0Mv
        OWRzTndlY000K2RQcEZUbW1wMll0ZWFyWkYyT0E4WHN2bUNvM0Nmc2p0cCtjK2Na
        b1hVUzlTcDJabkJlMWROc3luRzFlWnhHanlzUURZdWZpcWoxL3BRZTJDeE9IZwpi
        elkyclFVNmFQZkdrV0V2bzBsMXJobVBZOHg4MlBISUtuRHZCL0lQbmtvCi0tLSAv
        RGxnMkxEcXp3QWwySG5HRDdtam5Ha3EzcFpidTJ1RjcxN3V5RVVPREhnCoGo3Kzw
        BiWJ0v29rYgJ5VMozDtgZKd5HFMfOXuLS9EK6wXK/DY3fUyeuLrdULH+0iJVxL0k
        W5aLUxStMCsHkzY=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1pcc952wp5r5svd72s6anpqzpth2m3lzzp7t5p072dxss4jeymjwrrq8gw5c7szx0lwtazuyvnlupq5n8zv2nxhq7yzwp34pkxdvnaj2u3evlddrkyqxrje255vefhhru9jzqe9z7yja78wgw5ffvlzlqcgrrsu5n0dpaxf9ra8gzdryyht90z4w45wa03keqrgfxyfmrsz30wz7dkgrhr6us499q2pnuj6pthq48qksqmqy8tlpnfv7qr2kswqycnsdal5srludhclg80enjvth6ngmfwmp82u3thdsjghge5zs77qqzm5as39v4e6mxz8lf8g0wg3ds6gaguhj9f3hqs448c988x4hcqyfe97urr00qhverqec22flfkgkgngs8awpkwjeez93mp0zuk7agmygmdrcy8z9zsp6z27sl8f3x6tsgelg3gf8tj86pedvp0etllw3qqyw6wpdq0fggq7qcv6xw6eghzdhv0ljkwwg5v9ahdsy5ngs6673khfhqr8ae7yggk29mhqncgttx966fhfvq329edcza827tgmwvnj60x6hg4qnz4stsnfncmk6m0t00czqrpzuskvm368yth2s9gev0k7g762h6gx6709sred9qp6gr0qes9jadv3d94pynkpjhwmz449ypfy3pdqvhhn78zj92p9snqqqxavz8lzk88mcjdkeqhqvz4dgffja78pe44cukue7vxwdfstwgj24p4632fmzmnfrevst44ssr42kz064ez49mtyjvxmegrdsvadv8k635qffefl42w90f56mn5g0ww725tlay8hsuvevth0uh8vjjfaagkygr3cp3xpjuc9rwc2nyup6df4pk669f256m3ny3s53s6z6ra3sr773803z6z6f70zdqd2uxd36xtanrszj8scq882u8djntyreylvn9gppfyr4xgf67e7at542222cvyusm8jchcqzy7xpuh6v88qf59cw7j5vmmx53q2cpvdgsxeeptyp9tq4pvxshkz9c9muv6lz5ttupxss43z4er7tnsdg42kfzy2qvtfsypfk7wqupv63kg9kfp30nyqcf02v8pd5gl0dzj02eheq35u8fxy705wmu9gp9ytptetz9yrdszzxmszac90un82sgvf42g4v4jp9f4a70gkazhf5vng2pct7z99ggh46lccwgvfjxvmwfz5ff8j5jmzrhpu9nzmtvr8x8evn82gl9h6p5gkm28uhurlwtg32uh8yst3zlq9xygwu2hcm32lj0f3h0kecvvd4m59gteyjs9zpelyj90k4p0g9jrsz5y8edjrhdzanrm353xd6hymuh2qu890k97dgp3ppds56gsza50ddcxve36xr3f4ft08dxlax5589nscuagaa8v0zcntf4d5asrzu8jknr42rk2y34mu54r0cjc0quy278yf657ez2nt33cr9qy3xesvx9uc60juwteuqvttec8knag9mv3q0d3jq9dau8cp5295m4dzjzya384k36rpjgl85r5weaqk60vlymnuugzpj5tyur3sxjds7p55ndjeflhu237zuu84fdpze2csnqzf3ak8q6qz7cjxsaqjhnv5y5ysp99w35u6rxs4u0f03ks7tv9de90cv5cca6sq2pfr6mv4nw8eu52qtp93dn4hgnzfven2r3lrpwelkr3mrpwn4wcrwcqjzytcuzse54ug9hdfnxn8f6edpqy9ztjwnp9mfy2w32keapqjk8dcvjd6n6yzkk2hry55d8cww4p74sdgwrghh84hx4wg57udyul3tmzpmfue7te9wtrxpn6gu287eu42xz2h3f88genu26030ve4nwvs0xcghmflvcjpp0sk5h9476vezhvp2k3kqyjvvt57qel7y8n4f70kn5ffna4m20x3pn2uy3d5c2ywqt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-22T15:14:29Z"
  mac: ENC[AES256_GCM,data:p4Xnw31a3NuiGutBEAnJuoQ3UKF8Dj/1GAl8C4xqreF2hhwkrjqwVuZVkc+LEAklqIjKiE/Zlm5PnJS2a2+uzmBTZJj1nZg0CBiBp8VzS7nIA5nlNJ5rq3hE4H7kBeaUcoDq5G/hcUWp3XWxRrpy6wYW/hts/WVLS/3jIH4lKsE=,iv:rAI0a8kYaUau9eC8nE07a5HdcsrBaS9pV9KTHmvZdS0=,tag:q62BFgu7TD1QBpmrMVMY1g==,type:str]
  version: 3.13.3
