apiVersion: v1
kind: Service
metadata:
  name: lldap-service
  labels:
    app.kubernetes.io/name: lldap
    app.kubernetes.io/instance: lldap
    app.kubernetes.io/component: lldap
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app.kubernetes.io/name: lldap
    app.kubernetes.io/instance: lldap
    app.kubernetes.io/component: lldap
  ports:
    - name: ldap
      port: 3890
      targetPort: ldap
    - name: ldaps
      port: 6360
      targetPort: ldaps
    - name: web
      port: 17170
      targetPort: web
