apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: vaultwarden
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/component: database
spec:
  cluster:
    name: postgresql
  name: vaultwarden
  owner: vaultwarden
  databaseReclaimPolicy: retain
