apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - configmap.yaml
  - deployment.yaml
  - httproute.yaml
  - persistentvolumeclaim.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml
images:
  - name: docker.io/grafana/grafana
    newTag: 13.2.0-slim
    digest: sha256:b035710db1d835beebcc7bd8d16d2d2735e9a97b341015b0951c8f7b0043fcec
labels:
  - pairs:
      app.kubernetes.io/part-of: monitoring
      app.kubernetes.io/version: 13.2.0-slim
