apiVersion: v1
kind: Secret
metadata:
  name: grafana
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/component: grafana
type: Opaque
stringData:
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:N+/dS4Py5cr99My9xIajVBgb7X6X1jcB1UgObFHNfw7hFJmd3tIWSRCC4f9RKqgVvHt51/PdNQsN4krBnJXpWvLZGZ2X4V1y,iv:1ni6pRQs/MgXHQFZyn5vZCqr1yXFofBTD61pyfFFzq4=,tag:GfNVAUADjmrbobGJFb7bGA==,type:str]
  GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:5QLa65NPjiT2TL1QFSEvGLPR7YRnyUKxtXwdMZ5TDoUbF5J1r4bslwIYpXAeary65DR4WPbqqxWv6LrFu2lD5w==,iv:6Z2WqFpOR0mjyLqIRYsJdRTcdSzA2xMLI85N9mC7NOo=,tag:3I7vAepvPgQBn5HwEGWRHA==,type:str]
  GF_NTFY_AUTH_TOKENS: ENC[AES256_GCM,data:/etTcCArzZ1TMlVkdgNw6BtVgvlD7C0F6a/qMGX5cdw=,iv:KfujjAkdcyBQUZLtRC5dPq1DY89OpvMwQDn7Fw3777o=,tag:LMpbpOO4RhAhTE68XS7kLQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFFxVmxHNXEx
        TE16cDZnQkNGUVBnSm91NnRlUzV4S0JRM3hxdXFVUW1RNlNDSXJQb1k3NTZFZVBH
        V0MvVHJKWU1QUWRnOWxOdlI0QkNQSkw2MTRleHNOV2VQdC9LODlPTDJUYVRZYlNy
        WVRwc0VlajRycGFvZit1WXdaVmdPMHdLdm1yWnZYVmViUW05MzRremNweS9FTmpM
        VVF3Smk1TVNZZm5VSDJYQ3FQUmRmVzVmeXFZZkVHaHJobmJ5MmlNSzJFMENMN3Bn
        ZmdEa0tqc054VytMMWYzanY3eU9zODZrQi9NWVN5VDVlQnp1VDhmN3gyMEtReVBl
        aDBXL0J4bXdSZVpyTmlEN0szdmk4cjNJV0hJUXgxYUVVdENNdWlJSFFSaUUvazAy
        VkNyNlBmZDUrSXdRN1JTNmR2VWExeHB6VGlVUTJyeEEyR2o2emZpTWF2dmJRYkV5
        dSswb0QrejBWMVVBVEZhVlVDWk5nUGUzcEI2YVNxZXhDeUhNanlFUVRqdG45cElR
        Y1ZqME50U004d2V6NitMU24vZU10OHZlRDFzM3d5NG9LQTBkOXRMQ1NkK1RwNlBo
        anlJUzJvalF0N1hkZXZUODVNSVZHWUNiWHBiTjRKSmhGdHRBWGhLT2gxc0gyNUw5
        djUrbTZrWUM0ZkxqOG41UzFMbGNpNXJkalNBVGZPa3d0QWdpamh4Z01paytXL3BC
        Z1B5eVNsdlg3ams1bk9nL0IvN0ROTkN2MG1la2owSmVMcWFKeGMvYmFVQ2g1QWlj
        bmU3cnlROElFRE1ZUHB2dXp3NWxxQktic2k3Ulp6cGxDYWlyVmt4dFJscy82VXMr
        U1N6b2NxNlhBeTlyZlpEZllVaVpCWkZlTTFacWsyK1ZBYzN6TElxNXBQZU5haUtZ
        Y1pHc1MwTUFhZ0w0RTBVbk42eWpTMzFkeTVXekdoVmYzaTNSTUNNbTJUVE5DU1cy
        S2dTd2tHTWMrRlVwZWhvay9UVkNoakRreHJqSTlheFdZMkRhbGEybVpJb0lVYW1K
        VEpTMDR5UWMxaGNzNzd2WkNTTmkwUUlYaGhBbm5MNmR4UmRwOFNnTG5xbnZ0bmtB
        Zlljb0UvQWJRdVRacjdzTENCL0N3OFNEanVzdHBHZk1DdDFRRDNwOHc1eXV5aVVq
        MGRObXJqdDZhMjNBdU1ZeTNzMjhXNll4UmZwS0dvdzhLZHZOMVk2VUl1YU81SDVl
        V1JOek8xRFRZYXA1QmNZejl4eDZ6dHVROGF4OWhYUEpDNVZsOUtTOUt0UkN0eHor
        ZmZERGZwUmE5Rnd6UHpvWmRvVWZYWndjbXVKdDZqUFFhNHd1WXN1UkxRbHg3TlFD
        RWlnR0VzVmNTUjdMaGM5bjVkU0FLSk5IM1lINm1jZVZyYzB6bHJKdHRicFg1STBi
        Y0xrRnhkWlk3ZHg0b2VxZGJvYUoxZHpRVlg3d2lYaVgxTC81eENSMzhXZnRzb0hL
        MzUyd05PTm42NU1zLzB0VG1PUFpDQXpiSzVqSWxXeURNcEdtZHpBYU54ckJrSk1v
        M2ZYR1RqQUI1VEk2RFpsdDE1RXFsdzlhNE5kODlYNmw1b2xvakxySWk5RjR1Qnh1
        dWZUdVEwVE5UQ0p2dW9JcGlVTjRoMXg5YnFoSG5pdHE3dkdxNE02YzFjcFpnMUlk
        UzExTzZ1Q0N3dXNhWEN0NzdtVnRVMU5yNkdlN2xnT3JqV1crTnVRS05aZm5oNGI0
        bERYMmpNUnJaQTNRM2FSUlR5aFBadU9hdG9NWXYxWHg4bnNkYTJSWUpzaGJGaFJR
        WlVyTCtMSG9CVTJIOVlpYnNnVjVDTkVUQVZjQXZIUVJCZFlGQXlPMVMrRnkyNEt1
        c3EwVEc3QnFZdnhrUkZQSXp5SXpKZjl3MjRFRldNWE9uRm5yVUhmR0xsUktpKzQ5
        bG9uQ0lZZ0lmMGtCUHV6MGd1czUyR3grV3BuYnhmNHJKRHRCVWtlVVczRlVEdwpv
        OUUwQlFSSm5XNmQrT0ViNWxQRU5wSWhSUnQvMGJJaGZqRXlZWUM0U0lFCi0tLSBu
        ZFJ4aFhLY2JuN1FISVdYYWtza3lRdWpUOHFiOFRtd0U0a3hURHJmNVpnCsjYLpiI
        8pMEc5/ZNa6uc9o8ysMV55EcB2W4uBIuLECqAmDmVLSI78Hvn12vaofMOs5b96fr
        qdDwIOrWAD0+Orc=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1pcc952wp5r5svd72s6anpqzpth2m3lzzp7t5p072dxss4jeymjwrrq8gw5c7szx0lwtazuyvnlupq5n8zv2nxhq7yzwp34pkxdvnaj2u3evlddrkyqxrje255vefhhru9jzqe9z7yja78wgw5ffvlzlqcgrrsu5n0dpaxf9ra8gzdryyht90z4w45wa03keqrgfxyfmrsz30wz7dkgrhr6us499q2pnuj6pthq48qksqmqy8tlpnfv7qr2kswqycnsdal5srludhclg80enjvth6ngmfwmp82u3thdsjghge5zs77qqzm5as39v4e6mxz8lf8g0wg3ds6gaguhj9f3hqs448c988x4hcqyfe97urr00qhverqec22flfkgkgngs8awpkwjeez93mp0zuk7agmygmdrcy8z9zsp6z27sl8f3x6tsgelg3gf8tj86pedvp0etllw3qqyw6wpdq0fggq7qcv6xw6eghzdhv0ljkwwg5v9ahdsy5ngs6673khfhqr8ae7yggk29mhqncgttx966fhfvq329edcza827tgmwvnj60x6hg4qnz4stsnfncmk6m0t00czqrpzuskvm368yth2s9gev0k7g762h6gx6709sred9qp6gr0qes9jadv3d94pynkpjhwmz449ypfy3pdqvhhn78zj92p9snqqqxavz8lzk88mcjdkeqhqvz4dgffja78pe44cukue7vxwdfstwgj24p4632fmzmnfrevst44ssr42kz064ez49mtyjvxmegrdsvadv8k635qffefl42w90f56mn5g0ww725tlay8hsuvevth0uh8vjjfaagkygr3cp3xpjuc9rwc2nyup6df4pk669f256m3ny3s53s6z6ra3sr773803z6z6f70zdqd2uxd36xtanrszj8scq882u8djntyreylvn9gppfyr4xgf67e7at542222cvyusm8jchcqzy7xpuh6v88qf59cw7j5vmmx53q2cpvdgsxeeptyp9tq4pvxshkz9c9muv6lz5ttupxss43z4er7tnsdg42kfzy2qvtfsypfk7wqupv63kg9kfp30nyqcf02v8pd5gl0dzj02eheq35u8fxy705wmu9gp9ytptetz9yrdszzxmszac90un82sgvf42g4v4jp9f4a70gkazhf5vng2pct7z99ggh46lccwgvfjxvmwfz5ff8j5jmzrhpu9nzmtvr8x8evn82gl9h6p5gkm28uhurlwtg32uh8yst3zlq9xygwu2hcm32lj0f3h0kecvvd4m59gteyjs9zpelyj90k4p0g9jrsz5y8edjrhdzanrm353xd6hymuh2qu890k97dgp3ppds56gsza50ddcxve36xr3f4ft08dxlax5589nscuagaa8v0zcntf4d5asrzu8jknr42rk2y34mu54r0cjc0quy278yf657ez2nt33cr9qy3xesvx9uc60juwteuqvttec8knag9mv3q0d3jq9dau8cp5295m4dzjzya384k36rpjgl85r5weaqk60vlymnuugzpj5tyur3sxjds7p55ndjeflhu237zuu84fdpze2csnqzf3ak8q6qz7cjxsaqjhnv5y5ysp99w35u6rxs4u0f03ks7tv9de90cv5cca6sq2pfr6mv4nw8eu52qtp93dn4hgnzfven2r3lrpwelkr3mrpwn4wcrwcqjzytcuzse54ug9hdfnxn8f6edpqy9ztjwnp9mfy2w32keapqjk8dcvjd6n6yzkk2hry55d8cww4p74sdgwrghh84hx4wg57udyul3tmzpmfue7te9wtrxpn6gu287eu42xz2h3f88genu26030ve4nwvs0xcghmflvcjpp0sk5h9476vezhvp2k3kqyjvvt57qel7y8n4f70kn5ffna4m20x3pn2uy3d5c2ywqt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-23T14:53:00Z"
  mac: ENC[AES256_GCM,data:RCwccNU3wTvQ8XvQrjs+ANNVe9XqWEVIa532tKNwsm3ADwXdNct3ntb2b/O9yt5bB635NqU2zesPFKOFBUc2ctkun3+rqabmmAQilbiwj3Bo11S4E+gtfcTuLgxdX0IcaIx24mCFtM5yik5m2tdb7ElijOx+tWEu/2CXPR6tnU8=,iv:HeUTe+kIZJl6KhZBlDQBv3zLrXiYgNLzVGdXj75b7sg=,tag:WUtD8m5y5vvUuV5WG/TPxQ==,type:str]
  version: 3.13.3
