apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich-database
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/component: database
spec:
  cluster:
    name: postgresql
  name: immich
  owner: immich
  extensions:
    - name: vector
      ensure: present
    - name: vchord
      ensure: present
    - name: earthdistance
      ensure: present
    - name: cube
      ensure: present
  databaseReclaimPolicy: retain
