apiVersion: v1
kind: Secret
metadata:
  name: immich-database
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/component: database
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:0xY67u/f,iv:50DsjZrUZMIHdna4F2+j05xY3Y4lyJhQHIidOylD96o=,tag:zbJca/vtRDTSDDKnbnXUUg==,type:str]
  password: ENC[AES256_GCM,data:QYKmpB4IEgxmWyYYXfe7mdQFMh7WhKsoogeS/w2i+aywnKHseXkssFyO6YlGR228M399+sQsIMoOBf6fi2eNGg==,iv:5BxKioBGWPWjiSwDoEOpziDl4Tp1AVCsbesztRXGNrg=,tag:7bK4qfXfRfT5kcKWPdy0pg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDdBeXZXZDN6
        QjNpbUIwUzU0U1pGempuYmVWQ1hxNXQvQmpoSmYzcHdDb2xFNUhEWHFuakM3NFhF
        NC9PNGs2dlkwTHprSDBBcUNMT1o4M2lyS3NOR2xCcmZMdDd4ZFcwRlQxcnFENDVV
        TUpDT1oyUGhlNS9EekJwdUFlb3dyWS81QldrTFlTM1RDY3JFVXlLaFpKSzFSYUMv
        L2k5Ynp0dkxDWWZaVUZqM0ZKenRFUWZqRW9uU3IxSEpxaVZPajBOVzBBZlp6MkJD
        RWpRY0FrdllWVldlUjlJUStUcXc3VWhkbE5MdVhCd2dnenV6ZFhzbS9iRkFxYTBi
        L2dBQ2Z1UmR3SzdQa1dhdnZVWmorL0prRXNSNHZXcDhxaGMxSW4wRCtXK0crblNh
        aUJTQkp4ejdmRVUvYjVYMmVEZ0NENTFQQUQ0a0xHbko1cWUrS2g4Rk1oRUtqM1Z3
        YVNzSlVBQ20wV0xCWnNtYUg4emVadVFKVlY3TFJFSjBUak5mQm1YRURxU3Z0a1da
        SU44Zkp2aE5ORHdBaVBOV2RrRVNvZ0Y1bVp3TGtOUkppczlTRXVnVERVTHJ1RFNL
        cEVJcTBleDhaU2RycXMzaWd4eFdpbzJhVTUvd2ppWkdWd0Uwd3VncjJwdC9PWEg1
        dTlhdmNOVkNWaVdhR2w3MjlhZ1RUN3dYNVJ3NTh0UzZNYTNaS3RwTFlvdnZnbXl5
        aGp3aVZNTXBzaHErR3U4S0wwQStuY3JTRU01TEUvd1FjME5oVWhKeW5tcVRqQ29q
        ZEUraVN3dCszc0dhdzFNMXZzYzBOODllb29talJ6NmMveWdyR0MxNlI5bTk5c3g5
        Zk8xZE1ncWhsNGdTalpmbGJ5ZktsVE0vU3ljN3FBSVlPNEREczFTV0JHSnREQ3Rw
        eGZNY2hhaEJ5b2VzNlFibkZNdXFJNUZMQ0RnZTd4VjRJRXJGSTlxVkhRMER3b1ZL
        MkhBdkE3am0rWit2eEgydkdZL1lJUndtblJvUVE3U1JGMkl0MkkzNHJZUzAzV3Fs
        aUU4ZUNBZ3JQNENOREhqejFWQUZSMVVteWFDWFY0L1U5RFZ1UEwvL05zZm1DTnpi
        VVE4NHRYN0M2VmJyYnh1T25DV0R2K3FyMUFUTWo0VFNYanJ2RzNVa1FmZ3VXSDg0
        d2hINmpFTklRYVlQZGd1OXdqYVRTUTVWNkZneUJXTlZtZFNERXNjN2lNblFXd29J
        RGt5cnN2OUs0U0RxMVBzV3c3ZmtsaHBDMzBzTnRvd0ZOOXE3SzJBa1IwSFNUVDI0
        dHRYaDJtZkNPVmFDdFMva1QxMnVmcW5FVnZCbEFkWkk5M2VNbElEY29WNDZnQUVr
        TEluRHZhSXNLaEIxRHk3QXZyT1R3UzJkNThTVVZMYlIvSzR6RHo0dGE1cDhOb3Zl
        RHRGakVBT1NwcmMrZUtlbTlCVkZwUk14VGg5SVlLT1dpcWdJZUxXMDFYRGM4alIz
        VlhaQUcyM3ZsSUh4TWtwbW4xbm1oZ21HaStxcFVxUVZVN1dTcndjbXRhQXg2aXRw
        dFpuek1TaWNKNGRqTGF4ajk2VEd5Wk1GYXFWbm9xUXFudXc5NVlHWEg5WjgxM2dn
        OFJ5Q2MyR21XYUFldmNxcVA0SWdlSklSWE4yMmE1VEswNnNQQnozWlZuN3dKZDV1
        clQyZDhMcFgzYnBNZ21xeVErSWYrcDRUMVQ5a2w0Q1lxZE91UUE0a3FmdXlid0lB
        MlE1SWRKcGNGL2xOVXJuL0V6OHhlQzVRckFzTlRHMm01Qy8wTWttQnZuM1VyWjI0
        THI2Y2tWUHJ4MGorT2dzZlp4UU9oMS96MHNNMGtCbjJFLy9UblFZYlR3ME9sQ2U3
        ZGZIaDlQUVJLM1RYeDFtcmI5MUNqV2M1bE1SZUNJYnlST0R2cXJxT29zM01oR0k2
        NUhCbG5xVjVsMjF2WDh3TUxZQUdjN2wvOUNTTVRsODdPQXNLYk0xQkozTklUUQoy
        dGIzZFJldzhkdFZKSTVnaHlMb1hGQXBYVkxMeWMxR3RWWDVwY044TUNjCi0tLSAy
        OHp4aEFLTE1Wa3htL0Vud0tQT25IbDFNVTZmVlkwWWhUSnRVK3NVTkxBCuM6e0Op
        P0GZVmd/mHQDcTjE9SKJhVxuBc2gghyydh8NeOAbunh2e6pawsEnQK7X/sg4BcHt
        ZpkCgHIFt1c2iuM=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1pcc952wp5r5svd72s6anpqzpth2m3lzzp7t5p072dxss4jeymjwrrq8gw5c7szx0lwtazuyvnlupq5n8zv2nxhq7yzwp34pkxdvnaj2u3evlddrkyqxrje255vefhhru9jzqe9z7yja78wgw5ffvlzlqcgrrsu5n0dpaxf9ra8gzdryyht90z4w45wa03keqrgfxyfmrsz30wz7dkgrhr6us499q2pnuj6pthq48qksqmqy8tlpnfv7qr2kswqycnsdal5srludhclg80enjvth6ngmfwmp82u3thdsjghge5zs77qqzm5as39v4e6mxz8lf8g0wg3ds6gaguhj9f3hqs448c988x4hcqyfe97urr00qhverqec22flfkgkgngs8awpkwjeez93mp0zuk7agmygmdrcy8z9zsp6z27sl8f3x6tsgelg3gf8tj86pedvp0etllw3qqyw6wpdq0fggq7qcv6xw6eghzdhv0ljkwwg5v9ahdsy5ngs6673khfhqr8ae7yggk29mhqncgttx966fhfvq329edcza827tgmwvnj60x6hg4qnz4stsnfncmk6m0t00czqrpzuskvm368yth2s9gev0k7g762h6gx6709sred9qp6gr0qes9jadv3d94pynkpjhwmz449ypfy3pdqvhhn78zj92p9snqqqxavz8lzk88mcjdkeqhqvz4dgffja78pe44cukue7vxwdfstwgj24p4632fmzmnfrevst44ssr42kz064ez49mtyjvxmegrdsvadv8k635qffefl42w90f56mn5g0ww725tlay8hsuvevth0uh8vjjfaagkygr3cp3xpjuc9rwc2nyup6df4pk669f256m3ny3s53s6z6ra3sr773803z6z6f70zdqd2uxd36xtanrszj8scq882u8djntyreylvn9gppfyr4xgf67e7at542222cvyusm8jchcqzy7xpuh6v88qf59cw7j5vmmx53q2cpvdgsxeeptyp9tq4pvxshkz9c9muv6lz5ttupxss43z4er7tnsdg42kfzy2qvtfsypfk7wqupv63kg9kfp30nyqcf02v8pd5gl0dzj02eheq35u8fxy705wmu9gp9ytptetz9yrdszzxmszac90un82sgvf42g4v4jp9f4a70gkazhf5vng2pct7z99ggh46lccwgvfjxvmwfz5ff8j5jmzrhpu9nzmtvr8x8evn82gl9h6p5gkm28uhurlwtg32uh8yst3zlq9xygwu2hcm32lj0f3h0kecvvd4m59gteyjs9zpelyj90k4p0g9jrsz5y8edjrhdzanrm353xd6hymuh2qu890k97dgp3ppds56gsza50ddcxve36xr3f4ft08dxlax5589nscuagaa8v0zcntf4d5asrzu8jknr42rk2y34mu54r0cjc0quy278yf657ez2nt33cr9qy3xesvx9uc60juwteuqvttec8knag9mv3q0d3jq9dau8cp5295m4dzjzya384k36rpjgl85r5weaqk60vlymnuugzpj5tyur3sxjds7p55ndjeflhu237zuu84fdpze2csnqzf3ak8q6qz7cjxsaqjhnv5y5ysp99w35u6rxs4u0f03ks7tv9de90cv5cca6sq2pfr6mv4nw8eu52qtp93dn4hgnzfven2r3lrpwelkr3mrpwn4wcrwcqjzytcuzse54ug9hdfnxn8f6edpqy9ztjwnp9mfy2w32keapqjk8dcvjd6n6yzkk2hry55d8cww4p74sdgwrghh84hx4wg57udyul3tmzpmfue7te9wtrxpn6gu287eu42xz2h3f88genu26030ve4nwvs0xcghmflvcjpp0sk5h9476vezhvp2k3kqyjvvt57qel7y8n4f70kn5ffna4m20x3pn2uy3d5c2ywqt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-22T15:14:29Z"
  mac: ENC[AES256_GCM,data:E5EyIHPipoXhltAAEc8fHlN0EhBz1YpFOfZYYqV9HSbyxNQPxYE2Hm4iaR+spo/GyuBJMI6JczaFaiZjBpCHZqlJcviqgGe1zP9YjCJ2DccjXoCS5EMxxIylJdgIhRVE72TxqhqtFLiTSwj0PL7Pjh85cBeTqrjLvVhGRYQfxIo=,iv:kTATkbR0a7ZuZxEUKFmXn1Dqqekgl/hOdz2/FFomft0=,tag:Oy0t0SxHq3TFQDmVbjRGEg==,type:str]
  version: 3.13.3
