apiVersion: v1
kind: ServiceAccount
metadata:
  name: victoria-metrics-single-server
  labels:
    app.kubernetes.io/name: victoria-metrics-single
    app.kubernetes.io/instance: victoria-metrics-single
    app.kubernetes.io/component: server
