apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics-single-server
  labels:
    app.kubernetes.io/name: victoria-metrics-single
    app.kubernetes.io/instance: victoria-metrics-single
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: victoria-metrics-single
    app.kubernetes.io/instance: victoria-metrics-single
    app.kubernetes.io/component: server
  ports:
    - name: http
      protocol: TCP
      port: 8428
      targetPort: http
